<?php

require_once __DIR__.'/helpers.php';

return paramedic_levels([
    [
        'title' => 'Mixed Assessment — Chest Pain vs Anxiety',
        'scenario' => '58-year-old with chest tightness after argument. Diaphoretic, HR 108, BP 142/88. No cardiac history documented.',
        'question' => 'Select all appropriate prehospital actions for this presentation.',
        'options' => [
            'twelve_lead' => 'Acquire 12-lead ECG',
            'aspirin' => 'Prepare aspirin per ACS protocol if no contraindication',
            'dismiss' => 'Dismiss as anxiety without evaluation',
            'vitals' => 'Serial vitals and continuous monitoring',
            'transport' => 'Transport if ACS cannot be excluded',
            'benzo' => 'Immediate benzodiazepine before any cardiac workup',
        ],
        'correct' => ['twelve_lead', 'aspirin', 'vitals', 'transport'],
        'explanation' => 'NHTSA EMS and NIH NHLBI ACS guidance: cannot exclude MI based on anxiety alone — 12-lead, monitoring, aspirin when appropriate, and transport per CDC chest pain evaluation pathways.',
    ],
    [
        'title' => 'Cardiology — ACLS Priorities',
        'scenario' => 'Patient in monomorphic VT 180/min, BP 70/40, altered mental status, pulses present.',
        'question' => 'Select all correct management elements.',
        'options' => [
            'cardiovert' => 'Synchronized cardioversion for unstable VT with pulse',
            'adenosine' => 'Adenosine 12 mg as first-line for wide-complex tachycardia',
            'monitor' => 'Continuous cardiac monitoring and IV access',
            'amio_stable' => 'Amiodarone as first choice when patient is unstable',
            'sedation' => 'Sedation/analgesia if possible without delaying cardioversion',
            'observe' => 'Observation only since pulses are present',
        ],
        'correct' => ['cardiovert', 'monitor', 'sedation'],
        'explanation' => 'AHA ACLS unstable tachycardia pathway requires synchronized cardioversion. Amiodarone is for stable VT. Adenosine is not for unstable wide-complex tachycardia per NHLBI arrhythmia guidance.',
    ],
    [
        'title' => 'Airway — Respiratory Failure Signs',
        'scenario' => 'COPD patient somnolent, RR 8/min, SpO₂ 84% on 15 L NRB, EtCO₂ 72 mmHg.',
        'question' => 'Select all findings indicating need for ventilatory support escalation.',
        'options' => [
            'somnolence' => 'Altered mental status from hypercapnia',
            'bradypnea' => 'Respiratory rate 8/min',
            'hypercapnia' => 'EtCO₂ 72 mmHg',
            'high_flow_o2' => 'Continued 15 L NRB targeting 100% SpO₂',
            'niv' => 'BiPAP/CPAP per protocol if alert enough initially',
            'ignore_co2' => 'Ignore capnography in COPD',
        ],
        'correct' => ['somnolence', 'bradypnea', 'hypercapnia', 'niv'],
        'explanation' => 'NIH MedlinePlus COPD guidance: somnolence, bradypnea, and hypercapnia indicate ventilatory failure. Titrate O₂ to 88–92%; NIV or intubation if failing per NHTSA respiratory protocols.',
    ],
    [
        'title' => 'Pharmacology — Anaphylaxis Dosing',
        'scenario' => 'Adult 60 kg anaphylactic shock after bee sting. Stridor, BP 76/40 despite first IM epinephrine 5 minutes ago.',
        'question' => 'Select all appropriate medication actions.',
        'options' => [
            'repeat_epi' => 'Repeat IM epinephrine 0.3–0.5 mg per FDA labeling',
            'fluids' => 'IV crystalloid bolus for distributive shock',
            'antihistamine_only' => 'Diphenhydramine as sole repeat treatment',
            'albuterol' => 'Nebulized albuterol for bronchospasm component',
            'wait_60' => 'Wait 60 minutes before second epinephrine',
            'iv_epi_first' => 'Routine 1 mg IV epinephrine push as standard repeat dose',
        ],
        'correct' => ['repeat_epi', 'fluids', 'albuterol'],
        'explanation' => 'FDA epinephrine auto-injector labeling supports repeat IM dosing. IV epinephrine 1 mg is arrest dose — not routine anaphylaxis repeat. Antihistamines are adjuncts per CDC anaphylaxis guidance.',
    ],
    [
        'title' => 'Trauma — Hemorrhage Control',
        'scenario' => 'GSW thigh with femoral hemorrhage. BP 92/58, HR 132, tourniquet not yet applied.',
        'question' => 'Select all priority trauma interventions.',
        'options' => [
            'tourniquet' => 'Direct pressure and tourniquet for life-threatening extremity hemorrhage',
            'iv' => 'IV/IO access for resuscitation',
            'scene_time' => 'Prolong scene time for complete secondary survey before transport',
            'txa' => 'Tranexamic acid per protocol if within time window',
            'hypotensive_resus' => 'Permissive hypotension consideration for penetrating trauma per protocol',
            'oral_fluids' => 'Oral hydration for shock',
        ],
        'correct' => ['tourniquet', 'iv', 'txa', 'hypotensive_resus'],
        'explanation' => 'CDC Stop the Bleed and NIH trauma guidance prioritize hemorrhage control and balanced resuscitation. Minimize scene time per NHTSA field triage — transport after life threats addressed.',
    ],
    [
        'title' => 'Stroke — Transport Criteria',
        'scenario' => '72-year-old sudden right facial droop and slurred speech 20 minutes ago. FAST positive. BP 168/98.',
        'question' => 'Select all correct stroke system actions.',
        'options' => [
            'transport' => 'Rapid transport to stroke-capable center',
            'notify' => 'Pre-arrival stroke alert with last known well time',
            'withhold' => 'Withhold transport until symptoms resolve',
            'glucose' => 'Check blood glucose before stroke alert',
            'bp_manage' => 'BP management per protocol without delaying transport',
            'tpa_field' => 'Administer IV tPA prehospital routinely',
        ],
        'correct' => ['transport', 'notify', 'glucose', 'bp_manage'],
        'explanation' => 'CDC stroke systems of care and NIH stroke scale guidance require rapid transport, notification, glucose check, and BP management without delay. tPA is hospital-based after imaging.',
    ],
    [
        'title' => 'Pediatrics — Weight-Based Resuscitation',
        'scenario' => '5-year-old 20 kg in pulseless arrest after drowning. CPR in progress.',
        'question' => 'Select all pediatric arrest interventions per PALS.',
        'options' => [
            'defib_2j' => 'Initial defibrillation 2 J/kg (40 J)',
            'epi_01' => 'Epinephrine 0.01 mg/kg IV/IO every 3–5 minutes',
            'adult_dose' => 'Adult epinephrine 1 mg regardless of weight',
            'compressions' => 'Compression depth ~1/3 AP chest diameter',
            'delay_shock' => 'Delay all shocks until 10 minutes CPR',
            'broselow' => 'Use length-based tape if weight unknown',
        ],
        'correct' => ['defib_2j', 'epi_01', 'compressions', 'broselow'],
        'explanation' => 'AHA PALS and CDC pediatric resuscitation guidance use weight-based defibrillation and epinephrine. Broselow tape supports dosing when weight unknown per NHTSA pediatric readiness.',
    ],
    [
        'title' => 'Obstetrics — Eclampsia Management',
        'scenario' => '34 weeks pregnant, postictal after seizure, BP 184/112, hyperreflexia, headache.',
        'question' => 'Select all appropriate management elements.',
        'options' => [
            'magnesium' => 'Magnesium sulfate per protocol',
            'left_lateral' => 'Left lateral positioning',
            'diazepam_first' => 'Diazepam instead of magnesium as first-line anticonvulsant',
            'bp_control' => 'Antihypertensive per protocol for severe range BP',
            'vaginal_exam' => 'Digital vaginal exam to assess dilation',
            'transport' => 'Transport to OB emergency capability',
        ],
        'correct' => ['magnesium', 'left_lateral', 'bp_control', 'transport'],
        'explanation' => 'FDA magnesium sulfate obstetric labeling and NIH preeclampsia guidance: magnesium prevents eclampsia recurrence. Avoid unnecessary vaginal exam. BP control and OB transport required.',
    ],
    [
        'title' => 'Operations — MCI Triage Principles',
        'scenario' => 'Warehouse collapse, limited resources, multiple casualties. START triage in use.',
        'question' => 'Select all correct MCI triage principles.',
        'options' => [
            'greatest_good' => 'Greatest good for greatest number resource allocation',
            'red_first' => 'Immediate (red) patients with salvageable life threats prioritized for transport',
            'black_expectant' => 'Black tag patients receive expectant care when resources exhausted',
            'green_first' => 'Ambulatory green patients receive first available ambulance',
            'start' => 'START: RPM — respirations, perfusion, mental status',
            'individual' => 'Treat every patient as single-patient priority ignoring others',
        ],
        'correct' => ['greatest_good', 'red_first', 'black_expectant', 'start'],
        'explanation' => 'NHTSA and CDC MCI triage (START/SALT) prioritize immediate salvageable patients, expectant category when appropriate, and resource allocation for greatest good — not first-come or minor injuries first.',
    ],
    [
        'title' => 'Integrated Readiness — Post-ROSC Bundle',
        'scenario' => 'ROSC after 18 minutes VF arrest. Intubated, BP 88/52, EtCO₂ 28 from rapid ventilation, SpO₂ 100% on 100% O₂.',
        'question' => 'Select all elements of appropriate post-ROSC care.',
        'options' => [
            'titrate_o2' => 'Titrate oxygen to SpO₂ 94–98%',
            'avoid_hypovent' => 'Reduce ventilation rate to target EtCO₂ 35–45 mmHg',
            'hypotension' => 'Treat hypotension with fluids and vasopressors',
            'hyperoxia' => 'Maintain 100% FiO₂ indefinitely',
            'hypervent' => 'Continue hyperventilation to EtCO₂ 25 for neuroprotection',
            'twelve_lead' => '12-lead ECG for STEMI identification',
            'terminate' => 'Terminate transport — ROSC means recovery',
        ],
        'correct' => ['titrate_o2', 'avoid_hypovent', 'hypotension', 'twelve_lead'],
        'explanation' => 'AHA post-cardiac arrest care and CDC resuscitation guidance: avoid hyperoxia and hyperventilation, support blood pressure, obtain 12-lead, transport to appropriate facility. Hyperventilation reduces cerebral perfusion.',
    ],
]);
