<?php

require_once __DIR__.'/helpers.php';

return paramedic_levels([
    [
        'title' => 'Failed BVM — Airway Escalation',
        'scenario' => 'Unresponsive trauma patient. Two-person BVM inadequate: SpO₂ 82%, EtCO₂ 55, gurgling upper airway. Gag reflex absent.',
        'instruction' => 'Sort each intervention into the correct category.',
        'categories' => ['basic' => 'Basic airway', 'advanced' => 'Advanced airway', 'vent' => 'Ventilation'],
        'items' => [
            ['id' => 'i1', 'text' => 'Head-tilt chin-lift or jaw thrust', 'category' => 'basic'],
            ['id' => 'i2', 'text' => 'Oropharyngeal airway insertion', 'category' => 'basic'],
            ['id' => 'i3', 'text' => 'Endotracheal intubation with capnography', 'category' => 'advanced'],
            ['id' => 'i4', 'text' => 'Supraglottic airway (i-gel/LMA)', 'category' => 'advanced'],
            ['id' => 'i5', 'text' => 'Two-person bag-valve-mask ventilation', 'category' => 'vent'],
            ['id' => 'i6', 'text' => 'Mechanical ventilator settings post-intubation', 'category' => 'vent'],
            ['id' => 'i7', 'text' => 'Nasopharyngeal airway in semiconscious patient', 'category' => 'basic'],
            ['id' => 'i8', 'text' => 'Needle cricothyrotomy in CICO', 'category' => 'advanced'],
        ],
        'explanation' => 'NIH MedlinePlus and NHTSA EMS scope support stepwise airway management: basic maneuvers and adjuncts, then supraglottic or endotracheal airways when BVM fails. Ventilation strategies confirm adequacy with capnography.',
    ],
    [
        'title' => 'Cardiac Arrest Airway Management',
        'scenario' => 'Witnessed VF arrest. CPR in progress. Team debating airway versus compressions priority.',
        'instruction' => 'Sort each intervention into the correct category.',
        'categories' => ['basic' => 'Basic airway', 'advanced' => 'Advanced airway', 'vent' => 'Ventilation'],
        'items' => [
            ['id' => 'i1', 'text' => 'OPA during BVM without interrupting compressions', 'category' => 'basic'],
            ['id' => 'i2', 'text' => 'Supraglottic airway after failed BVM with adjunct', 'category' => 'advanced'],
            ['id' => 'i3', 'text' => 'Endotracheal intubation by skilled provider with minimal pause', 'category' => 'advanced'],
            ['id' => 'i4', 'text' => 'Passive oxygen via nasal cannula during compressions only', 'category' => 'vent'],
            ['id' => 'i5', 'text' => 'BVM 30:2 before advanced airway placement', 'category' => 'vent'],
            ['id' => 'i6', 'text' => 'Continuous compressions with asynchronous ventilations after advanced airway', 'category' => 'vent'],
            ['id' => 'i7', 'text' => 'Suction of upper airway secretions', 'category' => 'basic'],
            ['id' => 'i8', 'text' => 'Waveform capnography to confirm tracheal placement', 'category' => 'vent'],
        ],
        'explanation' => 'AHA ACLS and NHTSA EMS guidance prioritize compressions; advanced airways may improve ventilation during arrest when placed with minimal interruption. Capnography confirms placement per NIH resuscitation standards.',
    ],
    [
        'title' => 'CHF Pulmonary Edema',
        'scenario' => 'CHF patient: SpO₂ 86%, RR 32, crackles bilaterally, BP 158/92, speaking word clusters.',
        'instruction' => 'Sort each intervention into the correct category.',
        'categories' => ['basic' => 'Basic airway', 'advanced' => 'Advanced airway', 'vent' => 'Ventilation'],
        'items' => [
            ['id' => 'i1', 'text' => 'High-flow oxygen via non-rebreather', 'category' => 'basic'],
            ['id' => 'i2', 'text' => 'CPAP or PEEP device per protocol', 'category' => 'vent'],
            ['id' => 'i3', 'text' => 'RSI if CPAP fails and patient obtunded', 'category' => 'advanced'],
            ['id' => 'i4', 'text' => 'Position upright/semi-Fowler if tolerated', 'category' => 'basic'],
            ['id' => 'i5', 'text' => 'Nitroglycerin per protocol (not airway but concurrent)', 'category' => 'basic'],
            ['id' => 'i6', 'text' => 'BVM if apneic after sedation for intubation', 'category' => 'vent'],
            ['id' => 'i7', 'text' => 'Endotracheal tube with lung-protective tidal volumes', 'category' => 'advanced'],
            ['id' => 'i8', 'text' => 'Capnography monitoring during NIV', 'category' => 'vent'],
        ],
        'explanation' => 'NIH MedlinePlus heart failure guidance supports NIPPV (CPAP/BiPAP) for acute cardiogenic pulmonary edema when alert. Intubation reserved for failure of NIV or inability to protect airway.',
    ],
    [
        'title' => 'COPD Exacerbation — CO₂ Retainer',
        'scenario' => 'COPD exacerbation: RR 28, SpO₂ 88% on 2 L NC, somnolent, EtCO₂ 62 mmHg.',
        'instruction' => 'Sort each intervention into the correct category.',
        'categories' => ['basic' => 'Basic airway', 'advanced' => 'Advanced airway', 'vent' => 'Ventilation'],
        'items' => [
            ['id' => 'i1', 'text' => 'Titrate oxygen to SpO₂ 88–92%', 'category' => 'basic'],
            ['id' => 'i2', 'text' => 'NPA if obtunded but ventilations needed', 'category' => 'basic'],
            ['id' => 'i3', 'text' => 'BiPAP/CPAP per protocol with monitoring', 'category' => 'vent'],
            ['id' => 'i4', 'text' => 'Endotracheal intubation if NIV fails or arrest imminent', 'category' => 'advanced'],
            ['id' => 'i5', 'text' => 'Bronchodilator nebulization', 'category' => 'basic'],
            ['id' => 'i6', 'text' => 'Avoid NRB 15 L/min targeting 100% SpO₂', 'category' => 'basic'],
            ['id' => 'i7', 'text' => 'EtCO₂ monitoring to guide ventilation rate', 'category' => 'vent'],
            ['id' => 'i8', 'text' => 'Surgical airway only in CICO scenario', 'category' => 'advanced'],
        ],
        'explanation' => 'NIH MedlinePlus COPD guidance warns against excessive oxygen in chronic retainers — titrate to 88–92%. NIV supports ventilation; intubation if failure per CDC respiratory emergency principles.',
    ],
    [
        'title' => 'Anaphylaxis Airway Emergency',
        'scenario' => 'Anaphylaxis: stridor, lip swelling, SpO₂ 89%, hoarse voice despite IM epinephrine.',
        'instruction' => 'Sort each intervention into the correct category.',
        'categories' => ['basic' => 'Basic airway', 'advanced' => 'Advanced airway', 'vent' => 'Ventilation'],
        'items' => [
            ['id' => 'i1', 'text' => 'High-flow oxygen', 'category' => 'basic'],
            ['id' => 'i2', 'text' => 'Repeat IM epinephrine', 'category' => 'basic'],
            ['id' => 'i3', 'text' => 'Nebulized epinephrine if protocol allows', 'category' => 'vent'],
            ['id' => 'i4', 'text' => 'RSI for progressive laryngeal edema', 'category' => 'advanced'],
            ['id' => 'i5', 'text' => 'Needle cricothyrotomy if cannot intubate/oxygenate', 'category' => 'advanced'],
            ['id' => 'i6', 'text' => 'CPAP on stridor patient', 'category' => 'vent'],
            ['id' => 'i7', 'text' => 'Albuterol nebulizer for bronchospasm component', 'category' => 'vent'],
            ['id' => 'i8', 'text' => 'Position of comfort; minimize agitation', 'category' => 'basic'],
        ],
        'explanation' => 'NIH MedlinePlus anaphylaxis guidance: progressive stridor requires repeat epinephrine and preparation for definitive airway. CPAP may worsen upper airway obstruction in angioedema — FDA epinephrine labeling supports repeat IM dosing.',
    ],
    [
        'title' => 'Asthma — Impending Respiratory Failure',
        'scenario' => 'Silent chest, exhaustion, RR 40, SpO₂ 90%, unable to speak, weak tidal volumes.',
        'instruction' => 'Sort each intervention into the correct category.',
        'categories' => ['basic' => 'Basic airway', 'advanced' => 'Advanced airway', 'vent' => 'Ventilation'],
        'items' => [
            ['id' => 'i1', 'text' => 'Continuous albuterol/ipratropium nebulization', 'category' => 'vent'],
            ['id' => 'i2', 'text' => 'High-flow oxygen', 'category' => 'basic'],
            ['id' => 'i3', 'text' => 'IM epinephrine if severe bronchospasm per protocol', 'category' => 'basic'],
            ['id' => 'i4', 'text' => 'RSI with ketamine or etomidate per protocol', 'category' => 'advanced'],
            ['id' => 'i5', 'text' => 'Ventilator with permissive hypercapnia post-intubation', 'category' => 'vent'],
            ['id' => 'i6', 'text' => 'Mag sulfate IV if protocol allows', 'category' => 'basic'],
            ['id' => 'i7', 'text' => 'BVM preoxygenation before RSI', 'category' => 'vent'],
            ['id' => 'i8', 'text' => 'Capnography after intubation', 'category' => 'vent'],
        ],
        'explanation' => 'NIH MedlinePlus asthma emergency guidance: silent chest and exhaustion signal critical obstruction — prepare assisted ventilation and advanced airway while continuing bronchodilators.',
    ],
    [
        'title' => 'Inhalation Injury — Structure Fire',
        'scenario' => 'House fire victim: hoarseness, singed nasal hairs, soot in nares, stridor at rest.',
        'instruction' => 'Sort each intervention into the correct category.',
        'categories' => ['basic' => 'Basic airway', 'advanced' => 'Advanced airway', 'vent' => 'Ventilation'],
        'items' => [
            ['id' => 'i1', 'text' => '100% oxygen; consider C-spine if trauma mechanism', 'category' => 'basic'],
            ['id' => 'i2', 'text' => 'Early RSI before airway edema progresses', 'category' => 'advanced'],
            ['id' => 'i3', 'text' => 'Small-tube ETT if significant edema anticipated', 'category' => 'advanced'],
            ['id' => 'i4', 'text' => 'BVM with PEEP valve if available pre-intubation', 'category' => 'vent'],
            ['id' => 'i5', 'text' => 'Suction of soot and secretions', 'category' => 'basic'],
            ['id' => 'i6', 'text' => 'Avoid CPAP with upper airway burns and stridor', 'category' => 'basic'],
            ['id' => 'i7', 'text' => 'Mechanical ventilation post-intubation', 'category' => 'vent'],
            ['id' => 'i8', 'text' => 'Cricothyrotomy backup if oral airway fails', 'category' => 'advanced'],
        ],
        'explanation' => 'CDC burn and inhalation injury guidance recommends early intubation when hoarseness, stridor, or facial burns present — airway edema progresses rapidly. High-flow oxygen treats CO exposure.',
    ],
    [
        'title' => 'Drowning Resuscitation',
        'scenario' => 'Pulled from pool: apneic, pulse 60 weak, cyanotic. Vomitus in mouth.',
        'instruction' => 'Sort each intervention into the correct category.',
        'categories' => ['basic' => 'Basic airway', 'advanced' => 'Advanced airway', 'vent' => 'Ventilation'],
        'items' => [
            ['id' => 'i1', 'text' => 'Manual inline spinal stabilization if trauma suspected', 'category' => 'basic'],
            ['id' => 'i2', 'text' => 'Suction and jaw thrust; two rescue breaths', 'category' => 'basic'],
            ['id' => 'i3', 'text' => 'BVM 10–12/min if pulse present', 'category' => 'vent'],
            ['id' => 'i4', 'text' => 'CPR 30:2 if pulse absent', 'category' => 'vent'],
            ['id' => 'i5', 'text' => 'Advanced airway if BVM inadequate or arrest', 'category' => 'advanced'],
            ['id' => 'i6', 'text' => 'OPA/NPA as adjuncts during BVM', 'category' => 'basic'],
            ['id' => 'i7', 'text' => 'Warm oxygen during ventilation', 'category' => 'vent'],
            ['id' => 'i8', 'text' => 'Capnography when advanced airway placed', 'category' => 'vent'],
        ],
        'explanation' => 'CDC drowning prevention and NIH MedlinePlus guidance: respiratory arrest from submersion requires immediate ventilation after clearing airway. CPR if pulseless; prioritize ventilations if bradycardic with pulse.',
    ],
    [
        'title' => 'RSI Medications and Equipment',
        'scenario' => 'RSI planned for trauma patient with GCS 8. Team preparing equipment and medications.',
        'instruction' => 'Sort each intervention into the correct category.',
        'categories' => ['basic' => 'Basic airway', 'advanced' => 'Advanced airway', 'vent' => 'Ventilation'],
        'items' => [
            ['id' => 'i1', 'text' => 'Preoxygenation with BVM and PEEP', 'category' => 'vent'],
            ['id' => 'i2', 'text' => 'Video laryngoscope and bougie', 'category' => 'advanced'],
            ['id' => 'i3', 'text' => 'Induction agent (etomidate/ketamine) and paralytic', 'category' => 'advanced'],
            ['id' => 'i4', 'text' => 'Endotracheal tube with stylet', 'category' => 'advanced'],
            ['id' => 'i5', 'text' => 'Waveform capnography for confirmation', 'category' => 'vent'],
            ['id' => 'i6', 'text' => 'Backup supraglottic airway device', 'category' => 'advanced'],
            ['id' => 'i7', 'text' => 'Suction catheter and Yankauer', 'category' => 'basic'],
            ['id' => 'i8', 'text' => 'Ventilator or BVM with inline capnography post-RSI', 'category' => 'vent'],
        ],
        'explanation' => 'NHTSA EMS airway standards and NIH MedlinePlus RSI guidance emphasize preoxygenation, backup devices, capnographic confirmation, and failed-airway planning including CICO rescue per Difficult Airway Society principles adopted in EMS.',
    ],
    [
        'title' => 'Obstructive Sleep Apnea Overdose',
        'scenario' => 'Opioid overdose reversed with naloxone but somnolent with obstructive respirations and SpO₂ 88%.',
        'instruction' => 'Sort each intervention into the correct category.',
        'categories' => ['basic' => 'Basic airway', 'advanced' => 'Advanced airway', 'vent' => 'Ventilation'],
        'items' => [
            ['id' => 'i1', 'text' => 'Jaw thrust and NPA/OPA adjunct', 'category' => 'basic'],
            ['id' => 'i2', 'text' => 'BVM ventilations until protective reflexes return', 'category' => 'vent'],
            ['id' => 'i3', 'text' => 'Recovery position if breathing adequate and protected', 'category' => 'basic'],
            ['id' => 'i4', 'text' => 'Endotracheal intubation if cannot maintain airway', 'category' => 'advanced'],
            ['id' => 'i5', 'text' => 'Supraglottic airway if BVM difficult', 'category' => 'advanced'],
            ['id' => 'i6', 'text' => 'Repeat naloxone titrated to respirations not full reversal', 'category' => 'basic'],
            ['id' => 'i7', 'text' => 'EtCO₂ monitoring during assisted ventilation', 'category' => 'vent'],
            ['id' => 'i8', 'text' => 'CPAP for obstructive sleep apnea in somnolent overdose', 'category' => 'vent'],
        ],
        'explanation' => 'CDC opioid guidance recommends ventilation support and titrated naloxone. Adjunct airways and BVM maintain oxygenation until protective reflexes return; intubate if unable to ventilate per NHTSA overdose protocols.',
    ],
]);
