<?php

require_once __DIR__.'/helpers.php';

return paramedic_levels([
    [
        'title' => 'Endocrine Emergencies',
        'scenario' => 'Match each presentation to the most likely endocrine emergency.',
        'question' => 'Match each finding to the correct diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'Hot skin, agitation, HR 140, glucose 420 mg/dL, fruity breath absent'],
            ['id' => 'l2', 'text' => 'Cool clammy, glucose 48 mg/dL, diaphoresis, responds to oral glucose'],
            ['id' => 'l3', 'text' => 'Kussmaul respirations, glucose 520, vomiting, pH 7.18 on i-STAT'],
            ['id' => 'l4', 'text' => 'Hypotension, hyperkalemia, hyperpigmentation, chronic steroid use missed'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'Thyrotoxic crisis'],
            ['id' => 'r2', 'text' => 'Hypoglycemia'],
            ['id' => 'r3', 'text' => 'Diabetic ketoacidosis'],
            ['id' => 'r4', 'text' => 'Adrenal crisis'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'NIH and CDC diabetes guidance distinguishes hypoglycemia, DKA, and thyroid storm. Adrenal crisis presents with refractory hypotension and hyperkalemia in chronic steroid users per FDA glucocorticoid labeling.',
    ],
    [
        'title' => 'Toxicologic Presentations',
        'scenario' => 'Overdose and exposure cases from a college campus. Match toxidrome to agent class.',
        'question' => 'Match each finding to the correct diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'Pinpoint pupils, RR 8/min, decreased LOC'],
            ['id' => 'l2', 'text' => 'Mydriasis, hyperthermia, diaphoresis, agitation, HR 130'],
            ['id' => 'l3', 'text' => 'QRS >120 ms, anticholinergic signs, prolonged QT'],
            ['id' => 'l4', 'text' => 'Garlic odor, pinpoint pupils, bronchorrhea, SLUDGE symptoms'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'Opioid overdose'],
            ['id' => 'r2', 'text' => 'Sympathomimetic (cocaine/amphetamine)'],
            ['id' => 'r3', 'text' => 'Tricyclic antidepressant overdose'],
            ['id' => 'r4', 'text' => 'Organophosphate poisoning'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'CDC poison center and NIH toxidrome resources describe classic patterns. Opioids cause miosis and respiratory depression; TCAs widen QRS; organophosphates cause cholinergic excess per FDA pesticide safety guidance.',
    ],
    [
        'title' => 'Electrolyte Disturbances',
        'scenario' => 'Dialysis and oncology patients with ECG changes. Match finding to electrolyte emergency.',
        'question' => 'Match each finding to the correct diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'Peaked T waves, absent P waves, sine wave pattern, K+ 7.4'],
            ['id' => 'l2', 'text' => 'Prolonged QT, U waves, muscle cramps, K+ 2.6'],
            ['id' => 'l3', 'text' => 'Trousseau sign, prolonged QT, tetany after alkalosis'],
            ['id' => 'l4', 'text' => 'Short QT, hyperreflexia, altered mental status, Mg 0.8 mg/dL'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'Hyperkalemia'],
            ['id' => 'r2', 'text' => 'Hypokalemia'],
            ['id' => 'r3', 'text' => 'Hypocalcemia'],
            ['id' => 'r4', 'text' => 'Hypermagnesemia (or severe hypomagnesemia with tetany)'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'NIH MedlinePlus electrolyte guidance: hyperkalemia widens QRS; hypokalemia prolongs QT with U waves; hypocalcemia causes tetany. Magnesium disorders affect neuromuscular excitability per NHLBI electrolyte resources.',
    ],
    [
        'title' => 'Pulmonary Emergencies',
        'scenario' => 'Dyspnea cases in mixed settings. Match presentation to diagnosis.',
        'question' => 'Match each finding to the correct diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'Sudden pleuritic pain, RR 28, SpO₂ 88%, unilateral decreased breath sounds, recent surgery'],
            ['id' => 'l2', 'text' => 'Gradual dyspnea, JVD, bilateral crackles, BP 168/100, orthopnea'],
            ['id' => 'l3', 'text' => 'Unilateral wheeze after choking episode, asymmetric breath sounds'],
            ['id' => 'l4', 'text' => 'Fever, productive cough, RR 24, SpO₂ 92%, unilateral consolidation on exam'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'Pulmonary embolism'],
            ['id' => 'r2', 'text' => 'Acute cardiogenic pulmonary edema'],
            ['id' => 'r3', 'text' => 'Foreign body airway obstruction'],
            ['id' => 'r4', 'text' => 'Community-acquired pneumonia'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'NIH NHLBI and CDC respiratory guidance: PE presents with sudden dyspnea and risk factors; CHF with JVD and crackles; aspiration/FBO with asymmetric findings; pneumonia with infectious signs.',
    ],
    [
        'title' => 'GI and Hepatic Emergencies',
        'scenario' => 'Abdominal emergencies from clinic referrals. Match presentation to diagnosis.',
        'question' => 'Match each finding to the correct diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'RUQ pain, Murphy sign, fever, nausea after fatty meal'],
            ['id' => 'l2', 'text' => 'Hematemesis, history NSAIDs/alcohol, BP 86/50, melena reported'],
            ['id' => 'l3', 'text' => 'Ascites, jaundice, confusion, asterixis, ammonia smell'],
            ['id' => 'l4', 'text' => 'Epigastric pain radiating to back, vomiting, lipase elevated on i-STAT'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'Acute cholecystitis'],
            ['id' => 'r2', 'text' => 'Upper GI hemorrhage'],
            ['id' => 'r3', 'text' => 'Hepatic encephalopathy'],
            ['id' => 'r4', 'text' => 'Acute pancreatitis'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'NIH digestive disease resources describe RUQ cholecystitis, variceal/ulcer GI bleed with shock, hepatic encephalopathy in cirrhosis, and epigastric radiation in pancreatitis per CDC alcohol-related liver disease guidance.',
    ],
    [
        'title' => 'Environmental Emergencies',
        'scenario' => 'Outdoor recreation incidents. Match environment to diagnosis.',
        'question' => 'Match each finding to the correct diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'Core temp 30°C, bradycardia, rigid muscles, found outdoors winter'],
            ['id' => 'l2', 'text' => 'Temp 41°C, hot dry skin, anhidrosis, marathon collapse'],
            ['id' => 'l3', 'text' => 'Diving ascent, joint pain, neuro symptoms, rash over shoulders'],
            ['id' => 'l4', 'text' => 'Headache, cherry red skin, CO detector alarm, multiple victims'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'Severe hypothermia'],
            ['id' => 'r2', 'text' => 'Heat stroke'],
            ['id' => 'r3', 'text' => 'Decompression sickness'],
            ['id' => 'r4', 'text' => 'Carbon monoxide poisoning'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'CDC environmental health guidance covers hypothermia management, heat stroke active cooling, CO poisoning with high-flow oxygen, and NIH diving medicine for decompression illness.',
    ],
    [
        'title' => 'Infectious Disease Emergencies',
        'scenario' => 'Fever and rash cases. Match presentation to likely diagnosis.',
        'question' => 'Match each finding to the correct diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'Petechial rash non-blanching, fever, neck stiffness, photophobia'],
            ['id' => 'l2', 'text' => 'Maculopapular rash palms/soles, travel history, fever, lymphadenopathy'],
            ['id' => 'l3', 'text' => 'Fever, hypotension, indwelling catheter, AMS from nursing home'],
            ['id' => 'l4', 'text' => 'Painful vesicular rash dermatomal distribution, elderly immunocompromised'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'Meningococcemia / bacterial meningitis'],
            ['id' => 'r2', 'text' => 'Rocky Mountain spotted fever (rickettsial)'],
            ['id' => 'r3', 'text' => 'Sepsis / urosepsis'],
            ['id' => 'r4', 'text' => 'Herpes zoster (shingles)'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'CDC meningitis and sepsis guidance: petechiae with fever is emergency. RMSF requires doxycycline empirically per NIH infectious disease resources. Zoster is dermatomal vesicles.',
    ],
    [
        'title' => 'Psychiatric and Behavioral',
        'scenario' => 'Behavioral emergencies with medical mimics. Match presentation to priority diagnosis.',
        'question' => 'Match each finding to the correct diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'Agitation, hyperthermia, diaphoresis, rigidity after antipsychotic use'],
            ['id' => 'l2', 'text' => 'Delusions, normal vitals, calm cooperative, requesting voluntary transport'],
            ['id' => 'l3', 'text' => 'Acute confusion, fever, UTI history, foul-smelling urine in elderly'],
            ['id' => 'l4', 'text' => 'Suicide attempt with empty acetaminophen bottles, asymptomatic now'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'Neuroleptic malignant syndrome'],
            ['id' => 'r2', 'text' => 'Primary psychiatric crisis without medical emergency'],
            ['id' => 'r3', 'text' => 'Delirium from infection (organic cause)'],
            ['id' => 'r4', 'text' => 'Acetaminophen toxicity requiring NAC evaluation'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'FDA antipsychotic labeling warns of NMS with hyperthermia and rigidity. CDC geriatric guidance: treat delirium causes first. FDA acetaminophen toxicity requires antidote within window per NIH poison center protocols.',
    ],
    [
        'title' => 'Renal and Urologic',
        'scenario' => 'Flank pain and retention cases. Match to diagnosis.',
        'question' => 'Match each finding to the correct diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'Colicky flank pain, hematuria, unable to find comfortable position'],
            ['id' => 'l2', 'text' => 'Suprapubic pain, distended bladder, unable to void 12 hours, HR 110'],
            ['id' => 'l3', 'text' => 'ESRD missed dialysis, K+ 7.0, peaked T waves, weakness'],
            ['id' => 'l4', 'text' => 'Fever, CVA tenderness, dysuria, elderly female'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'Nephrolithiasis (kidney stone)'],
            ['id' => 'r2', 'text' => 'Urinary retention'],
            ['id' => 'r3', 'text' => 'Hyperkalemia from renal failure'],
            ['id' => 'r4', 'text' => 'Pyelonephritis'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'NIH kidney stone and UTI guidance describe classic presentations. Retention causes suprapubic distension. Missed dialysis with hyperkalemia is life-threatening per CDC chronic kidney disease emergency planning.',
    ],
    [
        'title' => 'Hematologic Emergencies',
        'scenario' => 'Bleeding and clotting presentations. Match finding to diagnosis.',
        'question' => 'Match each finding to the correct diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'Warfarin use, fall, headache, vomiting, unequal pupils, BP elevated'],
            ['id' => 'l2', 'text' => 'Sickle cell pain crisis, chest pain, SpO₂ 89%, fever'],
            ['id' => 'l3', 'text' => 'Hemophilia, joint swelling after minor trauma, family history'],
            ['id' => 'l4', 'text' => 'DVT history, sudden dyspnea, tachycardia, pleuritic pain'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'Intracranial hemorrhage on anticoagulation'],
            ['id' => 'r2', 'text' => 'Acute chest syndrome'],
            ['id' => 'r3', 'text' => 'Hemophilic arthropathy / hemarthrosis'],
            ['id' => 'r4', 'text' => 'Pulmonary embolism'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'FDA warfarin labeling emphasizes bleeding risk with head injury. NIH sickle cell guidance: acute chest syndrome is emergency. Hemophilia causes hemarthrosis. PE complicates DVT per NHLBI venous thromboembolism resources.',
    ],
]);
