<?php

require_once __DIR__.'/helpers.php';

return paramedic_levels([
    [
        'title' => 'Pediatric Epinephrine IM — Anaphylaxis',
        'scenario' => '8-year-old 25 kg with anaphylaxis after peanut exposure. Protocol: epinephrine 1:1000 IM 0.01 mg/kg (max 0.3 mg).',
        'question' => 'Calculate the dose in mg.',
        'correct' => 0.25,
        'tolerance' => 0.02,
        'unit' => 'mg',
        'explanation' => '0.01 mg/kg × 25 kg = 0.25 mg IM, under pediatric max 0.3 mg. FDA epinephrine auto-injector labeling: 0.15 mg for ≤30 kg, 0.3 mg for >30 kg per CDC pediatric anaphylaxis guidance.',
    ],
    [
        'title' => 'Pediatric Defibrillation — First Shock',
        'scenario' => '4-year-old 18 kg in VF arrest. Biphasic defibrillator. Protocol: 2 J/kg first shock.',
        'question' => 'Calculate energy in joules.',
        'correct' => 36,
        'tolerance' => 0,
        'unit' => 'J',
        'explanation' => '2 J/kg × 18 kg = 36 J. AHA pediatric advanced life support and CDC resuscitation guidance use weight-based defibrillation with escalation to 4 J/kg if initial shock fails.',
    ],
    [
        'title' => 'Pediatric Fluid Bolus — Hypovolemia',
        'scenario' => '10-year-old 40 kg dehydrated from gastroenteritis with shock. Protocol: isotonic crystalloid 20 mL/kg bolus.',
        'question' => 'Calculate bolus volume in mL.',
        'correct' => 800,
        'tolerance' => 0,
        'unit' => 'mL',
        'explanation' => '20 mL/kg × 40 kg = 800 mL bolus, reassess between boluses per NIH PALS hypovolemic shock algorithm and NHTSA pediatric EMS protocols.',
    ],
    [
        'title' => 'Pediatric Dextrose — Hypoglycemia',
        'scenario' => '3-year-old 15 kg symptomatic hypoglycemia glucose 42 mg/dL. Protocol: D10W 5 mL/kg IV.',
        'question' => 'Calculate volume in mL.',
        'correct' => 75,
        'tolerance' => 0,
        'unit' => 'mL',
        'explanation' => '5 mL/kg × 15 kg = 75 mL D10W IV. NIH neonatal/pediatric hypoglycemia guidance supports weight-based dextrose with reassessment — avoid D25W in young children per CDC pediatric diabetes emergency materials.',
    ],
    [
        'title' => 'Pediatric Amiodarone — VF/pVT',
        'scenario' => '6-year-old 22 kg refractory VF. Protocol: amiodarone 5 mg/kg IV/IO first dose.',
        'question' => 'Calculate dose in mg.',
        'correct' => 110,
        'tolerance' => 2,
        'unit' => 'mg',
        'explanation' => '5 mg/kg × 22 kg = 110 mg. AHA PALS and FDA amiodarone labeling describe weight-based pediatric arrest dosing distinct from fixed adult 300 mg.',
    ],
    [
        'title' => 'Pediatric Atropine — Symptomatic Bradycardia',
        'scenario' => '2-year-old 12 kg post-intubation bradycardia HR 55 with poor perfusion. Protocol: atropine 0.02 mg/kg IV (min 0.1 mg, max child 0.5 mg).',
        'question' => 'Calculate dose in mg.',
        'correct' => 0.24,
        'tolerance' => 0.02,
        'unit' => 'mg',
        'explanation' => '0.02 mg/kg × 12 kg = 0.24 mg IV, above minimum 0.1 mg and below max 0.5 mg. AHA PALS bradycardia algorithm per NIH pediatric arrhythmia resources.',
    ],
    [
        'title' => 'Pediatric Benzo — Status Epilepticus',
        'scenario' => '5-year-old 20 kg active seizure >5 minutes. Protocol: midazolam 0.1 mg/kg IM (max 10 mg).',
        'question' => 'Calculate dose in mg.',
        'correct' => 2,
        'tolerance' => 0.1,
        'unit' => 'mg',
        'explanation' => '0.1 mg/kg × 20 kg = 2 mg IM midazolam. NIH epilepsy and CDC seizure first aid guidance support benzodiazepines for prolonged pediatric seizures per EMS protocol.',
    ],
    [
        'title' => 'Broselow — Estimated Weight Dose',
        'scenario' => 'Color zone estimates 10 kg infant in respiratory failure. Protocol: epinephrine 0.01 mg/kg IV for bradycardia (0.1 mg/mL concentration).',
        'question' => 'Calculate dose in mg.',
        'correct' => 0.1,
        'tolerance' => 0.01,
        'unit' => 'mg',
        'explanation' => '0.01 mg/kg × 10 kg = 0.1 mg IV epinephrine. NHTSA pediatric readiness and AHA PALS emphasize Broselow length-based weight estimation when scale unavailable.',
    ],
    [
        'title' => 'Pediatric Naloxone — Opioid Overdose',
        'scenario' => 'Toddler 13 kg accidental opioid ingestion, RR 6/min. Protocol: naloxone 0.1 mg/kg IV/IM (max 2 mg per dose).',
        'question' => 'Calculate dose in mg.',
        'correct' => 1.3,
        'tolerance' => 0.1,
        'unit' => 'mg',
        'explanation' => '0.1 mg/kg × 13 kg = 1.3 mg, under 2 mg max. CDC opioid overdose guidance supports weight-based naloxone in pediatrics with ventilation priority.',
    ],
    [
        'title' => 'Pediatric Ketamine — Pain/Procedural',
        'scenario' => '9-year-old 30 kg isolated femur fracture. Protocol: ketamine 1 mg/kg IV for analgesia/sedation.',
        'question' => 'Calculate dose in mg.',
        'correct' => 30,
        'tolerance' => 1,
        'unit' => 'mg',
        'explanation' => '1 mg/kg × 30 kg = 30 mg IV ketamine. FDA ketamine labeling and NIH pediatric pain management references describe weight-based dosing with airway monitoring per NHTSA EMS pharmacology.',
    ],
]);
