<?php

require_once __DIR__.'/helpers.php';

return paramedic_levels([
    [
        'title' => 'Epinephrine IM — Adult Anaphylaxis',
        'scenario' => 'Adult 70 kg in anaphylaxis. Protocol: epinephrine 1:1000 IM 0.01 mg/kg (max 0.5 mg).',
        'question' => 'Calculate the dose in mg.',
        'correct' => 0.5,
        'tolerance' => 0.05,
        'unit' => 'mg',
        'explanation' => '0.01 mg/kg × 70 kg = 0.7 mg, capped at 0.5 mg maximum per FDA epinephrine auto-injector and most EMS protocols for adult anaphylaxis.',
    ],
    [
        'title' => 'Pediatric Epinephrine IM — Anaphylaxis',
        'scenario' => 'Child 15 kg with anaphylaxis. Protocol: epinephrine 1:1000 IM 0.01 mg/kg (max 0.3 mg pediatric).',
        'question' => 'Calculate the dose in mg.',
        'correct' => 0.15,
        'tolerance' => 0.02,
        'unit' => 'mg',
        'explanation' => '0.01 mg/kg × 15 kg = 0.15 mg IM. FDA pediatric auto-injector delivers 0.15 mg for children ≤30 kg per labeling.',
    ],
    [
        'title' => 'Amiodarone — Cardiac Arrest VF/pVT',
        'scenario' => 'Refractory VF during arrest. Protocol: amiodarone 300 mg IV/IO first dose (fixed dose, not weight-based).',
        'question' => 'Calculate the first dose in mg.',
        'correct' => 300,
        'tolerance' => 0,
        'unit' => 'mg',
        'explanation' => 'AHA ACLS recommends amiodarone 300 mg IV/IO as first dose in refractory VF/pVT. FDA amiodarone prescribing information supports this ACLS dosing for life-threatening arrhythmias.',
    ],
    [
        'title' => 'D10W for Neonatal Hypoglycemia',
        'scenario' => 'Newborn 3.2 kg, symptomatic hypoglycemia. Protocol: D10W 2 mL/kg IV. Calculate total volume in mL.',
        'question' => 'Calculate the volume in mL.',
        'correct' => 6.4,
        'tolerance' => 0.2,
        'unit' => 'mL',
        'explanation' => '2 mL/kg × 3.2 kg = 6.4 mL D10W. NIH neonatal hypoglycemia guidance supports weight-based dextrose boluses with reassessment.',
    ],
    [
        'title' => 'Lidocaine — Stable VT (Protocol)',
        'scenario' => 'Stable monomorphic VT. Protocol: lidocaine 1.5 mg/kg IV. Patient weight 80 kg.',
        'question' => 'Calculate the dose in mg.',
        'correct' => 120,
        'tolerance' => 1,
        'unit' => 'mg',
        'explanation' => '1.5 mg/kg × 80 kg = 120 mg IV. FDA lidocaine labeling and AHA alternative antiarrhythmic pathways describe weight-based loading for ventricular arrhythmias when amiodarone unavailable.',
    ],
    [
        'title' => 'Fentanyl — Pain Management',
        'scenario' => 'Isolated extremity fracture. Protocol: fentanyl 1 mcg/kg IV. Patient 90 kg.',
        'question' => 'Calculate the dose in mcg.',
        'correct' => 90,
        'tolerance' => 2,
        'unit' => 'mcg',
        'explanation' => '1 mcg/kg × 90 kg = 90 mcg IV fentanyl. FDA opioid labeling emphasizes weight-based titration with monitoring for respiratory depression per CDC opioid safety guidance.',
    ],
    [
        'title' => 'Magnesium Sulfate — Torsades',
        'scenario' => 'Torsades de pointes. Protocol: magnesium sulfate 2 g IV over 10 minutes (fixed dose).',
        'question' => 'Calculate the dose in g.',
        'correct' => 2,
        'tolerance' => 0,
        'unit' => 'g',
        'explanation' => 'AHA ACLS and FDA magnesium sulfate labeling recommend 2 g IV for torsades de pointes associated with QT prolongation per NIH NHLBI long QT guidance.',
    ],
    [
        'title' => 'Pediatric Defibrillation — Biphasic',
        'scenario' => 'Pediatric arrest 20 kg with biphasic defibrillator. Protocol: 2 J/kg first shock.',
        'question' => 'Calculate energy in joules.',
        'correct' => 40,
        'tolerance' => 0,
        'unit' => 'J',
        'explanation' => '2 J/kg × 20 kg = 40 J first biphasic shock. AHA pediatric advanced life support and CDC resuscitation guidance use weight-based defibrillation energy.',
    ],
    [
        'title' => 'Calcium Chloride — Hyperkalemia',
        'scenario' => 'Hyperkalemia with widened QRS. Protocol: calcium chloride 10% 10 mg/kg IV (max 1 g). Patient 85 kg.',
        'question' => 'Calculate the dose in mg (apply maximum if exceeded).',
        'correct' => 1000,
        'tolerance' => 0,
        'unit' => 'mg',
        'explanation' => '10 mg/kg × 85 kg = 850 mg, under 1 g max. If calculation exceeded 1000 mg, cap at 1 g. NIH electrolyte emergency guidance uses calcium to stabilize myocardium in hyperkalemia.',
    ],
    [
        'title' => 'Ketamine — Procedural Sedation RSI',
        'scenario' => 'RSI induction. Protocol: ketamine 2 mg/kg IV. Patient 75 kg.',
        'question' => 'Calculate the dose in mg.',
        'correct' => 150,
        'tolerance' => 2,
        'unit' => 'mg',
        'explanation' => '2 mg/kg × 75 kg = 150 mg IV ketamine. FDA ketamine labeling describes weight-based induction dosing; NHTSA EMS pharmacology references support ketamine for hemodynamically stable RSI.',
    ],
]);
