<?php

require_once __DIR__.'/helpers.php';

return paramedic_levels([
    [
        'title' => 'STEMI Patterns on 12-Lead',
        'scenario' => 'Multiple chest pain patients after a community health fair. Match each 12-lead finding to the correct diagnosis.',
        'question' => 'Match each finding to the rhythm or diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'ST elevation ≥2 mm in V2–V4 with reciprocal inferior ST depression'],
            ['id' => 'l2', 'text' => 'ST elevation II, III, aVF with ST elevation V4R and hypotension, clear lungs'],
            ['id' => 'l3', 'text' => 'New LBBB with chest pain; modified Sgarbossa criteria positive'],
            ['id' => 'l4', 'text' => 'Diffuse ST elevation with PR depression; no reciprocal pattern'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'Anterior STEMI'],
            ['id' => 'r2', 'text' => 'Inferior STEMI with RV involvement'],
            ['id' => 'r3', 'text' => 'STEMI equivalent'],
            ['id' => 'r4', 'text' => 'Pericarditis'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'NIH NHLBI STEMI criteria define contiguous ST elevation thresholds. RV infarct shows V4R elevation with hypotension and JVD. New LBBB with positive Sgarbossa may be STEMI equivalent. Diffuse ST elevation with PR depression suggests pericarditis.',
    ],
    [
        'title' => 'AV Blocks and Conduction',
        'scenario' => 'Elderly patients with syncope and dizziness. Match ECG patterns to the correct diagnosis.',
        'question' => 'Match each finding to the rhythm or diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'PR interval >200 ms, every P wave conducted'],
            ['id' => 'l2', 'text' => 'Progressive PR prolongation until dropped QRS'],
            ['id' => 'l3', 'text' => 'Fixed PR with sudden dropped QRS; wide QRS 0.14 sec'],
            ['id' => 'l4', 'text' => 'P waves 80/min, QRS 40/min, no P–QRS relationship'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'First-degree AV block'],
            ['id' => 'r2', 'text' => 'Mobitz type I (Wenckebach)'],
            ['id' => 'r3', 'text' => 'Mobitz type II'],
            ['id' => 'r4', 'text' => 'Third-degree (complete) AV block'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'NIH NHLBI arrhythmia resources describe progressive PR prolongation in Wenckebach, fixed PR with dropped beats in Mobitz II, and complete AV dissociation in third-degree block — each with different pacing urgency.',
    ],
    [
        'title' => 'Wide-Complex Tachycardias',
        'scenario' => 'Hemodynamically diverse tachycardia presentations. Match monitor findings to diagnosis.',
        'question' => 'Match each finding to the rhythm or diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'Regular wide QRS 160/min, BP 74/40, history of CAD'],
            ['id' => 'l2', 'text' => 'Irregular wide QRS, no P waves, rate ~110/min'],
            ['id' => 'l3', 'text' => 'Twisting QRS around baseline, QT prolonged, self-terminating'],
            ['id' => 'l4', 'text' => 'Regular narrow QRS 220/min, BP 118/70, sudden onset'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'Monomorphic ventricular tachycardia'],
            ['id' => 'r2', 'text' => 'Atrial fibrillation with aberrancy'],
            ['id' => 'r3', 'text' => 'Torsades de pointes'],
            ['id' => 'r4', 'text' => 'Supraventricular tachycardia'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'NIH NHLBI wide-complex tachycardia guidance treats unstable wide regular VT as VT until proven otherwise. AF with aberrancy is irregularly irregular. Torsades occurs with QT prolongation. Narrow regular tachycardia suggests SVT.',
    ],
    [
        'title' => 'Cardiac Arrest Rhythms',
        'scenario' => 'Post-collapse monitor strips during resuscitation. Match each finding to the correct rhythm.',
        'question' => 'Match each finding to the rhythm or diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'Chaotic irregular waveform, no pulse'],
            ['id' => 'l2', 'text' => 'Organized QRS 40/min, no pulse, EtCO₂ 12'],
            ['id' => 'l3', 'text' => 'Flat line confirmed in two leads, no pulse'],
            ['id' => 'l4', 'text' => 'Coarse ventricular activity, no pulse'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'Ventricular fibrillation'],
            ['id' => 'r2', 'text' => 'Pulseless electrical activity'],
            ['id' => 'r3', 'text' => 'Asystole'],
            ['id' => 'r4', 'text' => 'Pulseless ventricular tachycardia'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'AHA ACLS and NIH NHLBI define shockable rhythms (VF/pulseless VT) versus non-shockable (PEA/asystole). PEA shows organized activity without perfusion — treat reversible causes per H\'s and T\'s.',
    ],
    [
        'title' => 'Rate and Rhythm Identification',
        'scenario' => 'Telemetry strips from the ED holding area. Match findings to the most likely rhythm.',
        'question' => 'Match each finding to the rhythm or diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'Irregularly irregular, no P waves, ventricular rate ~100/min (10 QRS in 6 sec)'],
            ['id' => 'l2', 'text' => 'Sawtooth flutter waves, regular QRS 150/min'],
            ['id' => 'l3', 'text' => 'P before every QRS, rate 72, normal intervals'],
            ['id' => 'l4', 'text' => 'Narrow QRS 180/min, P waves hidden, regular'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'Atrial fibrillation'],
            ['id' => 'r2', 'text' => 'Atrial flutter with 2:1 block'],
            ['id' => 'r3', 'text' => 'Normal sinus rhythm'],
            ['id' => 'r4', 'text' => 'Supraventricular tachycardia'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'NIH NHLBI ECG interpretation: 6-second method estimates rate. AF lacks P waves with irregular R–R. Flutter shows sawtooth atrial activity. NSR has normal P–QRS relationship. Regular narrow tachycardia suggests SVT.',
    ],
    [
        'title' => 'Electrolyte and Drug Effects',
        'scenario' => 'Renal and toxicology patients with ECG changes. Match findings to diagnosis.',
        'question' => 'Match each finding to the rhythm or diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'Peaked T waves, widened QRS, K+ 7.2 mEq/L'],
            ['id' => 'l2', 'text' => 'QT prolongation, U waves, K+ 2.8 mEq/L'],
            ['id' => 'l3', 'text' => 'Sinus tachycardia with QRS widening in tricyclic overdose'],
            ['id' => 'l4', 'text' => 'Junctional rhythm 52/min after digoxin toxicity'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'Hyperkalemia'],
            ['id' => 'r2', 'text' => 'Hypokalemia'],
            ['id' => 'r3', 'text' => 'Sodium channel blocker toxicity'],
            ['id' => 'r4', 'text' => 'Digoxin toxicity'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'NIH MedlinePlus electrolyte guidance: hyperkalemia progresses to wide QRS and sine wave; hypokalemia prolongs QT with U waves. Tricyclics widen QRS. Digoxin causes bradyarrhythmias and junctional rhythms per FDA labeling.',
    ],
    [
        'title' => 'Bundle Branch and Fascicular Blocks',
        'scenario' => 'Incidental and symptomatic conduction abnormalities on 12-lead. Match to diagnosis.',
        'question' => 'Match each finding to the rhythm or diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'QRS ≥120 ms, RSR\' in V1, wide S in lateral leads'],
            ['id' => 'l2', 'text' => 'QRS ≥120 ms, broad R in V5–V6, QS in V1'],
            ['id' => 'l3', 'text' => 'Left axis deviation, rS in II/III/aVF, qR in aVL'],
            ['id' => 'l4', 'text' => 'Right axis deviation, qR in III/aVF, rS in I/aVL'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'Right bundle branch block'],
            ['id' => 'r2', 'text' => 'Left bundle branch block'],
            ['id' => 'r3', 'text' => 'Left anterior fascicular block'],
            ['id' => 'r4', 'text' => 'Left posterior fascicular block'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'NIH NHLBI ECG conduction resources describe RBBB pattern in V1 (RSR\') and LBBB with dominant R in lateral leads. Fascicular blocks shift axis — LAFB causes left axis, LPFB causes right axis deviation.',
    ],
    [
        'title' => 'Paced and Artifact Patterns',
        'scenario' => 'Post-cardiac surgery and monitor artifact cases. Match findings to the correct interpretation.',
        'question' => 'Match each finding to the rhythm or diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'Spike before each QRS, wide QRS, rate 70/min, patient has pacemaker'],
            ['id' => 'l2', 'text' => 'Spikes without capture; native QRS 38/min, symptomatic'],
            ['id' => 'l3', 'text' => 'Regular wide complexes identical to prior VT; patient alert eating lunch'],
            ['id' => 'l4', 'text' => 'Organized rhythm on monitor; no pulse; EtCO₂ flat during BVM'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'Ventricular pacing with capture'],
            ['id' => 'r2', 'text' => 'Pacemaker failure — bradycardia'],
            ['id' => 'r3', 'text' => 'Lead artifact mimicking VT'],
            ['id' => 'r4', 'text' => 'Esophageal intubation or circuit disconnect'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'NIH device and ECG guidance: paced rhythms show capture spikes. Failure to capture causes symptomatic bradycardia. Artifact may mimic VT when patient is stable. Flat capnography with organized rhythm suggests esophageal placement.',
    ],
    [
        'title' => 'Ischemia Without Classic STEMI',
        'scenario' => 'Chest pain patients with ST changes not meeting classic STEMI criteria. Match to diagnosis.',
        'question' => 'Match each finding to the rhythm or diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'ST depression ≥1 mm in V4–V6 with T-wave inversion, troponin pending'],
            ['id' => 'l2', 'text' => 'ST elevation aVR with diffuse ST depression elsewhere'],
            ['id' => 'l3', 'text' => 'Hyperacute T waves V2–V3 without ST elevation yet'],
            ['id' => 'l4', 'text' => 'ST elevation V1–V3 in young athlete, J-point elevation only'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'NSTEMI / ischemia'],
            ['id' => 'r2', 'text' => 'Left main or severe multivessel ischemia'],
            ['id' => 'r3', 'text' => 'Early anterior STEMI (hyperacute T)'],
            ['id' => 'r4', 'text' => 'Benign early repolarization'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'NIH NHLBI ACS guidance: ST depression indicates ischemia. ST elevation in aVR with diffuse depression suggests left main disease. Hyperacute T waves precede ST elevation. J-point elevation in young athletes may be benign.',
    ],
    [
        'title' => 'Pediatric and SVT Nuances',
        'scenario' => 'Mixed-age tachycardia cases. Match findings to the correct rhythm.',
        'question' => 'Match each finding to the rhythm or diagnosis.',
        'left' => [
            ['id' => 'l1', 'text' => 'Infant 220/min, narrow QRS, no P waves visible, fussy then lethargic'],
            ['id' => 'l2', 'text' => 'Child 180/min, narrow QRS, P before each QRS, fever 39.5°C'],
            ['id' => 'l3', 'text' => 'Adolescent 200/min, narrow regular, vagal maneuver unsuccessful'],
            ['id' => 'l4', 'text' => 'Teen 160/min after cocaine use, wide QRS, BP 80/50'],
        ],
        'right' => [
            ['id' => 'r1', 'text' => 'Pediatric supraventricular tachycardia'],
            ['id' => 'r2', 'text' => 'Sinus tachycardia'],
            ['id' => 'r3', 'text' => 'Adolescent SVT requiring adenosine per protocol'],
            ['id' => 'r4', 'text' => 'Wide-complex tachycardia — treat as VT until proven otherwise'],
        ],
        'correct' => ['l1' => 'r1', 'l2' => 'r2', 'l3' => 'r3', 'l4' => 'r4'],
        'explanation' => 'NIH NHLBI pediatric arrhythmia guidance: infant narrow regular tachycardia without fever suggests SVT. Sinus tach has visible P waves with fever. Adolescent SVT may need adenosine. Wide complex with shock — treat as VT per AHA.',
    ],
]);
