<?php

require_once __DIR__.'/helpers.php';

return paramedic_levels([
    [
        'title' => 'Septic Shock Recognition',
        'scenario' => '89-year-old from SNF: fever 39.6°C, altered mental status, BP 88/50 after 500 mL fluid, HR 118, lactate 4.2 mmol/L (if available).',
        'question' => 'Select all findings consistent with septic shock.',
        'options' => [
            'fever' => 'Temperature 39.6°C',
            'hypotension' => 'BP 88/50 persisting after fluid resuscitation',
            'tachycardia' => 'Heart rate 118/min',
            'bradycardia' => 'Heart rate 52/min',
            'altered' => 'Altered mental status',
            'hypertension' => 'BP 168/96',
        ],
        'correct' => ['fever', 'hypotension', 'tachycardia', 'altered'],
        'explanation' => 'CDC sepsis guidance defines septic shock as sepsis with persistent hypotension requiring vasopressors or lactate >2 despite fluids. Fever, tachycardia, hypotension, and AMS are consistent findings per NIH sepsis resources.',
    ],
    [
        'title' => 'Cardiogenic Shock — Post-MI',
        'scenario' => 'Anterior STEMI patient: BP 82/48, cool extremities, bibasilar crackles, HR 102, SpO₂ 91%.',
        'question' => 'Select all findings consistent with cardiogenic shock.',
        'options' => [
            'hypotension' => 'Systolic BP 82 mmHg',
            'crackles' => 'Pulmonary edema on auscultation',
            'warm_flushed' => 'Warm flushed skin with bounding pulses',
            'tachycardia' => 'Compensatory tachycardia 102/min',
            'clear_lungs' => 'Clear lung fields bilaterally',
            'jvd' => 'Elevated JVD with pulmonary edema',
        ],
        'correct' => ['hypotension', 'crackles', 'tachycardia', 'jvd'],
        'explanation' => 'NIH NHLBI cardiogenic shock criteria include hypotension with signs of hypoperfusion and pulmonary congestion. Warm flushed skin suggests distributive not cardiogenic shock per AHA heart failure guidance.',
    ],
    [
        'title' => 'Hypovolemic Shock — Trauma',
        'scenario' => 'GSW abdomen: pale, diaphoretic, BP 74/40, HR 132, delayed cap refill, abdomen rigid.',
        'question' => 'Select all findings consistent with hypovolemic shock.',
        'options' => [
            'tachycardia' => 'Heart rate 132/min',
            'hypotension' => 'BP 74/40',
            'delayed_cap' => 'Delayed capillary refill >3 seconds',
            'hypertension' => 'BP 180/100',
            'bradycardia' => 'Heart rate 48/min in early shock only',
            'warm_skin' => 'Warm dry skin',
        ],
        'correct' => ['tachycardia', 'hypotension', 'delayed_cap'],
        'explanation' => 'CDC trauma and NIH shock guidance: hypovolemic shock presents with tachycardia, hypotension, and poor perfusion. Bradycardia in trauma suggests pre-arrest; warm skin suggests distributive shock.',
    ],
    [
        'title' => 'Neurogenic Shock — Spinal Injury',
        'scenario' => 'Cervical spine injury: BP 82/50, HR 52, warm dry skin below injury, paralysis.',
        'question' => 'Select all findings consistent with neurogenic shock.',
        'options' => [
            'bradycardia' => 'Heart rate 52/min',
            'hypotension' => 'BP 82/50',
            'warm_skin' => 'Warm dry skin (loss of sympathetic tone)',
            'tachycardia' => 'Heart rate 130/min',
            'diaphoresis' => 'Cool clammy diaphoresis',
            'spinal' => 'Spinal cord injury with motor loss',
        ],
        'correct' => ['bradycardia', 'hypotension', 'warm_skin', 'spinal'],
        'explanation' => 'NIH spinal cord injury resources describe neurogenic shock as hypotension with bradycardia and warm skin due to loss of sympathetic vasoconstriction — distinct from hypovolemic shock per NHTSA trauma protocols.',
    ],
    [
        'title' => 'Anaphylactic Shock',
        'scenario' => 'Bee sting: urticaria, stridor, BP 78/42, HR 140, angioedema, wheezing.',
        'question' => 'Select all findings consistent with anaphylactic shock.',
        'options' => [
            'urticaria' => 'Generalized hives',
            'hypotension' => 'BP 78/42 after epinephrine IM',
            'stridor' => 'Upper airway stridor',
            'bradycardia' => 'HR 48/min',
            'angioedema' => 'Lip and tongue swelling',
            'isolated_rash' => 'Rash only without other organ involvement',
        ],
        'correct' => ['urticaria', 'hypotension', 'stridor', 'angioedema'],
        'explanation' => 'FDA and CDC anaphylaxis criteria require multisystem involvement (skin, respiratory, cardiovascular). Hypotension defines anaphylactic shock. Isolated rash without other criteria is not anaphylaxis.',
    ],
    [
        'title' => 'Obstructive Shock — Tension Pneumothorax',
        'scenario' => 'Ventilated trauma patient deteriorates: BP 70/40, JVD, tracheal deviation, absent breath sounds left, EtCO₂ drop.',
        'question' => 'Select all findings consistent with obstructive shock from tension pneumothorax.',
        'options' => [
            'jvd' => 'Distended neck veins',
            'hypotension' => 'BP 70/40',
            'absent_breath' => 'Unilateral absent breath sounds',
            'deviation' => 'Tracheal deviation away from affected side',
            'clear_lungs' => 'Equal breath sounds bilaterally',
            'bradycardia_late' => 'Late bradycardia suggesting pre-arrest',
        ],
        'correct' => ['jvd', 'hypotension', 'absent_breath', 'deviation'],
        'explanation' => 'NIH and CDC trauma guidance: tension pneumothorax causes obstructive shock with JVD, hypotension, unilateral absent sounds, and tracheal deviation — treated with immediate needle decompression per NHTSA trauma protocols.',
    ],
    [
        'title' => 'Distributive Shock — Sepsis vs Anaphylaxis',
        'scenario' => 'Patient with infection source, fever, warm flushed skin early, BP 92/58, HR 118, bounding pulses initially.',
        'question' => 'Select all findings suggesting early distributive (warm) shock physiology.',
        'options' => [
            'warm_skin' => 'Warm flushed extremities',
            'fever' => 'Core temperature 39.2°C',
            'bounding' => 'Bounding peripheral pulses early in sepsis',
            'cool_clammy' => 'Cool clammy skin',
            'tachycardia' => 'Heart rate 118/min',
            'narrow_pulse' => 'Weak thready pulses only',
        ],
        'correct' => ['warm_skin', 'fever', 'bounding', 'tachycardia'],
        'explanation' => 'CDC sepsis education notes early sepsis may present with warm shock and bounding pulses before progression to cold hypoperfusion. Cool clammy skin suggests late or hypovolemic shock per NIH critical care guidance.',
    ],
    [
        'title' => 'Hemorrhagic Shock Classification',
        'scenario' => 'Penetrating trauma: HR 128, BP 88/60, anxious, estimated blood loss 30% class III.',
        'question' => 'Select all findings consistent with Class III hemorrhagic shock.',
        'options' => [
            'tachycardia' => 'HR >120/min',
            'hypotension' => 'Systolic BP 88 mmHg',
            'altered' => 'Anxiety progressing to altered mental status',
            'normal_bp' => 'BP 120/80',
            'blood_loss' => 'Estimated 30% blood volume loss',
            'bradycardia' => 'HR 55/min without beta-blockade',
        ],
        'correct' => ['tachycardia', 'hypotension', 'altered', 'blood_loss'],
        'explanation' => 'NIH ATLS hemorrhagic shock classification: Class III involves 30–40% blood loss with tachycardia, hypotension, and mental status changes. CDC Stop the Bleed emphasizes early recognition and hemorrhage control.',
    ],
    [
        'title' => 'Mixed Shock — Trauma Triad',
        'scenario' => 'Long extrication: temp 34.5°C, pH 7.22, BP 80/50, ongoing bleeding from pelvis fracture.',
        'question' => 'Select all components of the trauma triad of death.',
        'options' => [
            'hypothermia' => 'Core temperature 34.5°C',
            'acidosis' => 'Metabolic acidosis pH 7.22',
            'coagulopathy' => 'Coagulopathy from dilution and hypothermia',
            'hypertension' => 'Systolic BP 180 mmHg',
            'bradycardia' => 'Isolated bradycardia without hypothermia',
            'hyperglycemia' => 'Blood glucose 280 mg/dL alone',
        ],
        'correct' => ['hypothermia', 'acidosis', 'coagulopathy'],
        'explanation' => 'NIH trauma research defines the lethal triad: hypothermia, acidosis, and coagulopathy perpetuate hemorrhage. CDC trauma systems emphasize preventing hypothermia and rapid hemorrhage control.',
    ],
    [
        'title' => 'Vasopressor-Responsive Shock',
        'scenario' => 'Post-fluid sepsis: BP 86/52, MAP 63, lactate 3.8, starting norepinephrine infusion. Reassess perfusion.',
        'question' => 'Select all targets indicating improving perfusion per sepsis bundles.',
        'options' => [
            'map_65' => 'MAP ≥65 mmHg',
            'improved_mental' => 'Improved mental status',
            'urine_output' => 'Urine output improving (if Foley present)',
            'rising_lactate' => 'Lactate continuing to rise',
            'warm_periphery' => 'Improving capillary refill and warm extremities',
            'persistent_oliguria' => 'Urine output <0.5 mL/kg/hr despite MAP goal',
        ],
        'correct' => ['map_65', 'improved_mental', 'urine_output', 'warm_periphery'],
        'explanation' => 'CDC sepsis hour-1 bundle and NIH Surviving Sepsis guidelines target MAP ≥65 and perfusion improvement. Rising lactate and persistent oliguria suggest ongoing shock despite partial BP correction.',
    ],
]);
