<?php

return [
    'scenarios' => [
        [
            'title' => 'STEMI with Cardiogenic Shock',
            'scenario' => '58-year-old male, crushing chest pain 45 minutes, diaphoretic, pale. 12-lead shows anterior STEMI.',
            'detail' => 'Dispatch: chest pain, priority 1. Partner established IV while you acquired 12-lead. Aspirin given per protocol. 18-minute transport to PCI center.',
            'sentences' => [
                ['id' => 's1', 'text' => 'Patient reports substernal pressure radiating to left arm since mowing lawn.', 'section' => 'S'],
                ['id' => 's2', 'text' => 'Denies prior similar pain; history of hypertension and hyperlipidemia.', 'section' => 'S'],
                ['id' => 'o1', 'text' => 'Alert, pale, diaphoretic; lungs with bibasilar crackles.', 'section' => 'O'],
                ['id' => 'o2', 'text' => '12-lead: ST elevation V2–V5; BP 86/52, HR 102, SpO₂ 91% on 4 L.', 'section' => 'O'],
                ['id' => 'a1', 'text' => 'Anterior STEMI with cardiogenic shock physiology.', 'section' => 'A'],
                ['id' => 'p1', 'text' => 'STEMI alert, cautious fluids, norepinephrine per protocol, emergent PCI transport.', 'section' => 'P'],
                ['id' => 'x1', 'text' => 'Patient complained about hospital food on last admission three years ago.', 'section' => 'X'],
                ['id' => 'x2', 'text' => 'Crew discussed playoff game during transport.', 'section' => 'X'],
            ],
        ],
        [
            'title' => 'Post-Intubation ROSC',
            'scenario' => 'Witnessed VF arrest, ROSC after 3 shocks and epinephrine. Now intubated, EtCO₂ 38, MAP 55.',
            'detail' => 'Bystander CPR in progress on arrival. Family present; wife provided medical history.',
            'sentences' => [
                ['id' => 's1', 'text' => 'Wife reports sudden collapse while watching television; no chest pain beforehand.', 'section' => 'S'],
                ['id' => 's2', 'text' => 'Known CAD with stent 2019; takes metoprolol and aspirin.', 'section' => 'S'],
                ['id' => 'o1', 'text' => 'Post-ROSC: GCS 6, pupils 3 mm reactive, EtCO₂ 38, SpO₂ 96% on vent.', 'section' => 'O'],
                ['id' => 'o2', 'text' => 'BP 92/48 after push-dose pressor; 12-lead sinus tach, no STEMI.', 'section' => 'O'],
                ['id' => 'a1', 'text' => 'Return of spontaneous circulation after VF arrest; post-intubation hypotension.', 'section' => 'A'],
                ['id' => 'p1', 'text' => 'Avoid hyperventilation, maintain MAP, norepinephrine infusion, hypothermia-capable center.', 'section' => 'P'],
                ['id' => 'x1', 'text' => 'Living room TV was tuned to a cooking channel.', 'section' => 'X'],
                ['id' => 'x2', 'text' => 'Neighbor brought coffee for crew.', 'section' => 'X'],
            ],
        ],
        [
            'title' => 'Severe Sepsis — Nursing Home',
            'scenario' => '89-year-old from SNF: fever, altered, hypotensive. Suspected urosepsis.',
            'detail' => 'Facility nurse reported UTI treatment started yesterday. DNR status not present; full code.',
            'sentences' => [
                ['id' => 's1', 'text' => 'Staff report increasing confusion and decreased oral intake over 24 hours.', 'section' => 'S'],
                ['id' => 's2', 'text' => 'History dementia, diabetes, indwelling catheter.', 'section' => 'S'],
                ['id' => 'o1', 'text' => 'Febrile 39.6°C, dry mucous membranes, mottled knees.', 'section' => 'O'],
                ['id' => 'o2', 'text' => 'BP 88/50, HR 118, RR 26, SpO₂ 93% on NRB.', 'section' => 'O'],
                ['id' => 'a1', 'text' => 'Severe sepsis with hypoperfusion.', 'section' => 'A'],
                ['id' => 'p1', 'text' => 'Sepsis alert, 500 mL crystalloid bolus, repeat vitals, broad-spectrum abx at ED.', 'section' => 'P'],
                ['id' => 'x1', 'text' => 'SNF hallway carpet was blue.', 'section' => 'X'],
                ['id' => 'x2', 'text' => 'Patient favorite bingo night is Tuesday.', 'section' => 'X'],
            ],
        ],
        [
            'title' => 'Pediatric Anaphylaxis',
            'scenario' => '7-year-old school lunch peanut exposure: stridor, urticaria, BP 72/40.',
            'detail' => 'School nurse administered epinephrine auto-injector 5 minutes before EMS arrival.',
            'sentences' => [
                ['id' => 's1', 'text' => 'Teacher reports student ate classmate\'s peanut butter sandwich.', 'section' => 'S'],
                ['id' => 's2', 'text' => 'Known peanut allergy; has EpiPen at school.', 'section' => 'S'],
                ['id' => 'o1', 'text' => 'Stridor, wheezes, generalized urticaria, angioedema lips.', 'section' => 'O'],
                ['id' => 'o2', 'text' => 'BP 72/40, HR 132, SpO₂ 91%; improved hives after first epi, stridor persists.', 'section' => 'O'],
                ['id' => 'a1', 'text' => 'Anaphylaxis with persistent airway compromise and shock.', 'section' => 'A'],
                ['id' => 'p1', 'text' => 'Repeat IM epinephrine, IV fluids, albuterol, rapid transport, observe for biphasic reaction.', 'section' => 'P'],
                ['id' => 'x1', 'text' => 'Cafeteria served pizza yesterday.', 'section' => 'X'],
                ['id' => 'x2', 'text' => 'Child likes video games.', 'section' => 'X'],
            ],
        ],
        [
            'title' => 'Traumatic Brain Injury — MVC',
            'scenario' => 'Unrestrained driver, positive LOC, GCS 10, lateralizing left, pupil 5 mm right.',
            'detail' => 'Extrication 8 minutes. C-spine immobilized. Mechanism: high-speed frontal impact.',
            'sentences' => [
                ['id' => 's1', 'text' => 'Bystander reports driver struck steering wheel; brief LOC.', 'section' => 'S'],
                ['id' => 's2', 'text' => 'Patient confused, repeats questions; denies alcohol use.', 'section' => 'S'],
                ['id' => 'o1', 'text' => 'GCS 10 (E3V3M4), right pupil 5 mm sluggish, left hemiparesis.', 'section' => 'O'],
                ['id' => 'o2', 'text' => 'BP 158/92, HR 54, SpO₂ 96% on high-flow; scalp hematoma.', 'section' => 'O'],
                ['id' => 'a1', 'text' => 'Moderate TBI with unilateral pupillary change — herniation concern.', 'section' => 'A'],
                ['id' => 'p1', 'text' => 'Prevent hypoxia/hypotension, head elevation 30°, Level I trauma alert, 12-minute ETA.', 'section' => 'P'],
                ['id' => 'x1', 'text' => 'Vehicle was blue sedan.', 'section' => 'X'],
                ['id' => 'x2', 'text' => 'Traffic delayed by construction unrelated to crash.', 'section' => 'X'],
            ],
        ],
        [
            'title' => 'Obstetric Emergency — Eclampsia',
            'scenario' => '32-year-old 36 weeks pregnant postictal after generalized seizure. BP 182/110.',
            'detail' => 'Husband on scene. Prenatal care at community clinic; no magnesium given prior.',
            'sentences' => [
                ['id' => 's1', 'text' => 'Husband reports headache and visual changes today then witnessed seizure.', 'section' => 'S'],
                ['id' => 's2', 'text' => 'G1P0, no prior eclampsia; missed appointment last week.', 'section' => 'S'],
                ['id' => 'o1', 'text' => 'Postictal, left lateral position, 3+ pitting edema lower extremities.', 'section' => 'O'],
                ['id' => 'o2', 'text' => 'BP 182/110, HR 108, SpO₂ 97%; fetal heart tones 148.', 'section' => 'O'],
                ['id' => 'a1', 'text' => 'Eclampsia with severe preeclampsia features.', 'section' => 'A'],
                ['id' => 'p1', 'text' => 'Magnesium sulfate per protocol, BP control per protocol, OB emergency transport.', 'section' => 'P'],
                ['id' => 'x1', 'text' => 'Couple planning baby name discussion.', 'section' => 'X'],
                ['id' => 'x2', 'text' => 'Apartment painted beige.', 'section' => 'X'],
            ],
        ],
        [
            'title' => 'Airway Burn — Inhalation Injury',
            'scenario' => 'House fire victim: hoarseness, singed nasal hairs, CO exposure suspected.',
            'detail' => 'Fire department removed patient from structure. SpO₂ 88% on scene air.',
            'sentences' => [
                ['id' => 's1', 'text' => 'Patient reports being trapped in bedroom smoke for several minutes.', 'section' => 'S'],
                ['id' => 's2', 'text' => 'Complains of throat pain and hoarse voice; no known medical history.', 'section' => 'S'],
                ['id' => 'o1', 'text' => 'Facial partial-thickness burns, soot in nares, stridor at rest.', 'section' => 'O'],
                ['id' => 'o2', 'text' => 'RR 30, SpO₂ 90% on NRB; carboxyhemoglobin not available.', 'section' => 'O'],
                ['id' => 'a1', 'text' => 'Inhalation injury with airway edema risk and suspected CO toxicity.', 'section' => 'A'],
                ['id' => 'p1', 'text' => 'High-flow oxygen, early RSI consideration, burn center/trauma alert.', 'section' => 'P'],
                ['id' => 'x1', 'text' => 'House number is 1427.', 'section' => 'X'],
                ['id' => 'x2', 'text' => 'Neighbor cat escaped during fire.', 'section' => 'X'],
            ],
        ],
        [
            'title' => 'Hyperkalemia — Dialysis Patient',
            'scenario' => 'ESRD patient missed dialysis: weakness, peaked T waves on monitor.',
            'detail' => 'Family reports nausea and skipped last two sessions. AV fistula arm present.',
            'sentences' => [
                ['id' => 's1', 'text' => 'Patient reports progressive weakness and palpitations over two days.', 'section' => 'S'],
                ['id' => 's2', 'text' => 'ESRD on hemodialysis TThS; last session 5 days ago.', 'section' => 'S'],
                ['id' => 'o1', 'text' => 'Muscle weakness, prolonged PR and peaked T waves on 4-lead.', 'section' => 'O'],
                ['id' => 'o2', 'text' => 'K+ 7.1 mEq/L on i-STAT; BP 102/64, HR 52.', 'section' => 'O'],
                ['id' => 'a1', 'text' => 'Life-threatening hyperkalemia with bradycardia.', 'section' => 'A'],
                ['id' => 'p1', 'text' => 'Calcium chloride, albuterol, insulin-dextrose per protocol, emergent dialysis-capable ED.', 'section' => 'P'],
                ['id' => 'x1', 'text' => 'Patient watches dialysis unit TV game shows.', 'section' => 'X'],
                ['id' => 'x2', 'text' => 'Fistula placed 2018.', 'section' => 'X'],
            ],
        ],
        [
            'title' => 'Psychiatric Emergency — Excited Delirium',
            'scenario' => 'Agitated male TASERed by law enforcement: hyperthermia, combative, diaphoresis.',
            'detail' => 'Police on scene; scene secured. Unknown drug use reported by officers.',
            'sentences' => [
                ['id' => 's1', 'text' => 'Officers report bizarre behavior, stripping clothes, smashing window.', 'section' => 'S'],
                ['id' => 's2', 'text' => 'Unknown substance use; history unknown.', 'section' => 'S'],
                ['id' => 'o1', 'text' => 'Combative, diaphoretic, skin hot; pupils 6 mm bilaterally.', 'section' => 'O'],
                ['id' => 'o2', 'text' => 'Temp 40.1°C, HR 148, BP 168/100, SpO₂ 95% on room air.', 'section' => 'O'],
                ['id' => 'a1', 'text' => 'Excited delirium syndrome with hyperthermia — high mortality risk.', 'section' => 'A'],
                ['id' => 'p1', 'text' => 'Sedation per protocol, rapid cooling, cardiac monitor, transport; restraint only as needed for safety.', 'section' => 'P'],
                ['id' => 'x1', 'text' => 'Officer badge number documented separately.', 'section' => 'X'],
                ['id' => 'x2', 'text' => 'Street parking meter expired.', 'section' => 'X'],
            ],
        ],
        [
            'title' => 'Interfacility STEMI Transfer Handoff',
            'scenario' => 'Critical care transfer: STEMI patient post fibrinolysis from rural ED to PCI center.',
            'detail' => '45-minute ground transfer. You assumed care from RN at sending facility.',
            'sentences' => [
                ['id' => 's1', 'text' => 'Sending RN reports chest pain onset 2 hours ago; tenecteplase given 40 minutes ago.', 'section' => 'S'],
                ['id' => 's2', 'text' => 'Patient reports mild residual chest pressure 3/10.', 'section' => 'S'],
                ['id' => 'o1', 'text' => '12-lead: residual ST elevation II/III/aVF; BP 104/68, HR 92.', 'section' => 'O'],
                ['id' => 'o2', 'text' => 'Dual IVs patent, heparin infusion running per sending orders.', 'section' => 'O'],
                ['id' => 'a1', 'text' => 'Inferior STEMI post fibrinolysis — rescue PCI likely needed.', 'section' => 'A'],
                ['id' => 'p1', 'text' => 'Continuous monitoring, repeat 12-leads, PCI team notified, ETA 18 minutes.', 'section' => 'P'],
                ['id' => 'x1', 'text' => 'Hospital cafeteria closed during transfer.', 'section' => 'X'],
                ['id' => 'x2', 'text' => 'Sending facility built 1972.', 'section' => 'X'],
            ],
        ],
    ],
];
