<?php

namespace Database\Seeders;

use App\Support\CertificationLevel;
use App\Models\Question;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        Question::query()->delete();

        $this->seedForLevel(CertificationLevel::EMT_BASIC, $this->emtBasicQuestions());
        $this->seedForLevel(CertificationLevel::EMT_ADVANCED, $this->emtAdvancedQuestions());
        $this->seedForLevel(CertificationLevel::PARAMEDIC, $this->paramedicQuestions());
        $this->seedForLevel(CertificationLevel::NCLEX_PN, $this->nclexPnQuestions());
    }

    /** @param list<array{0: string, 1: int, 2: string, 3: string, 4: string, 5: string, 6: string, 7: string, 8: string}> $questions */
    private function seedForLevel(string $level, array $questions): void
    {
        $targetLetters = $this->balancedCorrectLetters(count($questions), $level);

        foreach ($questions as $index => [$category, $difficulty, $stem, $a, $b, $c, $d, $correct, $explanation]) {
            $options = $this->redistributeOptions(
                ['A' => $a, 'B' => $b, 'C' => $c, 'D' => $d],
                $correct,
                $targetLetters[$index],
            );

            Question::create([
                'certification_level' => $level,
                'category' => $category,
                'difficulty' => $difficulty,
                'stem' => $stem,
                'option_a' => $options['A'],
                'option_b' => $options['B'],
                'option_c' => $options['C'],
                'option_d' => $options['D'],
                'correct_option' => $targetLetters[$index],
                'explanation' => $explanation,
            ]);
        }
    }

    /** @return list<string> */
    private function balancedCorrectLetters(int $count, string $level): array
    {
        $letters = ['A', 'B', 'C', 'D'];
        $targets = [];

        foreach ($letters as $letter) {
            $targets = array_merge($targets, array_fill(0, intdiv($count, 4), $letter));
        }

        for ($i = 0; $i < $count % 4; $i++) {
            $targets[] = $letters[$i];
        }

        mt_srand(crc32($level));
        shuffle($targets);
        mt_srand();

        return $targets;
    }

    /**
     * @param  array<string, string>  $options
     * @return array<string, string>
     */
    private function redistributeOptions(array $options, string $currentCorrect, string $targetCorrect): array
    {
        $correctText = $options[$currentCorrect];
        $wrongTexts = [];

        foreach (['A', 'B', 'C', 'D'] as $letter) {
            if ($letter !== $currentCorrect) {
                $wrongTexts[] = $options[$letter];
            }
        }

        $result = [];
        $wrongIndex = 0;

        foreach (['A', 'B', 'C', 'D'] as $letter) {
            if ($letter === $targetCorrect) {
                $result[$letter] = $correctText;
            } else {
                $result[$letter] = $wrongTexts[$wrongIndex++];
            }
        }

        return $result;
    }

    /** @return list<array{0: string, 1: int, 2: string, 3: string, 4: string, 5: string, 6: string, 7: string, 8: string}> */
    private function emtBasicQuestions(): array
    {
        return [
            // Difficulty 1
            ['Airway', 1, 'What is the primary purpose of the head-tilt, chin-lift maneuver?', 'Open the airway in an unresponsive patient without suspected spinal injury', 'Stop severe bleeding from the scalp', 'Assess pupil reactivity quickly', 'Stabilize a suspected pelvic fracture', 'A', 'Head-tilt, chin-lift is the basic technique to open the airway when spinal injury is not suspected.'],
            ['Airway', 1, 'Which device is most appropriate for ventilating an apneic adult with a bag-valve mask?', 'Non-rebreather mask at 15 L/min', 'Bag-valve-mask with a tight mask seal and adequate volume', 'Nasal cannula at 6 L/min', 'Simple face mask at 10 L/min', 'B', 'BVM ventilation requires a good seal and enough volume to produce visible chest rise.'],
            ['Cardiology', 1, 'Where should you place your hands for adult CPR compressions?', 'Upper abdomen', 'Center of the chest on the lower half of the sternum', 'Left side of the chest over the heart', 'Over the xiphoid process', 'B', 'Compressions are delivered on the lower half of the sternum to maximize perfusion.'],
            ['Trauma', 1, 'What is the first step in caring for a patient with severe external bleeding?', 'Apply direct pressure to the bleeding site', 'Elevate the legs 90 degrees', 'Apply a tourniquet immediately in all cases', 'Start IV fluids before any bleeding control', 'A', 'Direct pressure is the first intervention for external hemorrhage.'],
            ['Medical', 1, 'Which sign best suggests hypoglycemia in a diabetic patient?', 'Hot, dry skin with Kussmaul respirations', 'Altered mental status with cool, clammy skin and tachycardia', 'Slow, shallow respirations with pinpoint pupils', 'Unequal pupils with battle sign', 'B', 'Hypoglycemia often presents with altered mental status, diaphoresis, and tachycardia.'],
            ['Operations', 1, 'When should PPE be donned during a call?', 'Only after patient contact is made', 'Before patient contact when exposure risk exists', 'Only if the patient requests it', 'After transport is complete', 'B', 'PPE should be worn before contact when there is a risk of exposure.'],
            ['OB/Peds', 1, 'An infant with a heart rate below 60 after 30 seconds of effective ventilation needs:', 'Immediate chest compressions', 'Only blow-by oxygen', 'Immediate defibrillation at 360J monophasic', 'No intervention unless cyanotic', 'A', 'Neonatal resuscitation guidelines call for compressions when HR remains below 60 despite ventilation.'],
            ['Airway', 1, 'An oropharyngeal airway should be sized by measuring from:', 'Earlobe to nipple line', 'Corner of the mouth to the angle of the mandible', 'Chin to xiphoid', 'Nose to umbilicus', 'B', 'OPA sizing uses the corner of the mouth to the angle of the mandible.'],
            ['Cardiology', 1, 'The normal adult respiratory rate is approximately:', '4-8 breaths per minute', '12-20 breaths per minute', '28-36 breaths per minute', '40-50 breaths per minute', 'B', 'Normal adult ventilatory rate is about 12-20/min.'],
            ['Trauma', 1, 'Which finding is most concerning in a head injury patient?', 'Repeated vomiting and decreasing level of consciousness', 'Small scalp laceration without swelling', 'Brief dizziness after minor bump', 'Mild headache with normal orientation', 'A', 'Vomiting with declining mental status suggests rising intracranial pressure.'],

            // Difficulty 2
            ['Airway', 2, 'You cannot ventilate an adult with a BVM despite an oropharyngeal airway. What is the best next step?', 'Insert a nasopharyngeal airway and reattempt ventilation', 'Begin chest compressions only', 'Wait for ALS to arrive without further airway attempts', 'Apply a non-rebreather at 15 L/min', 'A', 'An NPA may improve airflow when an OPA alone is insufficient and insertion is appropriate.'],
            ['Cardiology', 2, 'A conscious patient with chest pain, diaphoresis, and nitroglycerin prescribed should receive NTG if:', 'Systolic BP is 90 mmHg', 'They have taken sildenafil within 24 hours', 'Systolic BP is above 100 mmHg and no contraindications exist', 'They are bradycardic at 48/min regardless of BP', 'C', 'NTG is indicated when systolic BP is adequate and no contraindications are present.'],
            ['Trauma', 2, 'For an open pneumothorax, initial management includes:', 'Occlusive dressing taped on three sides', 'Needle decompression at the second intercostal space in all patients', 'High-flow oxygen only without wound coverage', 'Immediate endotracheal intubation in every case', 'A', 'An occlusive three-sided dressing prevents air from entering the wound during inspiration.'],
            ['Medical', 2, 'A patient with asthma has wheezing and speaking in two-word sentences. Priority treatment is:', 'Albuterol via nebulizer or MDI', 'Oral antihistamine only', 'Immediate rapid sequence intubation without bronchodilators', 'High-dose aspirin', 'A', 'Severe bronchospasm requires prompt beta-agonist therapy.'],
            ['Operations', 2, 'Medical direction is typically required for:', 'Applying a bandage to a minor abrasion', 'Administering epinephrine auto-injector per protocol', 'Assisting a patient with prescribed nitroglycerin when protocol allows', 'Both B and C depending on local protocol', 'D', 'Many medication administrations are protocol-driven and may require online/offline medical direction per local policy.'],
            ['OB/Peds', 2, 'A 3-year-old with a respiratory rate of 32, mild wheezing, and good color is best classified as:', 'Respiratory failure requiring immediate intubation', 'Mild to moderate respiratory distress needing evaluation and treatment', 'Cardiac arrest', 'Normal for age with no intervention needed', 'B', 'Tachypnea with wheezing suggests distress that needs treatment but not necessarily immediate airway control.'],
            ['Airway', 2, 'Capnography during BVM ventilation primarily helps confirm:', 'Placement and effectiveness of ventilation', 'Need for immediate cricothyrotomy', 'Presence of a pneumothorax without exam', 'Exact hemoglobin level', 'A', 'Waveform capnography confirms ventilation and airway patency.'],
            ['Cardiology', 2, 'Which rhythm is shockable in cardiac arrest?', 'Asystole', 'Pulseless electrical activity', 'Ventricular fibrillation', 'Sinus bradycardia with a pulse', 'C', 'VF and pulseless VT are shockable rhythms.'],
            ['Trauma', 2, 'Signs of internal bleeding in the abdomen may include:', 'Rigid abdomen, hypotension, and tachycardia', 'Warm dry skin and hypertension', 'Bradycardia with bounding pulses only', 'Isolated knee pain without vital sign changes', 'A', 'Abdominal rigidity with shock signs suggests internal hemorrhage.'],
            ['Medical', 2, 'A patient with suspected stroke should be transported to:', 'The nearest hospital regardless of capability', 'A stroke center when available and within acceptable time limits', 'Any urgent care clinic', 'The farthest facility to allow more assessment time', 'B', 'Stroke patients benefit from transport to appropriate stroke-capable centers.'],

            // Difficulty 3
            ['Airway', 3, 'After two failed intubation attempts in an adult trauma patient, the best airway plan is:', 'Continue unlimited intubation attempts on scene', 'Use a supraglottic airway or BVM per protocol and prepare surgical airway if needed', 'Withdraw all airway support and transport apneic', 'Place a nasal cannula and defer all other care', 'B', 'Failed airway algorithms emphasize rescue devices and surgical airway readiness.'],
            ['Cardiology', 3, 'A patient in narrow-complex regular tachycardia at 180/min with hypotension and altered mental status should receive:', 'Vagal maneuvers only and observation', 'Synchronized cardioversion when protocol allows', 'Immediate defibrillation without synchronization', 'Adenosine 12 mg before any other action regardless of stability', 'B', 'Unstable tachycardia with a pulse is treated with synchronized cardioversion.'],
            ['Trauma', 3, 'A patient with unilateral absent breath sounds, tracheal deviation, and shock after chest trauma likely has:', 'Simple rib fracture only', 'Tension pneumothorax', 'Isolated hemothorax without respiratory compromise', 'Flail chest without ventilation issues', 'B', 'Absent breath sounds, JVD/tracheal deviation, and shock suggest tension pneumothorax.'],
            ['Medical', 3, 'A patient with DKA may present with:', 'Kussmaul respirations, fruity breath, and hyperglycemia', 'Pinpoint pupils and bradypnea', 'Warm, dry skin with hypoglycemia', 'Hypertension with slow pulse only', 'A', 'DKA classically causes deep rapid breathing and hyperglycemia.'],
            ['Operations', 3, 'When refusing transport, a competent adult patient should:', 'Be ignored and transported anyway', 'Be informed of risks and allowed to sign out against medical advice when appropriate', 'Be restrained without documentation', 'Be discharged without any documentation or capacity assessment', 'B', 'Competent patients may refuse care after informed risk discussion and proper documentation.'],
            ['OB/Peds', 3, 'A newborn is limp, cyanotic, and not breathing after birth. First action is:', 'Dry, warm, stimulate, and position airway', 'Immediate IO access before any airway steps', 'Chest compressions before any ventilation attempt', 'Wait 5 minutes to see if tone improves', 'A', 'Initial neonatal resuscitation begins with warming, drying, stimulation, and airway positioning.'],
            ['Airway', 3, 'Sellick maneuver during intubation is intended to:', 'Prevent gastric insufflation and passive regurgitation', 'Increase blood pressure during sedation', 'Confirm endotracheal tube depth', 'Reduce the need for oxygenation before intubation', 'A', 'Cricoid pressure is used to reduce regurgitation risk during airway management.'],
            ['Cardiology', 3, 'STEMI recognition requires:', 'ST elevation meeting protocol criteria in contiguous leads with clinical correlation', 'Any T-wave inversion in one lead only', 'Normal ECG with chest pain', 'Bradycardia alone', 'A', 'STEMI is identified by ST elevation patterns per protocol and clinical presentation.'],
            ['Trauma', 3, 'Pelvic fracture suspicion with hypotension should prompt:', 'Early hemorrhage control measures and rapid transport', 'Delayed transport for repeated field exams only', 'High-flow oxygen without fluid or transport planning', 'Application of traction splint to the pelvis in all cases', 'A', 'Pelvic fractures can cause massive hemorrhage and require urgent transport and control strategies.'],
            ['Medical', 3, 'Organophosphate exposure is suggested by:', 'Miosis, salivation, bronchorrhea, and bradycardia', 'Mydriasis and dry skin only', 'Kussmaul respirations with hyperglycemia', 'Battle sign and raccoon eyes', 'A', 'SLUDGE/BBB symptoms indicate cholinergic toxicity.'],

            // Difficulty 4
            ['Airway', 4, 'A patient with severe angioedema and stridor is failing BVM ventilation. Most appropriate advanced action is:', 'Continue BVM indefinitely without escalation', 'Prepare for surgical cricothyrotomy if supraglottic rescue fails', 'Administer oral fluids to soothe the throat', 'Place patient in Trendelenburg and observe', 'B', 'Complete upper airway obstruction may require surgical airway when other methods fail.'],
            ['Cardiology', 4, 'Wide-complex monomorphic tachycardia at 220/min with a pulse and chest pain likely represents:', 'Sinus tachycardia from anxiety only', 'Ventricular tachycardia until proven otherwise', 'Normal variant requiring no treatment', 'Third-degree heart block', 'B', 'Wide-complex tachycardia should be treated as VT until proven otherwise.'],
            ['Trauma', 4, 'A patient with penetrating torso trauma becomes combative with hypotension and distended neck veins. Priority concern is:', 'Behavioral emergency only', 'Cardiac tamponade or tension pneumothorax', 'Hyperglycemia', 'Simple anxiety reaction', 'B', 'Beck triad suggests tamponade; tension pneumo can present similarly.'],
            ['Medical', 4, 'Tricyclic antidepressant overdose may cause:', 'QRS widening, anticholinergic signs, and seizures', 'Pinpoint pupils and bradypnea only', 'Isolated hypertension without ECG changes', 'Normal mental status with hypothermia only', 'A', 'TCA toxicity affects sodium channels and can cause wide QRS and seizures.'],
            ['Operations', 4, 'During a mass casualty incident with limited resources, triage priority goes to patients who:', 'Are obviously dead or expectant in many systems', 'Have minor abrasions first', 'Demand transport first regardless of severity', 'Have the loudest complaints only', 'A', 'Triage allocates resources to those most likely to benefit; expectant/deceased categories delay care appropriately.'],
            ['OB/Peds', 4, 'A postpartum patient with sudden dyspnea and blood-tinged sputum after delivery may have:', 'Amniotic fluid embolism or pulmonary embolism', 'Normal postpartum fatigue only', 'Simple asthma without urgency', 'Isolated anemia without respiratory symptoms', 'A', 'Sudden respiratory distress postpartum is an obstetric emergency until proven otherwise.'],
            ['Airway', 4, 'Confirmation of advanced airway placement should include:', 'Multiple methods such as capnography, chest rise, and auscultation per protocol', 'Tube depth mark alone', 'Patient color only after 10 minutes', 'Absence of gastric sounds only', 'A', 'Airway confirmation requires multiple assessment tools per protocol.'],
            ['Cardiology', 4, 'A patient with inferior STEMI and bradycardia may worsen with:', 'Nitroglycerin if right ventricular involvement is suspected and preload dependent', 'Oxygen for hypoxia', 'Aspirin per protocol', 'Rapid transport to PCI center', 'A', 'RV infarction can be preload dependent; nitrates may cause profound hypotension.'],
            ['Trauma', 4, 'Burns involving circumferential extremity eschar with absent distal pulse require consideration of:', 'Escharotomy for compartment pressure relief', 'Immediate amputation in the field', 'Ice immersion for 30 minutes', 'Topical antibiotic only without transport', 'A', 'Circumferential burns can cause compartment syndrome requiring escharotomy.'],
            ['Medical', 4, 'Hyperkalemia ECG findings may include:', 'Peaked T waves, widened QRS, and sine wave pattern', 'ST elevation in V1-V4 only', 'Short QT with bradycardia only', 'Normal sinus rhythm always', 'A', 'Hyperkalemia produces characteristic progressive ECG changes.'],

            // Difficulty 5
            ['Airway', 5, 'In a cannot-intubate, cannot-oxygenate adult, immediate life-saving intervention is:', 'Cricothyrotomy', 'Nasal trumpet only', 'Repeat laryngoscopy indefinitely', 'Oral suction and reassess in 30 minutes', 'A', 'CICO is a surgical airway emergency.'],
            ['Cardiology', 5, 'Polymorphic ventricular tachycardia with prolonged QT should prompt consideration of:', 'Magnesium and correction of electrolytes; avoid treatments that prolong QT further', 'Routine adenosine as first-line in all cases', 'Immediate synchronized cardioversion without rhythm analysis', 'High-dose beta blocker bolus in every patient', 'A', 'Torsades/degenerative polymorphic VT is treated with magnesium and addressing precipitants.'],
            ['Trauma', 5, 'A patient with traumatic cardiac arrest and signs of life on ultrasound may benefit from:', 'Resuscitative thoracotomy in select systems and rapid transport', 'Termination of care on scene without assessment', 'Delayed transport for repeat vitals every 15 minutes', 'Only oral airway placement', 'A', 'Selected trauma arrests with signs of life may warrant aggressive resuscitative interventions per protocol.'],
            ['Medical', 5, 'A patient with adrenal crisis presents with refractory hypotension after fluid bolus. Appropriate consideration includes:', 'Stress-dose steroids per protocol and treat precipitating cause', 'Only repeat fluid without hormonal support', 'Immediate discharge if awake', 'High-flow oxygen alone', 'A', 'Adrenal insufficiency requires glucocorticoid replacement and supportive care.'],
            ['Operations', 5, 'When operating under extended care due to prolonged extrication, priority shifts include:', 'Monitoring for hypothermia, pain, fluid balance, and deterioration while coordinating resources', 'Stopping all reassessment until arrival at hospital', 'Withholding analgesia to keep patient alert indefinitely', 'Deferring all communication with medical control', 'A', 'Prolonged field care requires ongoing reassessment and resource coordination.'],
            ['OB/Peds', 5, 'A pregnant trauma patient at 32 weeks with hypotension should be positioned to:', 'Provide left lateral uterine displacement to reduce aortocaval compression', 'Remain flat supine without displacement', 'Trendelenburg without other measures', 'Sit upright only regardless of vitals', 'A', 'Left uterine displacement improves venous return in late pregnancy.'],
            ['Airway', 5, 'Difficult airway predictors in an obese patient include:', 'Limited mouth opening, large neck circumference, and decreased neck mobility', 'Normal BMI and full neck range of motion', 'Ability to prognath easily with good mouth opening', 'Absence of beard or facial trauma', 'A', 'Obesity and limited mobility increase intubation difficulty.'],
            ['Cardiology', 5, 'A paced rhythm with capture but no pulse indicates:', 'Pulseless electrical activity requiring CPR and treatment of reversible causes', 'Successful perfusion requiring no further action', 'Normal functioning pacemaker with adequate perfusion always', 'Need for immediate unsynchronized shock at 360J always', 'A', 'Electrical activity without a pulse is PEA and treated as arrest.'],
            ['Trauma', 5, 'Combined blast injury with tympanic membrane rupture, abdominal pain, and delayed dyspnea suggests:', 'Primary, secondary, and possible tertiary/quaternary blast injury patterns', 'Isolated otologic injury only', 'Simple anxiety without internal injury risk', 'No need for serial reassessment', 'A', 'Blast injuries may evolve and involve multiple organ systems.'],
            ['Medical', 5, 'Severe beta-blocker overdose with bradycardia and hypotension may require:', 'Glucagon, supportive care, and advanced cardiac monitoring per protocol', 'Only oral fluids', 'Immediate discharge if awake', 'Adenosine 6 mg as sole therapy', 'A', 'Beta-blocker toxicity may respond to glucagon and aggressive supportive care.'],
        ];
    }

    /** @return list<array{0: string, 1: int, 2: string, 3: string, 4: string, 5: string, 6: string, 7: string, 8: string}> */
    private function emtAdvancedQuestions(): array
    {
        return [
            ['Airway', 1, 'An AEMT may assist with which airway adjunct under protocol?', 'Dual-lumen supraglottic airway when authorized', 'Cricothyrotomy as first choice in all patients', 'Needle decompression without training', 'Rapid sequence intubation independently in all states', 'A', 'AEMT scope varies by state but often includes supraglottic airways when authorized.'],
            ['Pharmacology', 2, 'Which medication is commonly within AEMT scope for anaphylaxis?', 'Epinephrine auto-injector or IM epinephrine per protocol', 'Amiodarone 300 mg IV push', 'Rocuronium 1 mg/kg', 'Magnesium 2 g IV over 10 minutes in all patients', 'A', 'Epinephrine for anaphylaxis is a core AEMT skill in many jurisdictions.'],
            ['IV Therapy', 2, 'Before initiating an IV, the AEMT should:', 'Verify patient identity, indication, and site selection per protocol', 'Always use the antecubital fossa regardless of condition', 'Never use a tourniquet', 'Flush with any available fluid without checking allergies', 'A', 'IV initiation requires indication, consent when possible, and proper site selection.'],
            ['Cardiology', 3, 'A 12-lead ECG obtained by an AEMT should be used to:', 'Identify STEMI patterns and facilitate early notification per protocol', 'Replace all physical exams', 'Determine blood glucose without a glucometer', 'Rule out all arrhythmias without medical direction', 'A', '12-lead acquisition supports early STEMI recognition and destination decisions.'],
            ['Trauma', 3, 'For a patient with suspected long bone fracture, AEMT care includes:', 'Manual stabilization, splinting, neurovascular checks, and pain management per protocol', 'Aggressive joint manipulation to restore alignment in the field', 'Delayed splinting until hospital arrival always', 'Application of traction splint to humerus fractures routinely', 'A', 'Splinting with neurovascular assessment is standard AEMT fracture care.'],
            ['Medical', 3, 'A patient with moderate dehydration and nausea may receive:', 'Oral glucose or oral hydration when alert and protocol allows', 'Immediate RSI without assessment', 'High-dose narcotics before exam', 'Only IM epinephrine', 'A', 'AEMTs may support oral hydration/glucose when appropriate and authorized.'],
            ['OB/Peds', 3, 'An AEMT managing a precipitous delivery should:', 'Support perineum, control delivery of head and body, and dry/warm the newborn', 'Pull forcefully on the head to expedite delivery', 'Clamp the cord before any drying or stimulation', 'Delay all newborn care until hospital arrival', 'A', 'Field delivery focuses on controlled delivery and newborn warming/stimulation.'],
            ['Pharmacology', 4, 'Dextrose 10% (D10) may be indicated for:', 'Symptomatic hypoglycemia when IV access is established and protocol allows', 'All patients with chest pain', 'Hypertensive emergency in every patient', 'Hyperkalemia as sole therapy', 'A', 'D10 is used for hypoglycemia when within AEMT scope and indicated.'],
            ['Cardiology', 4, 'Synchronized cardioversion at the AEMT level requires:', 'Training, protocol authorization, and appropriate monitoring', 'No medical direction in any system', 'Use only for asystole', 'Automatic performance for all tachycardias regardless of stability', 'A', 'Cardioversion is an advanced skill requiring authorization and monitoring.'],
            ['Operations', 4, 'When performing extended care as an AEMT during a prolonged extrication:', 'Reassess vitals, pain, perfusion, and IV site at regular intervals', 'Document once at scene arrival only', 'Withhold all analgesia until ED arrival always', 'Remove all splints to reassess hourly', 'A', 'Extended care requires ongoing reassessment and documentation.'],
            ['Airway', 5, 'An AEMT recognizes supraglottic airway malplacement when:', 'No capnography waveform, absent breath sounds, and gastric distention occur', 'Patient speaks in full sentences with the device in place', 'Easy ventilation with visible chest rise and capnography present', 'Patient requests removal for comfort', 'A', 'Failed placement shows poor ventilation and absent EtCO2 confirmation.'],
            ['Pharmacology', 5, 'Naloxone administration by an AEMT should be guided by:', 'Respiratory depression or unresponsiveness with suspected opioid toxicity per protocol', 'Any patient who uses opioids regardless of exam', 'All pain patients receiving narcotics prophylactically', 'Pediatric fever alone', 'A', 'Naloxone is indicated for suspected opioid-induced respiratory compromise.'],
            ['IV Therapy', 2, 'Signs of IV infiltration include:', 'Edema, coolness, and resistance to flushing at the site', 'Improved flow rate and patient comfort', 'Blood return with easy flush always', 'Warmth and redness only without swelling', 'A', 'Infiltration presents with swelling, cool skin, and poor flow.'],
            ['Trauma', 2, 'Traction splint application is indicated for:', 'Mid-shaft femur fracture without pelvis or knee injury contraindications', 'All lower leg injuries including ankle sprains', 'Humerus fractures as first choice', 'Pelvic instability as primary treatment', 'A', 'Traction splints address isolated mid-shaft femur fractures when appropriate.'],
            ['Medical', 4, 'A patient with altered mental status and fruity breath may need:', 'Blood glucose assessment and glucose administration if hypoglycemic per protocol', 'Immediate defibrillation', 'Only oral antibiotics', 'High-flow oxygen without further assessment', 'A', 'Altered mental status requires glucose assessment among other priorities.'],
            ['Cardiology', 2, 'AEMT interpretation of sinus tachycardia should include:', 'Assessing for fever, dehydration, pain, hypoxia, and shock', 'Automatic cardioversion', 'Ignoring rate if blood pressure is normal always', 'Immediate sedation without cause search', 'A', 'Tachycardia requires searching for underlying cause and treating appropriately.'],
            ['OB/Peds', 2, 'When assessing a pediatric patient, the AEMT should:', 'Use age-appropriate communication and weight-based dosing tools per protocol', 'Use adult vital sign norms for all ages', 'Avoid involving caregivers in assessment', 'Withhold oxygen from all infants', 'A', 'Pediatric assessment requires age-specific norms and communication.'],
            ['Operations', 2, 'AEMT scope documentation on scene should include:', 'Interventions, patient response, times, and medical direction contacts', 'Only departure time', 'Patient social security number always', 'No vital signs if stable appearing', 'A', 'Complete documentation supports continuity of care and legal requirements.'],
            ['Airway', 3, 'CPAP initiated by an AEMT is appropriate when:', 'Protocol allows and patient has responsive respiratory distress with adequate BP', 'Patient is apneic', 'Systolic BP is 70 mmHg', 'Patient refuses all monitoring but is in arrest', 'A', 'CPAP requires spontaneous breathing and hemodynamic tolerance per protocol.'],
            ['Pharmacology', 3, 'Nitroglycerin drip initiation at the AEMT level:', 'Depends on local protocol; many AEMT systems use SL NTG only', 'Is universal at all AEMT levels without exception', 'Is indicated for all chest pain regardless of BP', 'Replaces all fluid resuscitation always', 'A', 'AEMT pharmacology scope varies; NTG forms depend on local authorization.'],
        ];
    }

    /** @return list<array{0: string, 1: int, 2: string, 3: string, 4: string, 5: string, 6: string, 7: string, 8: string}> */
    private function paramedicQuestions(): array
    {
        return [
            ['Airway', 2, 'Paramedic RSI preparation should include:', 'Preoxygenation, suction, monitoring, and paralytic/sedation per protocol', 'Immediate intubation without medications', 'Only nasal cannula at 2 L/min', 'Deferring airway until ED in all unstable patients', 'A', 'RSI requires preparation, monitoring, and pharmacologic support per protocol.'],
            ['Pharmacology', 3, 'Etomidate is selected in RSI primarily because it:', 'Provides rapid induction with minimal hemodynamic depression in many patients', 'Provides long-lasting paralysis', 'Reverses opioid toxicity', 'Treats hyperkalemia directly', 'A', 'Etomidate offers rapid induction with relatively stable hemodynamics.'],
            ['Cardiology', 3, 'Transcutaneous pacing is indicated for:', 'Symptomatic bradycardia unresponsive to atropine when pacing is available', 'Stable sinus bradycardia at 55/min', 'Ventricular fibrillation', 'All tachycardias', 'A', 'TCP treats symptomatic bradycardia when medical therapy fails.'],
            ['Cardiology', 4, 'A post-ROSC patient should receive:', 'Targeted oxygenation, blood pressure support, and 12-lead ECG per protocol', 'Hyperventilation to pCO2 of 20', 'Immediate discharge if pulse returns', 'No further monitoring if awake', 'A', 'Post-arrest care focuses on oxygenation, perfusion, and cause identification.'],
            ['Pharmacology', 4, 'Amiodarone 300 mg IV is used in cardiac arrest for:', 'VF/pulseless VT refractory to defibrillation per ACLS', 'Asystole as first-line always', 'Stable SVT as first choice', 'Anaphylaxis', 'A', 'Amiodarone is an antiarrhythmic for shock-refractory VF/pVT.'],
            ['Trauma', 3, 'Needle decompression for tension pneumothorax is performed:', 'At the appropriate anterior chest site per protocol when signs are present', 'Only in the ED', 'Bilaterally in all trauma patients prophylactically', 'Through the epigastrium routinely', 'A', 'Needle decompression addresses life-threatening tension pneumothorax in the field.'],
            ['Medical', 4, 'A patient with tricyclic overdose and QRS widening may receive:', 'Sodium bicarbonate per protocol and aggressive airway support', 'Only activated charcoal after 4 hours', 'Adenosine as sole therapy', 'Oral fluids and discharge', 'A', 'TCA toxicity with wide QRS may respond to bicarbonate per protocol.'],
            ['OB/Peds', 4, 'A paramedic managing eclampsia should prioritize:', 'Seizure control, airway protection, and rapid transport per protocol', 'Oral hydration only', 'Waiting for spontaneous seizure resolution without treatment', 'Immediate field delivery regardless of gestational age always', 'A', 'Eclampsia requires seizure management and urgent obstetric care.'],
            ['Pharmacology', 5, 'Push-dose epinephrine may be used to:', 'Temporarily support blood pressure in refractory hypotension per protocol', 'Replace all fluid resuscitation', 'Treat stable hypertension', 'Reverse benzodiazepine overdose', 'A', 'Push-dose pressors are a bridge in select hypotensive states per protocol.'],
            ['Cardiology', 5, 'Recognizing hyperkalemia on 12-lead may show:', 'Peaked T waves progressing to wide QRS and sine wave', 'ST elevation in aVR only as sole finding always', 'Normal sinus rhythm only', 'Short QT with bradycardia exclusively', 'A', 'Hyperkalemia produces characteristic ECG progression.'],
            ['Airway', 4, 'Post-intubation sedation and analgesia should be:', 'Maintained per protocol to prevent awareness and ventilator dyssynchrony', 'Withheld to expedite transport always', 'Provided only if patient requests it', 'Limited to paralytic only without sedation', 'A', 'Post-intubation patients require ongoing sedation/analgesia per protocol.'],
            ['Operations', 3, 'Paramedic critical care transport decisions should consider:', 'Patient acuity, interventions required en route, and receiving facility capability', 'Only closest facility regardless of specialty', 'Patient preference alone without clinical factors', 'Weather only', 'A', 'Destination decisions weigh acuity, needed resources, and facility capability.'],
            ['Trauma', 4, 'Resuscitative endovascular balloon occlusion (REBOA) when available is:', 'A specialized intervention outside standard street paramedic scope in most systems', 'First-line for all extremity fractures', 'Used for simple nosebleeds', 'Standard BLS skill', 'A', 'REBOA is a specialized critical care intervention not routine for all paramedics.'],
            ['Medical', 3, 'An asthma patient in status asthmaticus despite initial bronchodilators may need:', 'Repeat bronchodilator, magnesium, CPAP/intubation preparation per protocol', 'Discharge from scene if speaking', 'Only antihistamine PO', 'Defibrillation', 'A', 'Status asthmaticus may require escalating bronchodilator therapy and airway support.'],
            ['Pharmacology', 3, 'Ketamine may be used in RSI for:', 'Induction in asthmatics or hemodynamically unstable patients per protocol', 'All patients with hypertension only', 'Reversal of paralytics', 'Treatment of hypoglycemia', 'A', 'Ketamine provides induction with bronchodilation and hemodynamic support in select patients.'],
            ['Cardiology', 2, 'Monomorphic wide-complex tachycardia with pulse should be treated as:', 'Ventricular tachycardia until proven otherwise', 'Sinus tachycardia always', 'Normal variant requiring no treatment', 'Atrial fibrillation only', 'A', 'Wide-complex tachycardia is VT until proven otherwise.'],
            ['OB/Peds', 3, 'Neonatal resuscitation with HR below 60 after ventilation requires:', 'Chest compressions coordinated with ventilations per NRP guidelines', 'Only blow-by oxygen indefinitely', 'Defibrillation at 4 J/kg as first step always', 'No compressions in the field', 'A', 'Neonatal algorithm calls for compressions when HR remains below 60 despite effective ventilation.'],
            ['Airway', 5, 'Cannot intubate, cannot oxygenate in a paramedic airway scenario requires:', 'Emergency surgical cricothyrotomy when authorized and indicated', 'Continued attempts without limit', 'Nasal cannula at 1 L/min', 'Transport apneic without intervention', 'A', 'CICO is a surgical airway emergency.'],
            ['Pharmacology', 4, 'Calcium chloride may be indicated for:', 'Hyperkalemia, calcium channel blocker overdose, or hypocalcemia per protocol', 'All chest pain patients', 'Anaphylaxis as first-line instead of epinephrine', 'Hypoglycemia', 'A', 'Calcium has specific indications including hyperkalemia and calcium channel blocker toxicity.'],
            ['Medical', 5, 'Severe sepsis in the field should prompt:', 'Early recognition, oxygen, IV access, fluid per protocol, and rapid transport', 'Delayed transport for repeat vitals every hour only', 'Oral antibiotics only', 'Withholding fluids in all hypotensive patients', 'A', 'Sepsis requires early recognition, supportive care, and rapid transport.'],
        ];
    }

    /** @return list<array{0: string, 1: int, 2: string, 3: string, 4: string, 5: string, 6: string, 7: string, 8: string}> */
    private function nclexPnQuestions(): array
    {
        return [
            // Difficulty 1
            ['Safe Care', 1, 'Before entering an isolation room, the PN should first:', 'Perform hand hygiene and don appropriate PPE', 'Document vital signs at the nurses\' station', 'Administer scheduled medications early', 'Remove all PPE in the hallway after exit only', 'A', 'Hand hygiene and proper PPE sequence prevent transmission of infection.'],
            ['Basic Care', 1, 'When measuring an oral temperature, the PN should:', 'Ensure the patient has not smoked or consumed hot fluids in the last 15 minutes', 'Use the same thermometer for all patients without cleaning', 'Place the probe under the tongue on the side with a pacemaker', 'Record axillary and oral temperatures as equivalent always', 'A', 'Recent hot/cold intake or smoking can falsely alter oral temperature readings.'],
            ['Health Promotion', 1, 'A primary goal of patient education for a new insulin prescription is:', 'Safe self-administration and recognition of hypoglycemia', 'Memorizing the drug\'s chemical structure', 'Discontinuing glucose monitoring once stable', 'Avoiding all carbohydrate intake permanently', 'A', 'Education should focus on safe use and recognizing dangerous side effects.'],
            ['Psychosocial', 1, 'A patient who says "I don\'t want to talk about it" during admission should be met with:', 'Respectful presence, open-ended offers to listen, and assessment for safety', 'Immediate psychiatric commitment without evaluation', 'Changing the subject to lighter topics only', 'Leaving the room without further contact', 'A', 'Therapeutic communication respects boundaries while maintaining supportive care.'],
            ['Pharmacology', 1, 'The PN recognizes a medication error has occurred. The first action is:', 'Assess the patient and notify the RN or provider per facility policy', 'Document the error only in the patient diary', 'Discard the unused medication without reporting', 'Wait until the end of the shift to mention it', 'A', 'Patient safety requires immediate assessment and notification when errors occur.'],
            ['Adult Health', 1, 'Early signs of hypovolemic shock may include:', 'Increased heart rate and decreased urine output', 'Bounding pulse and brisk capillary refill only', 'Hypertension and wide pulse pressure', 'Bradycardia with warm, dry skin exclusively', 'A', 'Compensatory tachycardia and oliguria are early shock indicators.'],
            ['Maternal/Child', 1, 'When holding a newborn, the PN should:', 'Support the head and neck and maintain safe body alignment', 'Hold the infant only by the ankles during transport', 'Place soft pillows in the crib for positioning', 'Leave the newborn unattended on an adult bed briefly', 'A', 'Newborns require head/neck support due to weak muscle control.'],
            ['Risk Reduction', 1, 'To reduce fall risk in an older adult, the PN should:', 'Keep the call light within reach and bed in low position with brakes locked', 'Use side rails as restraints without an order', 'Dim all lights at night without night lights', 'Encourage ambulation without non-slip footwear', 'A', 'Fall prevention includes accessible call devices, low beds, and safe mobility aids.'],
            ['Safe Care', 1, 'Standard precautions apply to:', 'All patients regardless of suspected diagnosis', 'Only patients with confirmed HIV', 'Patients in reverse isolation exclusively', 'Visitors but not healthcare workers', 'A', 'Standard precautions are used for all patient interactions.'],
            ['Basic Care', 1, 'When assisting a patient with oral care who is unconscious, the PN should:', 'Position the patient on the side to prevent aspiration', 'Use large amounts of fluid with the head flat', 'Perform oral care only once per hospitalization', 'Place cotton swabs deep into the pharynx routinely', 'A', 'Side-lying position reduces aspiration risk during oral care.'],
            // Difficulty 2
            ['Pharmacology', 2, 'A patient prescribed warfarin should be taught to report:', 'Unusual bleeding, dark stools, or severe headache', 'Mild thirst after exercise only', 'Occasional yawning in the morning', 'Improved appetite as an emergency sign', 'A', 'Anticoagulant therapy requires monitoring for bleeding complications.'],
            ['Adult Health', 2, 'A patient with COPD receiving oxygen via nasal cannula at 5 L/min becomes sleepy and has a rising PaCO2. The PN should:', 'Notify the RN — high-flow oxygen may suppress hypoxic drive in select COPD patients', 'Increase oxygen to 10 L/min without assessment', 'Remove oxygen and leave the patient without monitoring', 'Place an ice pack on the forehead only', 'A', 'Excessive oxygen in some COPD patients can worsen hypercapnia; notify the care team.'],
            ['Psychosocial', 2, 'Therapeutic communication with an anxious patient includes:', 'Calm tone, short clear statements, and acknowledging feelings', 'Arguing that there is nothing to worry about', 'Providing lengthy medical lectures during acute anxiety', 'Using medical jargon to sound authoritative', 'A', 'Validation and clarity reduce anxiety more than dismissal or jargon.'],
            ['Health Promotion', 2, 'When teaching foot care to a patient with diabetes, the PN should emphasize:', 'Daily inspection, proper footwear, and never soaking feet in hot water', 'Trimming nails aggressively into the corners', 'Walking barefoot outdoors to toughen skin', 'Applying heating pads to improve circulation nightly', 'A', 'Diabetic foot care focuses on prevention of injury and infection.'],
            ['Safe Care', 2, 'The PN receives a telephone order for a new medication. The correct action is:', 'Repeat the order back for verification and document per policy', 'Administer immediately and chart later', 'Accept orders only from family members', 'Refuse all telephone orders in every setting', 'A', 'Read-back verification reduces transcription errors for verbal/telephone orders.'],
            ['Maternal/Child', 2, 'An infant with a rectal temperature of 100.4°F (38°C) requires:', 'Prompt notification and further assessment per pediatric protocol', 'No action if feeding well', 'Immediate discharge planning only', 'Application of alcohol baths at home without reporting', 'A', 'Fever in young infants can indicate serious infection and needs evaluation.'],
            ['Risk Reduction', 2, 'Before ambulating a postoperative patient, the PN should:', 'Assess pain, dizziness, orthostatic vitals, and assistive devices', 'Ambulate alone without calling for help', 'Withhold pain medication to keep the patient alert', 'Use a gait belt only for pediatric patients', 'A', 'Pre-ambulation assessment reduces fall and syncope risk after surgery.'],
            ['Basic Care', 2, 'A patient on strict fluid restriction should have intake recorded:', 'All oral fluids, IV fluids, ice chips, and foods with high fluid content', 'Only water consumed from a cup', 'IV fluids but not ice chips', 'Fluids only if volume exceeds 240 mL', 'A', 'Fluid restrictions require accurate measurement of all fluid sources.'],
            ['Adult Health', 2, 'Crackles at lung bases in a patient with heart failure suggest:', 'Pulmonary congestion requiring assessment and possible diuretic therapy', 'Normal finding requiring no follow-up', 'Improved gas exchange exclusively', 'Need for high-sodium diet encouragement', 'A', 'Basilar crackles may indicate fluid overload in heart failure.'],
            ['Pharmacology', 2, 'A patient receiving IV potassium should be monitored for:', 'Cardiac dysrhythmias and proper infusion rate per protocol', 'Hypertension only without ECG changes', 'Improved vision as a primary effect', 'No need to use an infusion pump', 'A', 'IV potassium must be infused slowly; rapid infusion can cause fatal arrhythmias.'],
            // Difficulty 3
            ['Safe Care', 3, 'A confused patient pulls at an IV line. The most appropriate initial intervention is:', 'Reorient, ensure safety, notify RN, and use alternatives per care plan', 'Apply wrist restraints immediately without an order', 'Leave the room until the behavior stops', 'Remove the IV without provider notification', 'A', 'Non-pharmacologic safety measures and team notification come before restraints.'],
            ['Adult Health', 3, 'A patient with acute chest pain and diaphoresis should receive priority assessment for:', 'Myocardial infarction including vital signs, ECG, and pain evaluation', 'Constipation only', 'Routine discharge teaching first', 'Delayed assessment until lunch is served', 'A', 'Acute chest pain with diaphoresis is a cardiac emergency until ruled out.'],
            ['Pharmacology', 3, 'The PN prepares to administer digoxin and finds the apical pulse is 58/min. The PN should:', 'Hold the dose and notify the RN or provider per protocol', 'Administer half the dose without reporting', 'Crush the tablet and mix with applesauce anyway', 'Give the dose if the radial pulse is 72/min', 'A', 'Digoxin is often held for bradycardia per protocol; use apical pulse for one minute.'],
            ['Psychosocial', 3, 'A patient experiencing grief after a miscarriage needs the PN to:', 'Provide empathetic support and facilitate appropriate referrals', 'Minimize feelings by comparing to others\' losses', 'Avoid discussing the topic entirely', 'Tell the patient to "stay positive" and move on quickly', 'A', 'Grief support requires empathy and appropriate resources, not minimization.'],
            ['Maternal/Child', 3, 'When assessing a breastfeeding mother, the PN should evaluate for:', 'Effective latch, audible swallowing, and nipple integrity', 'Scheduled feeding times only with no night feeds', 'Formula supplementation at every feed routinely', 'Pain is expected and should not be addressed', 'A', 'Successful breastfeeding assessment includes latch, transfer, and maternal comfort.'],
            ['Health Promotion', 3, 'When planning discharge for a patient starting a low-sodium diet, teaching should include:', 'Reading food labels and avoiding processed meats and canned soups', 'Using salt substitutes without provider guidance in all cases', 'Increasing canned vegetables for convenience', 'Eliminating all fluids from the diet', 'A', 'Sodium restriction education focuses on hidden sources in processed foods.'],
            ['Risk Reduction', 3, 'A patient on bed rest is at risk for deep vein thrombosis. Appropriate nursing care includes:', 'Leg exercises, hydration, and anti-embolism devices as ordered', 'Massaging calf muscles firmly every hour', 'Keeping knee gatch raised continuously without movement', 'Withholding all fluids to prevent edema', 'A', 'DVT prevention includes mobility exercises, hydration, and ordered prophylaxis.'],
            ['Basic Care', 3, 'A patient with urinary retention post-op reports inability to void 8 hours after surgery. The PN should:', 'Assess bladder distention, encourage privacy, and notify the RN', 'Ignore unless 24 hours have passed', 'Force oral fluids only without further assessment', 'Ambulate the patient outdoors immediately alone', 'A', 'Postoperative urinary retention requires assessment and intervention to prevent complications.'],
            ['Adult Health', 3, 'Signs of increased intracranial pressure in an alert patient may include:', 'Worsening headache, vomiting, and changes in level of consciousness', 'Improved orientation as ICP rises', 'Bradycardia with hypertension in late stages only — never early symptoms', 'Pinpoint pupils as the only sign always', 'A', 'Headache, vomiting, and LOC changes may signal rising ICP.'],
            ['Safe Care', 3, 'When delegating a task to unlicensed assistive personnel, the PN must:', 'Ensure the task is within scope, the person is competent, and supervision is appropriate', 'Delegate any task regardless of training', 'Never delegate vital signs on stable patients', 'Assign medication administration to UAP routinely', 'A', 'Delegation requires appropriate task, competence, and supervision per nurse practice act.'],
            // Difficulty 4
            ['Pharmacology', 4, 'A patient with a penicillin allergy is prescribed cephalexin. The PN should:', 'Question the order and notify the RN — cross-reactivity may occur with some cephalosporins', 'Administer immediately without verification', 'Assume all antibiotics are safe if allergic to one', 'Document allergy as inactive without provider review', 'A', 'Cross-sensitivity between penicillins and cephalosporins requires verification before administration.'],
            ['Adult Health', 4, 'A patient with diabetic ketoacidosis presents with Kussmaul respirations. The PN understands this indicates:', 'Compensatory elimination of excess acid via deep, rapid breathing', 'Improved oxygenation without metabolic disturbance', 'Normal sleep breathing pattern', 'Hyperventilation from anxiety only without acid-base change', 'A', 'Kussmaul respirations are a compensatory response to metabolic acidosis.'],
            ['Psychosocial', 4, 'A patient with schizophrenia who hears voices telling them to hurt others requires:', 'Immediate safety assessment, close observation, and notification of the care team', 'Isolation without any communication', 'Agreement that the voices are real to build trust', 'Discharge home alone without evaluation', 'A', 'Command hallucinations with harm ideation are a psychiatric emergency requiring safety measures.'],
            ['Maternal/Child', 4, 'The PN caring for a laboring patient notes late decelerations on the fetal monitor. The appropriate action is:', 'Reposition the patient, apply oxygen if ordered, stop oxytocin if infusing, and notify the RN', 'Document as normal and continue without notification', 'Encourage supine positioning exclusively', 'Ambulate the patient outdoors without monitoring', 'A', 'Late decelerations may indicate uteroplacental insufficiency and require intervention.'],
            ['Safe Care', 4, 'During a fire emergency on the unit, the PN\'s first priority is:', 'Rescue patients in immediate danger, then alarm, contain, and extinguish as trained', 'Finish all medication passes before evacuating', 'Open all windows and doors to improve airflow first', 'Use elevators to move all patients quickly', 'A', 'RACE protocols prioritize rescue and alarm before containment and extinguishment.'],
            ['Health Promotion', 4, 'When counseling a patient about smoking cessation, the most effective approach includes:', 'Setting a quit date, identifying triggers, and discussing nicotine replacement options', 'Scolding the patient for lack of willpower', 'Suggesting cutting down to one cigarette without a plan', 'Avoiding follow-up after initial advice', 'A', 'Evidence-based cessation includes planning, trigger management, and pharmacologic support when appropriate.'],
            ['Risk Reduction', 4, 'A patient receiving a blood transfusion develops flushing, wheezing, and hypotension. The PN should:', 'Stop the transfusion, maintain IV access, monitor, and notify the RN immediately', 'Slow the rate and continue unless fever occurs', 'Administer the next unit to dilute the reaction', 'Document as mild allergy without stopping infusion', 'A', 'Transfusion reactions require stopping the blood product and urgent assessment.'],
            ['Basic Care', 4, 'An older adult with dysphagia after a stroke should receive:', 'Thickened liquids and upright positioning during meals as ordered', 'Thin liquids through a straw without supervision', 'Large boluses of food to finish meals quickly', 'NPO status without alternative nutrition planning indefinitely', 'A', 'Dysphagia management includes texture modification and safe positioning to prevent aspiration.'],
            ['Adult Health', 4, 'A patient post-thyroidectomy reports tingling around the mouth and muscle twitching. The PN suspects:', 'Hypocalcemia from possible parathyroid involvement and notifies the RN', 'Hypernatremia requiring free water only', 'Normal post-op sensation requiring no action', 'Hyperkalemia treated with kayexelate immediately without labs', 'A', 'Perioral tingling and tetany may indicate hypocalcemia after thyroid surgery.'],
            ['Pharmacology', 4, 'The PN is administering insulin lispro at 0730. The patient refuses breakfast. The PN should:', 'Notify the RN — rapid-acting insulin may need adjustment when the patient is NPO', 'Administer the insulin IM for faster effect', 'Give double the dose to compensate for missed meal', 'Skip documentation if the patient refuses', 'A', 'Mealtime insulin requires coordination with intake; hypoglycemia risk increases if food is refused.'],
            // Difficulty 5
            ['Safe Care', 5, 'The PN discovers a coworker is impaired on the job. The priority action is:', 'Ensure patient safety and report to the nurse manager or chain of command per policy', 'Ignore it to maintain workplace friendships', 'Confront publicly on social media', 'Assign the coworker more complex patients to test them', 'A', 'Impaired practice threatens patient safety and must be reported through proper channels.'],
            ['Adult Health', 5, 'A patient with pulmonary embolism may present with:', 'Sudden dyspnea, pleuritic chest pain, tachycardia, and hypoxia', 'Slow respirations with bradycardia only', 'Improved exercise tolerance initially', 'Painless hemoptysis as the sole symptom always', 'A', 'PE classically causes sudden respiratory distress, chest pain, and tachycardia.'],
            ['Psychosocial', 5, 'A patient with major depression expresses a specific suicide plan. The PN should:', 'Stay with the patient, remove harmful items, and initiate emergency protocols', 'Promise confidentiality and avoid telling anyone', 'Leave to complete other assignments first', 'Suggest they sleep it off without assessment', 'A', 'Active suicide plan requires immediate safety intervention and cannot be kept confidential.'],
            ['Maternal/Child', 5, 'A neonate born to a mother with active genital herpes lesions at delivery is at risk for:', 'Neonatal herpes infection requiring isolation and close monitoring per protocol', 'No transmission if breastfeeding is avoided only', 'Immediate immunity without symptoms', 'Only ocular infection with no systemic spread', 'A', 'Neonatal herpes can cause severe systemic infection and requires prompt recognition.'],
            ['Pharmacology', 5, 'A patient receiving heparin infusion has an aPTT of 120 seconds. The PN should:', 'Hold infusion and notify the RN — supratherapeutic aPTT increases bleeding risk', 'Increase rate to reach target faster', 'Administer protamine without provider order independently in all states', 'Ignore unless the patient reports pain', 'A', 'Supratherapeutic aPTT on heparin requires dose adjustment and provider notification.'],
            ['Health Promotion', 5, 'When prioritizing care for four patients, the PN should see first the patient who:', 'Has new onset chest pain and diaphoresis', 'Needs routine discharge paperwork signed', 'Requests help trimming toenails before lunch', 'Asks for a second blanket while watching television', 'A', 'Airway, breathing, and circulation problems take priority over comfort or routine tasks.'],
            ['Risk Reduction', 5, 'A patient with a central venous catheter develops chills and fever during an infusion. The PN suspects:', 'Catheter-related bloodstream infection and stops infusion per protocol while notifying the RN', 'Normal inflammatory response requiring no action', 'Need to increase infusion rate to flush bacteria', 'Removal of the catheter by the PN alone without orders always', 'A', 'Infusion-related fever with chills may indicate line infection and requires assessment and notification.'],
            ['Basic Care', 5, 'An unconscious patient with increased intracranial pressure should be positioned:', 'Head midline with head of bed elevated 30 degrees unless contraindicated', 'Flat with legs elevated above heart level routinely', 'Prone with head turned sharply to one side always', 'Trendelenburg to improve cerebral perfusion in all cases', 'A', 'HOB elevation with neutral head alignment helps reduce venous congestion and ICP.'],
            ['Adult Health', 5, 'A patient with acute pancreatitis should be monitored for complications including:', 'Hypovolemic shock, respiratory distress, and infection', 'Improved glucose control without fluid shifts', 'Hyperkalemia as the earliest life-threatening issue always', 'No pain management needs due to autodigestion pause', 'A', 'Pancreatitis can cause third-spacing, ARDS, and sepsis requiring close monitoring.'],
            ['Safe Care', 5, 'The PN identifies a sentinel event near-miss on the unit. The appropriate response is:', 'Report through event reporting systems to improve systems of care', 'Hide the incident to protect the unit\'s reputation', 'Blame the patient for noncompliance publicly', 'Document only in personal notes without institutional reporting', 'A', 'Near-miss reporting supports patient safety and quality improvement initiatives.'],
        ];
    }
}
