<?php

$mk = fn (string $title, string $scenario, string $correct, string $explanation) => compact('title', 'scenario', 'correct', 'explanation');

return [
    'triage-start' => [
        $mk('Self-extricated driver', 'Adult walking from vehicle, alert, complaining of wrist pain only.', 'minor', 'Ambulatory patients are tagged Green (Minor) in START.'),
        $mk('Pulseless after positioning', 'Adult pinned in driver seat, apneic after airway positioning, no carotid pulse.', 'expectant', 'Apneic without perfusion after positioning → Expectant (Black) when resources are limited.'),
        $mk('Tachypnea with perfusion', 'Non-ambulatory adult, RR 34/min, follows commands, strong radial pulse.', 'immediate', 'Respirations over 30/min place the patient in Immediate (Red) category.'),
        $mk('Altered but breathing', 'Non-ambulatory, RR 18, confused and unable to obey commands, pulse present.', 'delayed', 'Breathing under 30 with perfusion but unable to obey commands → Delayed (Yellow).'),
        $mk('Walking with open fracture', 'Patient ambulatory to triage area with open tib-fib fracture and active bleeding controlled.', 'minor', 'If the patient can walk to you, START assigns Green first regardless of significant extremity injury.'),
    ],
    'triage-jumpstart' => [
        $mk('Ambulatory child', '11-year-old walking from bus crash, crying, forearm deformity, RR 22.', 'minor', 'Ambulatory pediatric patients → Green (Minor) in JumpSTART.'),
        $mk('Apneic infant', '8-month-old apneic after positioning, no brachial pulse.', 'expectant', 'Apneic without pulses after positioning → Expectant unless mass resuscitation is available.'),
        $mk('Apneic with brachial pulse', '3-year-old apneic after jaw thrust, brachial pulse present.', 'immediate', 'Apneic with perfusion → Immediate (Red), ventilate and reassess.'),
        $mk('Pediatric tachypnea', 'Non-ambulatory 5-year-old, RR 52/min, withdraws to painful stimulus.', 'immediate', 'Respiratory rate over 45/min → Immediate (Red) in JumpSTART.'),
        $mk('Stable pediatric', 'Non-ambulatory 10-year-old, RR 24, obeys commands, cap refill 2 sec.', 'delayed', 'Breathing under 45, perfusion present, obeys commands → Delayed (Yellow).'),
    ],
    'triage-salt' => [
        $mk('Hemorrhage control applied', 'Conscious patient with tourniquet on forearm placed 2 minutes ago, talking.', 'lifesaving', 'SALT: lifesaving interventions already started → urgent treatment/transport.'),
        $mk('Self-evacuating patient', 'Alert patient leaving venue on own, minor abrasions, no major bleeding.', 'minor', 'Ambulatory without immediate life threat → Minor category in SALT sort.'),
        $mk('Warm zone hold', 'Patient in warm zone during active threat, no immediate life threat identified yet.', 'assess', 'SALT begins with Sort/Assess before movement when threat persists.'),
        $mk('Penetrating chest wound', 'Conscious patient with sucking chest wound, diminished breath sounds.', 'lifesaving', 'Airway/breathing compromise requiring immediate intervention → lifesaving in SALT.'),
        $mk('Traumatic arrest', 'Blunt trauma with decapitation in cold zone triage area.', 'expectant', 'Incompatible with life → Expectant/deceased category.'),
    ],
    'triage-mci' => [
        [
            'title' => 'School bus rollover',
            'scenario' => 'One ambulance remaining. Tap the patient who should go next.',
            'patients' => [
                ['id' => 'airway', 'label' => 'Patient A', 'detail' => 'Unresponsive, gurgling respirations, pale'],
                ['id' => 'femur', 'label' => 'Patient B', 'detail' => 'Alert, open femur fracture, controlled bleeding'],
                ['id' => 'walking', 'label' => 'Patient C', 'detail' => 'Ambulatory, minor abrasions'],
                ['id' => 'pulseless', 'label' => 'Patient D', 'detail' => 'Apneic, no pulse after airway maneuver'],
            ],
            'correct' => 'airway',
            'explanation' => 'Airway compromise with altered perfusion is highest priority among salvageable patients.',
        ],
        [
            'title' => 'Apartment fire',
            'scenario' => 'Limited crews. Who gets the next transport?',
            'patients' => [
                ['id' => 'smoke', 'label' => 'Patient 1', 'detail' => 'Confused, soot around mouth, RR 30'],
                ['id' => 'burns', 'label' => 'Patient 2', 'detail' => 'Partial-thickness burns 18% TBSA, alert'],
                ['id' => 'sprain', 'label' => 'Patient 3', 'detail' => 'Ankle injury, ambulatory'],
                ['id' => 'hypotensive', 'label' => 'Patient 4', 'detail' => 'Crush injury, BP 78/48, tachycardic'],
            ],
            'correct' => 'hypotensive',
            'explanation' => 'Hypotensive crush injury outranks stable burns or minor injuries.',
        ],
        [
            'title' => 'Concert stampede',
            'scenario' => 'Two units left. Choose highest priority.',
            'patients' => [
                ['id' => 'pregnant', 'label' => 'Patient A', 'detail' => '38 weeks pregnant, contractions q4 min'],
                ['id' => 'asthma', 'label' => 'Patient B', 'detail' => 'RR 34, SpO₂ 86%, speaking words only'],
                ['id' => 'laceration', 'label' => 'Patient C', 'detail' => 'Forearm laceration, bleeding controlled'],
                ['id' => 'anxiety', 'label' => 'Patient D', 'detail' => 'Hyperventilating, vitals stable'],
            ],
            'correct' => 'asthma',
            'explanation' => 'Hypoxic respiratory distress is immediate priority over stable laceration or anxiety.',
        ],
        [
            'title' => 'Industrial explosion',
            'scenario' => 'Triage officer — next transport?',
            'patients' => [
                ['id' => 'amputation', 'label' => 'Patient A', 'detail' => 'Partial hand amputation, tourniquet applied, alert'],
                ['id' => 'agonal', 'label' => 'Patient B', 'detail' => 'Unresponsive, agonal respirations'],
                ['id' => 'geriatric', 'label' => 'Patient C', 'detail' => 'Hip pain, ambulatory with assistance'],
                ['id' => 'obvious_death', 'label' => 'Patient D', 'detail' => 'Obvious death, incompatible with life'],
            ],
            'correct' => 'agonal',
            'explanation' => 'Potentially salvageable airway emergency before stable amputation or minor geriatric injury.',
        ],
        [
            'title' => 'Multi-vehicle collision',
            'scenario' => 'One ambulance available. Who goes first?',
            'patients' => [
                ['id' => 'entrapped', 'label' => 'Patient A', 'detail' => 'Entrapped, alert, pelvis pain, vitals stable'],
                ['id' => 'chest_pain', 'label' => 'Patient B', 'detail' => 'Diaphoretic, crushing chest pain, BP 88/60'],
                ['id' => 'minor', 'label' => 'Patient C', 'detail' => 'Walking wounded with scalp lac'],
                ['id' => 'airway', 'label' => 'Patient D', 'detail' => 'Altered, stridor, SpO₂ 84%'],
            ],
            'correct' => 'airway',
            'explanation' => 'Airway compromise with hypoxia is the highest immediate priority.',
        ],
    ],
    'gcs-scenarios' => [
        ['title' => 'Assault — combative', 'scenario' => 'Opens eyes to voice, confused conversation, withdraws from pain.', 'eye' => 3, 'verbal' => 4, 'motor' => 4, 'explanation' => 'E3 V4 M4 = GCS 11.'],
        ['title' => 'Severe TBI', 'scenario' => 'Opens eyes to pain only, incomprehensible sounds, extension to pain.', 'eye' => 2, 'verbal' => 2, 'motor' => 2, 'explanation' => 'E2 V2 M2 = GCS 6 — severe injury.'],
        ['title' => 'Minor head bump', 'scenario' => 'Eyes open spontaneously, oriented, obeys commands.', 'eye' => 4, 'verbal' => 5, 'motor' => 6, 'explanation' => 'E4 V5 M6 = GCS 15.'],
        ['title' => 'Epidural hematoma', 'scenario' => 'Eyes to speech, inappropriate words, abnormal flexion to pain.', 'eye' => 3, 'verbal' => 3, 'motor' => 3, 'explanation' => 'E3 V3 M3 = GCS 9 — deteriorating head injury.'],
        ['title' => 'Intoxication with trauma', 'scenario' => 'Eyes open spontaneously, confused, localizes pain.', 'eye' => 4, 'verbal' => 4, 'motor' => 5, 'explanation' => 'E4 V4 M5 = GCS 13 — document intoxication and trauma separately.'],
    ],
    'burn-scoring' => [
        [
            'title' => 'Kitchen scald — torso',
            'scenario' => 'Boiling water spilled on anterior chest and abdomen. Partial-thickness with blisters.',
            'correct_regions' => ['anterior:chest', 'anterior:abdomen'],
            'correct_percent' => '36',
            'percent_options' => ['18' => '18% TBSA', '27' => '27% TBSA', '36' => '36% TBSA', '45' => '45% TBSA'],
            'explanation' => 'Anterior chest 18% + anterior abdomen 18% ≈ 36% TBSA.',
        ],
        [
            'title' => 'Chemical splash — both arms',
            'scenario' => 'Industrial acid splash to entire anterior surface of both arms.',
            'correct_regions' => ['anterior:arm_l', 'anterior:arm_r'],
            'correct_percent' => '18',
            'percent_options' => ['9' => '9% TBSA', '18' => '18% TBSA', '27' => '27% TBSA', '36' => '36% TBSA'],
            'explanation' => 'Each entire arm ≈ 9% TBSA → about 18% total.',
        ],
        [
            'title' => 'Sunburn — face only',
            'scenario' => 'Second-degree sunburn to face and scalp only, anterior view.',
            'correct_regions' => ['anterior:head'],
            'correct_percent' => '9',
            'percent_options' => ['4' => '4.5% TBSA', '9' => '9% TBSA', '18' => '18% TBSA', '27' => '27% TBSA'],
            'explanation' => 'Head (including face) ≈ 9% TBSA by rule of nines.',
        ],
        [
            'title' => 'Structure fire — anterior',
            'scenario' => 'Flash burn to face, chest, and both anterior legs from waist down.',
            'correct_regions' => ['anterior:head', 'anterior:chest', 'anterior:leg_l', 'anterior:leg_r'],
            'correct_percent' => '45',
            'percent_options' => ['27' => '27% TBSA', '36' => '36% TBSA', '45' => '45% TBSA', '54' => '54% TBSA'],
            'explanation' => 'Head 9% + chest 18% + both legs 18% ≈ 45% TBSA.',
        ],
        [
            'title' => 'Clothing ignition — back',
            'scenario' => 'Patient burned on entire posterior trunk after clothing caught fire. Anterior uninjured.',
            'correct_regions' => ['posterior:back'],
            'correct_percent' => '18',
            'percent_options' => ['9' => '9% TBSA', '18' => '18% TBSA', '27' => '27% TBSA', '36' => '36% TBSA'],
            'explanation' => 'Entire back ≈ 18% TBSA.',
        ],
    ],
    'stroke-scale' => [
        [
            'title' => 'Sudden hemiparesis',
            'scenario' => '62-year-old with sudden right facial droop, right arm drift, slurred speech — 15 minutes ago.',
            'fast' => ['face' => true, 'arms' => true, 'speech' => true],
            'correct' => 'transport',
            'explanation' => 'Positive FAST within window → stroke center transport and alert.',
        ],
        [
            'title' => 'Isolated arm weakness',
            'scenario' => 'Patient reports left arm numbness on waking, face symmetric, speech clear.',
            'fast' => ['face' => false, 'arms' => true, 'speech' => false],
            'correct' => 'transport',
            'explanation' => 'Focal neuro deficit still warrants stroke evaluation and transport.',
        ],
        [
            'title' => 'Panic attack',
            'scenario' => 'Hyperventilating after job interview, symmetric face, equal grip strength, clear speech.',
            'fast' => ['face' => false, 'arms' => false, 'speech' => false],
            'correct' => 'evaluate',
            'explanation' => 'Negative FAST — evaluate other causes but do not ignore atypical stroke symptoms.',
        ],
        [
            'title' => 'Fall with dysarthria',
            'scenario' => 'Slurred speech after fall, unilateral facial droop, no arm drift noted.',
            'fast' => ['face' => true, 'arms' => false, 'speech' => true],
            'correct' => 'transport',
            'explanation' => 'Any positive FAST component with acute onset → stroke protocol.',
        ],
        [
            'title' => 'Wake-up stroke',
            'scenario' => 'Found with left-sided weakness at breakfast, last normal at bedtime.',
            'fast' => ['face' => true, 'arms' => true, 'speech' => true],
            'correct' => 'transport',
            'explanation' => 'Document last known well; transport for stroke evaluation.',
        ],
    ],
    'vital-signs' => [
        [
            'title' => 'Croup presentation',
            'scenario' => '3-year-old with barking cough, stridor at rest, and retractions.',
            'vitals' => ['bp' => '—', 'pulse' => '142', 'rr' => '38', 'spo2' => '90%', 'temp' => '38.0°C', 'glucose' => '—'],
            'correct' => 'oxygen',
            'explanation' => 'Hypoxia and upper airway distress → oxygen and rapid transport.',
        ],
        [
            'title' => 'STEMI with shock',
            'scenario' => '68-year-old diaphoretic with crushing substernal chest pain.',
            'vitals' => ['bp' => '84/52', 'pulse' => '112', 'rr' => '24', 'spo2' => '91%', 'temp' => '98.4°F', 'glucose' => '118'],
            'correct' => 'oxygen_iv',
            'explanation' => 'Hypotension + chest pain → oxygen, IV, ECG, rapid transport.',
        ],
        [
            'title' => 'Isolated wrist injury',
            'scenario' => '28-year-old fell on outstretched hand, pain over distal radius.',
            'vitals' => ['bp' => '118/74', 'pulse' => '72', 'rr' => '16', 'spo2' => '99%', 'temp' => '98.6°F', 'glucose' => '—'],
            'correct' => 'comfort_transport',
            'explanation' => 'Stable vitals — splint, ice, transport per patient preference/protocol.',
        ],
        [
            'title' => 'UTI with sepsis',
            'scenario' => 'Elderly female with fever, flank pain, and increasing confusion.',
            'vitals' => ['bp' => '88/50', 'pulse' => '118', 'rr' => '28', 'spo2' => '93%', 'temp' => '39.8°C', 'glucose' => '142'],
            'correct' => 'oxygen_iv',
            'explanation' => 'Fever, hypotension, tachycardia, AMS → high-risk sepsis pathway.',
        ],
        [
            'title' => 'DKA presentation',
            'scenario' => 'Known type 1 diabetic with polyuria, abdominal pain, and Kussmaul respirations.',
            'vitals' => ['bp' => '128/78', 'pulse' => '108', 'rr' => '28', 'spo2' => '97%', 'temp' => '98.2°F', 'glucose' => '486'],
            'correct' => 'transport_iv',
            'explanation' => 'Significant hyperglycemia with symptoms → transport, IV, monitor.',
        ],
    ],
    'pharma-contraindications' => [
        [
            'title' => 'Nitroglycerin — recent PDE-5 use',
            'drug' => 'Nitroglycerin',
            'prompt' => '48-year-old with chest pain. Patient took tadalafil (Cialis) 12 hours ago. BP 118/74. Safe to assist with nitroglycerin?',
            'correct' => 'no',
            'explanation' => 'Recent PDE-5 inhibitor use (within 24–48 hours per protocol) is a contraindication to nitroglycerin due to severe hypotension risk.',
        ],
        [
            'title' => 'Oral glucose — unresponsive patient',
            'drug' => 'Oral Glucose',
            'prompt' => 'Diabetic found unresponsive. Glucose 42 mg/dL. Patient cannot protect airway. Safe to give oral glucose?',
            'correct' => 'no',
            'explanation' => 'Oral glucose requires the ability to swallow and protect the airway. Use IV glucose or IM glucagon per protocol when the patient cannot swallow safely.',
        ],
        [
            'title' => 'Aspirin — no contraindications',
            'drug' => 'Aspirin',
            'prompt' => '62-year-old with substernal pressure, no aspirin allergy, no active GI bleed. Safe to assist with aspirin?',
            'correct' => 'yes',
            'explanation' => 'Aspirin is indicated for suspected acute coronary syndrome when the patient has no allergy or active bleeding contraindication.',
        ],
        [
            'title' => 'Epinephrine — no anaphylaxis',
            'drug' => 'Epinephrine (auto-injector)',
            'prompt' => 'Patient with isolated urticaria, no airway swelling, BP 122/78, SpO₂ 98%. Safe to give epinephrine auto-injector?',
            'correct' => 'no',
            'explanation' => 'Epinephrine is reserved for anaphylaxis. Isolated urticaria without airway compromise does not warrant epinephrine per protocol.',
        ],
        [
            'title' => 'Activated charcoal — petroleum ingestion',
            'drug' => 'Activated Charcoal',
            'prompt' => 'Child ingested lamp oil 15 minutes ago. Awake, coughing mildly. Safe to give activated charcoal?',
            'correct' => 'no',
            'explanation' => 'Activated charcoal is contraindicated for hydrocarbon ingestions — aspiration risk and poor adsorption.',
        ],
    ],
    'pharma-assist' => [
        [
            'title' => 'Anaphylaxis — epinephrine pen',
            'drug' => 'Epinephrine (auto-injector)',
            'prompt' => '24-year-old with hives, lip swelling, wheezing, and BP 92/58 after peanut exposure. Patient carries prescribed epinephrine. Should you assist?',
            'correct' => 'yes',
            'explanation' => 'Anaphylaxis with airway compromise and hypotension warrants immediate epinephrine IM per protocol.',
        ],
        [
            'title' => 'Chest pain — hypotensive',
            'drug' => 'Nitroglycerin',
            'prompt' => '70-year-old with crushing chest pain. BP 78/48, pale and diaphoretic. Has prescribed nitroglycerin. Should you assist?',
            'correct' => 'no',
            'explanation' => 'Systolic BP below protocol threshold is a contraindication to nitroglycerin. Focus on oxygen, IV access, and rapid transport.',
        ],
        [
            'title' => 'Alert hypoglycemia',
            'drug' => 'Oral Glucose',
            'prompt' => '52-year-old diabetic, glucose 58 mg/dL, anxious and tremulous, awake and able to swallow. Should you assist with oral glucose?',
            'correct' => 'yes',
            'explanation' => 'Conscious patients who can swallow and protect their airway should receive oral glucose for symptomatic hypoglycemia.',
        ],
        [
            'title' => 'Opioid toxidrome',
            'drug' => 'Naloxone (Narcan)',
            'prompt' => '28-year-old unresponsive. RR 4/min, pinpoint pupils, track marks. SpO₂ 80%. Should you assist with naloxone?',
            'correct' => 'yes',
            'explanation' => 'Opioid toxidrome with respiratory depression warrants naloxone per protocol along with airway support and oxygen.',
        ],
        [
            'title' => 'Mild urticaria',
            'drug' => 'Diphenhydramine',
            'prompt' => '21-year-old with hives after new medication. No airway swelling, no wheezing, BP 120/76. Should you assist with diphenhydramine?',
            'correct' => 'yes',
            'explanation' => 'Isolated urticaria without anaphylaxis may be treated with diphenhydramine per protocol while monitoring for progression.',
        ],
    ],
    'pharma-matching' => [
        [
            'title' => 'Symptomatic hypoglycemia',
            'prompt' => 'Diaphoretic, tremulous, glucose 49 mg/dL. Patient is awake and can swallow. Which medication is most appropriate?',
            'options' => [
                'oral_glucose' => 'Oral glucose',
                'naloxone' => 'Naloxone (Narcan)',
                'nitroglycerin' => 'Nitroglycerin',
                'albuterol' => 'Albuterol',
            ],
            'correct' => 'oral_glucose',
            'explanation' => 'Altered mental status with documented hypoglycemia → oral glucose when the patient can swallow safely.',
        ],
        [
            'title' => 'Asthma exacerbation',
            'prompt' => 'Audible wheezes, accessory muscle use, SpO₂ 89%. Patient has prescribed MDI. Which medication should you assist with?',
            'options' => [
                'albuterol' => 'Albuterol (MDI)',
                'epinephrine' => 'Epinephrine auto-injector',
                'aspirin' => 'Aspirin',
                'diphenhydramine' => 'Diphenhydramine',
            ],
            'correct' => 'albuterol',
            'explanation' => 'Bronchospasm with wheezing is treated with a bronchodilator — assist with albuterol per protocol.',
        ],
        [
            'title' => 'Suspected MI',
            'prompt' => '58-year-old with substernal pressure radiating to left arm. No aspirin allergy. BP 128/80. Which medication is typically given first?',
            'options' => [
                'aspirin' => 'Aspirin',
                'naloxone' => 'Naloxone',
                'oral_glucose' => 'Oral glucose',
                'activated_charcoal' => 'Activated charcoal',
            ],
            'correct' => 'aspirin',
            'explanation' => 'Aspirin is indicated early for suspected MI when no allergy or active bleeding is present.',
        ],
        [
            'title' => 'Opioid overdose',
            'prompt' => 'Unresponsive female. Pinpoint pupils, RR 6/min, shallow breathing. Which medication matches this presentation?',
            'options' => [
                'naloxone' => 'Naloxone (Narcan)',
                'nitroglycerin' => 'Nitroglycerin',
                'diphenhydramine' => 'Diphenhydramine',
                'oral_glucose' => 'Oral glucose',
            ],
            'correct' => 'naloxone',
            'explanation' => 'Pinpoint pupils + respiratory depression suggests opioid overdose → naloxone per protocol.',
        ],
        [
            'title' => 'Hypoxia after trauma',
            'prompt' => 'SpO₂ 86% on room air after MVC. Increased work of breathing. Which intervention is most appropriate?',
            'options' => [
                'oxygen' => 'Oxygen',
                'oral_glucose' => 'Oral glucose',
                'activated_charcoal' => 'Activated charcoal',
                'aspirin' => 'Aspirin',
            ],
            'correct' => 'oxygen',
            'explanation' => 'SpO₂ below protocol threshold requires supplemental oxygen.',
        ],
    ],
    'pharma-outcomes' => [
        [
            'title' => 'After albuterol',
            'prompt' => 'You assisted a wheezing patient with 2 puffs of albuterol MDI. Re-assessment in 5 minutes. Which finding best indicates the medication is working?',
            'options' => [
                'wheezing_decreased' => 'Wheezing decreased and SpO₂ improved',
                'bp_drop' => 'Blood pressure dropped to 68/40',
                'pupils_pinpoint' => 'Pupils became pinpoint',
                'glucose_low' => 'Glucose fell to 38 mg/dL',
            ],
            'correct' => 'wheezing_decreased',
            'explanation' => 'Effective bronchodilation should reduce wheezing and improve oxygenation.',
        ],
        [
            'title' => 'After nitroglycerin',
            'prompt' => 'Chest pain patient received nitroglycerin 0.4 mg SL per protocol. BP remains above 100 systolic. What outcome suggests it helped?',
            'options' => [
                'pain_improved' => 'Chest pain intensity decreased',
                'pain_worse' => 'Chest pain became crushing with new ST elevation',
                'anaphylaxis' => 'Developed hives and wheezing',
                'hypoglycemia' => 'Became confused with glucose 52',
            ],
            'correct' => 'pain_improved',
            'explanation' => 'Nitroglycerin vasodilation often reduces myocardial ischemic chest pain when appropriately indicated.',
        ],
        [
            'title' => 'After oral glucose',
            'prompt' => 'Hypoglycemic patient received oral glucose gel. Repeat glucose in 10 minutes. What would indicate improvement?',
            'options' => [
                'ams_resolved' => 'Mental status returned to normal and glucose rose',
                'resp_depression' => 'Respiratory rate fell to 4/min',
                'hives' => 'Generalized hives appeared',
                'chest_pain' => 'Crushing chest pain developed',
            ],
            'correct' => 'ams_resolved',
            'explanation' => 'Successful hypoglycemia treatment restores mental status and raises blood glucose.',
        ],
        [
            'title' => 'After naloxone',
            'prompt' => 'Opioid overdose patient received naloxone IN. Which change suggests naloxone is effective?',
            'options' => [
                'rr_increased' => 'Respiratory rate and mental status improved',
                'spo2_worse' => 'SpO₂ dropped to 68% without other cause',
                'anaphylaxis' => 'Facial swelling and stridor developed',
                'hypotension' => 'BP fell to 76/44',
            ],
            'correct' => 'rr_increased',
            'explanation' => 'Naloxone reverses opioid-induced respiratory depression — expect improved RR and alertness.',
        ],
        [
            'title' => 'After oxygen',
            'prompt' => 'Patient with SpO₂ 87% placed on high-flow oxygen via non-rebreather mask. What finding shows oxygen is improving the patient?',
            'options' => [
                'spo2_up' => 'SpO₂ increased to 95% or higher',
                'glucose_up' => 'Blood glucose increased to 220',
                'pain_gone' => 'All chest pain resolved without other treatment',
                'pupils_dilated' => 'Pupils became fully dilated and fixed',
            ],
            'correct' => 'spo2_up',
            'explanation' => 'Supplemental oxygen should raise SpO₂ in hypoxic patients when the airway and delivery device are appropriate.',
        ],
    ],
    'pharma-dosage' => [
        [
            'title' => 'Epinephrine auto-injector — adult',
            'prompt' => 'Adult patient in anaphylaxis. You are assisting with a prescribed epinephrine auto-injector. What is the standard adult dose?',
            'options' => [
                '0.3mg' => '0.3 mg IM',
                '0.15mg' => '0.15 mg IM',
                '1mg' => '1 mg IV push',
                '324mg' => '324 mg oral',
            ],
            'correct' => '0.3mg',
            'explanation' => 'Adult epinephrine auto-injector delivers 0.3 mg IM (typically 0.3 mg/0.3 mL). Pediatric auto-injectors deliver 0.15 mg.',
        ],
        [
            'title' => 'Albuterol MDI',
            'prompt' => 'Patient with bronchospasm has a prescribed metered-dose inhaler and spacer. How many puffs are typically assisted per dose?',
            'options' => [
                '2_puffs' => '2 puffs',
                '10_puffs' => '10 puffs at once',
                '1_puff' => '1 puff only, never repeat',
                '0.4mg' => '0.4 mg sublingual',
            ],
            'correct' => '2_puffs',
            'explanation' => 'Standard MDI assist is 2 puffs, reassess, and repeat per protocol if wheezing persists.',
        ],
        [
            'title' => 'Nitroglycerin SL',
            'prompt' => 'Chest pain patient meets criteria for nitroglycerin. BP adequate. What is the dose per administration?',
            'options' => [
                '0.4mg' => '0.4 mg sublingual',
                '0.3mg' => '0.3 mg IM',
                '2mg' => '2 mg intranasal',
                '324mg' => '324 mg oral',
            ],
            'correct' => '0.4mg',
            'explanation' => 'Nitroglycerin is given 0.4 mg SL (tablet or spray) per dose, with protocol limits on total doses and reassessment between doses.',
        ],
        [
            'title' => 'Aspirin — ACS',
            'prompt' => 'Suspected acute coronary syndrome. No aspirin allergy or active bleeding. What is the standard aspirin dose?',
            'options' => [
                '324mg' => '324 mg chewable',
                '81mg' => '81 mg chewable',
                '650mg' => '650 mg swallowed whole only',
                '0.4mg' => '0.4 mg sublingual',
            ],
            'correct' => '324mg',
            'explanation' => 'EMT-Basic protocol typically uses 324 mg chewable aspirin (four 81 mg tablets or equivalent) for suspected MI.',
        ],
        [
            'title' => 'Oral glucose gel',
            'prompt' => 'Symptomatic hypoglycemia in an alert patient who can swallow. What is a typical oral glucose dose?',
            'options' => [
                '15g' => '15 g oral glucose gel/tablets',
                '324mg' => '324 mg chewable',
                '0.4mg' => '0.4 mg sublingual',
                '50g' => '50 g activated charcoal',
            ],
            'correct' => '15g',
            'explanation' => 'Oral glucose is typically given as 15 g, reassess, and repeat per protocol until mental status and glucose improve.',
        ],
    ],
];
