<?php

return [
    [
        'title' => 'Traumatic arrest — ROSC',
        'scenario' => '33-year-old motorcycle vs guardrail, brief downtime, ROSC after field resuscitation.',
        'detail' => 'No helmet. GCS 3 on arrival. Bilateral femur fractures suspected. Massive transfusion protocol at receiving facility.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Bystander reports high-speed motorcycle crash.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Unknown downtime; CPR by first responder ~4 minutes.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Initial rhythm PEA, ROSC after epinephrine and fluid bolus.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'GCS 6 post-ROSC, bilateral femur deformity, scalp avulsion.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'BP 82/48, pulse 124, RR assisted 16, SpO₂ 92%.', 'section' => 'O'],
            ['id' => 's6', 'text' => 'Traumatic arrest with ROSC — multisystem trauma.', 'section' => 'A'],
            ['id' => 's7', 'text' => 'High risk of re-arrest and hemorrhagic shock.', 'section' => 'A'],
            ['id' => 's8', 'text' => 'Permissive hypotension per protocol, TXA if indicated, rapid trauma center transport.', 'section' => 'P'],
            ['id' => 's9', 'text' => 'Pelvic binder applied for mechanism.', 'section' => 'O'],
            ['id' => 's10', 'text' => 'ETT placed after ROSC, confirmed bilateral breath sounds.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Motorcycle color is black.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Crash scene on highway exit 14.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'News helicopter circled area.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Patient\'s wallet found 10 feet away.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Road crew patching potholes nearby.', 'section' => 'X'],
            ['id' => 'x6', 'text' => 'Weather dry and clear.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Obstetric emergency — shoulder dystocia resolved',
        'scenario' => '28-year-old delivered infant after difficult shoulder dystocia, now bleeding heavily.',
        'detail' => 'Midwife resolved dystocia with McRoberts. Infant crying. Mother pale, estimated blood loss >1000 mL.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Midwife reports shoulder dystocia requiring maneuvers.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Patient feels faint and reports heavy bleeding.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Infant crying, Apgar not yet assigned.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Mother pale, diaphoretic, uterus boggy on palpation.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'BP 88/54, pulse 128, RR 22, SpO₂ 96%.', 'section' => 'O'],
            ['id' => 's6', 'text' => 'Postpartum hemorrhage after complicated delivery.', 'section' => 'A'],
            ['id' => 's7', 'text' => 'Risk of hypovolemic shock.', 'section' => 'A'],
            ['id' => 's8', 'text' => 'Fundal massage, IV access, fluid resuscitation, oxytocin per protocol, transport mother and neonate.', 'section' => 'P'],
            ['id' => 's9', 'text' => 'Perineal laceration with ongoing bleeding.', 'section' => 'O'],
            ['id' => 's10', 'text' => 'Placenta delivered intact per midwife.', 'section' => 'S'],
            ['id' => 'x1', 'text' => 'Birth plan was laminated on fridge.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Doula en route.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Birthing ball in corner.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Scented candles extinguished.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Playlist stopped during emergency.', 'section' => 'X'],
            ['id' => 'x6', 'text' => 'Husband fainted briefly — uninjured.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Tension pneumothorax post-ventilation',
        'scenario' => '48-year-old intubated trauma patient develops sudden hypoxia and tracheal deviation.',
        'detail' => 'MVC 1 hour ago. Positive pressure ventilation in progress. Previously stable vitals.',
        'sentences' => [
            ['id' => 's1', 'text' => 'No new history from patient — sedated and paralyzed.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Mechanism: high-speed frontal impact per crew report.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Sudden desaturation to 82%, absent breath sounds left.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Trachea deviated right, JVD present, hypotension.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'BP 74/40, pulse 134, EtCO₂ dropped abruptly.', 'section' => 'O'],
            ['id' => 's6', 'text' => 'Tension pneumothorax on ventilated trauma patient.', 'section' => 'A'],
            ['id' => 's7', 'text' => 'Obstructive shock physiology.', 'section' => 'A'],
            ['id' => 's8', 'text' => 'Needle decompression left chest, reassess, continue rapid transport.', 'section' => 'P'],
            ['id' => 's9', 'text' => 'Needle decompression performed 2nd ICS midclavicular — rush of air.', 'section' => 'O'],
            ['id' => 's10', 'text' => 'SpO₂ improved to 94% post-decompression.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Ambulance manufacturer is Ford.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Driver ate breakfast at station.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Traffic light timing unknown.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Patient\'s shoes were Nike.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Radio traffic was heavy.', 'section' => 'X'],
            ['id' => 'x6', 'text' => 'Hospital charge nurse name unknown.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Pediatric septic shock',
        'scenario' => '4-year-old with fever, rash, and altered mental status progressing over 12 hours.',
        'detail' => 'Non-blanching purpuric rash on legs. Parents report decreased urine output. No meningitis vaccine reaction hx.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Parents report fever and lethargy since yesterday.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Child less responsive today, not drinking.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Non-blanching purpuric rash lower extremities.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Cap refill 5 sec, mottled skin, fontanelle not applicable.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'BP 68/40, pulse 168, RR 32, temp 39.8°C, SpO₂ 93%.', 'section' => 'O'],
            ['id' => 's6', 'text' => 'Pediatric septic shock — meningococcemia in differential.', 'section' => 'A'],
            ['id' => 's7', 'text' => 'High mortality without rapid intervention.', 'section' => 'A'],
            ['id' => 's8', 'text' => 'IV/IO access, fluid bolus per broselow, oxygen, isolation precautions, PICU transport.', 'section' => 'P'],
            ['id' => 's9', 'text' => 'GCS 10 (E2 V3 M5).', 'section' => 'O'],
            ['id' => 's10', 'text' => 'Parents consent to treatment.', 'section' => 'S'],
            ['id' => 'x1', 'text' => 'Daycare closure unrelated.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Child favorite color is purple.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Stuffed bunny in ambulance.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Pediatrician office closed weekends.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Sibling stayed with neighbor.', 'section' => 'X'],
            ['id' => 'x6', 'text' => 'TV cartoon paused on screen.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Complex psychiatric — excited delirium',
        'scenario' => '35-year-old male agitated, hyperthermic, with superhuman strength after stimulant use.',
        'detail' => 'Police on scene. Taser deployed x1 prior to EMS. Combativeness continuing. Core temp estimated very high.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Police report bizarre behavior and stimulant paraphernalia.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Bystanders say patient was running into traffic.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Profound agitation, diaphoresis, skin hot to touch.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Pulse 160, RR 28, BP 188/110, SpO₂ 97%.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'GCS fluctuating 12–14, pupils dilated.', 'section' => 'O'],
            ['id' => 's6', 'text' => 'Excited delirium syndrome — stimulant toxidrome.', 'section' => 'A'],
            ['id' => 's7', 'text' => 'Risk of sudden death and hyperthermia.', 'section' => 'A'],
            ['id' => 's8', 'text' => 'Request law enforcement assistance, sedation per protocol, cooling, rapid transport.', 'section' => 'P'],
            ['id' => 's9', 'text' => 'Four-point restraint applied for safety after sedation.', 'section' => 'O'],
            ['id' => 's10', 'text' => 'No obvious traumatic injuries after restraint.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Officer badge number recorded.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Incident on Main Street.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Store window unbroken.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Patient wore red sneakers.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Crowd gathered at corner.', 'section' => 'X'],
            ['id' => 'x6', 'text' => 'News crew not present.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'High-voltage electrical injury',
        'scenario' => '40-year-old lineman with contact burn and cardiac dysrhythmia after arc flash.',
        'detail' => 'Coworkers witnessed arc. Patient had brief LOC. Entry burns both hands, exit through boots melted.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Coworker reports high-voltage arc flash during repair.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Patient does not recall brief unconscious period.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Full-thickness burns bilateral palms, exit wounds feet.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Monitor: frequent PVCs, BP 102/68, pulse 108 irregular.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'SpO₂ 96%, RR 18, patient alert but anxious.', 'section' => 'O'],
            ['id' => 's6', 'text' => 'High-voltage electrical injury with arrhythmia risk.', 'section' => 'A'],
            ['id' => 's7', 'text' => 'Potential deep tissue and multisystem damage.', 'section' => 'A'],
            ['id' => 's8', 'text' => 'Cardiac monitoring, IV access, burn care, trauma center transport.', 'section' => 'P'],
            ['id' => 's9', 'text' => 'C-spine precautions maintained for fall from bucket.', 'section' => 'O'],
            ['id' => 's10', 'text' => 'Myoglobinuria concern — adequate IV fluids started.', 'section' => 'P'],
            ['id' => 'x1', 'text' => 'Utility company name on truck.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'OSHA notification pending.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Lunch cooler in bucket truck.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Weather windy but dry.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Hard hat cracked.', 'section' => 'X'],
            ['id' => 'x6', 'text' => 'Union steward phone unknown.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Mass casualty — triage red patient',
        'scenario' => 'Single EMS unit first on scene of bus crash extracts most critical patient during triage.',
        'detail' => '12 patients total. Incident command established. Your patient: unresponsive with agonal respirations.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Found unresponsive by triage officer in immediate category.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Mechanism: bus rollover per incident command.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'GCS 3, agonal respirations 4/min, cyanotic.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Pelvic instability, abdominal distension.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'BP unobtainable, pulse thready 140, SpO₂ 70%.', 'section' => 'O'],
            ['id' => 's6', 'text' => 'Immediate (red) — critical trauma with airway compromise.', 'section' => 'A'],
            ['id' => 's7', 'text' => 'Hemorrhagic shock and probable traumatic arrest progression.', 'section' => 'A'],
            ['id' => 's8', 'text' => 'Load-and-go: airway intervention, pelvic binder, one unit transport, MCI radio report.', 'section' => 'P'],
            ['id' => 's9', 'text' => 'Triage tag applied: red, time 1432.', 'section' => 'O'],
            ['id' => 's10', 'text' => 'Second patient deferred to incoming unit per MCI protocol.', 'section' => 'P'],
            ['id' => 'x1', 'text' => 'Bus company logo visible.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Media helicopter not yet arrived.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Road closed both directions.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Volunteer firefighter brought water.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Patient wallet not priority.', 'section' => 'X'],
            ['id' => 'x6', 'text' => 'Incident name assigned by dispatch.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Aortic dissection mimic',
        'scenario' => '64-year-old with tearing chest pain radiating to back, unequal blood pressures in arms.',
        'detail' => 'Pain sudden onset 25 min ago. Hx: hypertension, Marfanoid habitus. Medications: metoprolol.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Sudden tearing chest pain radiating to interscapular area.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Denies trauma; pain maximal at onset.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'BP right arm 186/102, left arm 134/78.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Pulse deficit noted right radial vs left.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Diaphoretic, anxious, lungs clear, no JVD.', 'section' => 'O'],
            ['id' => 's6', 'text' => 'Suspected aortic dissection — hypertensive emergency.', 'section' => 'A'],
            ['id' => 's7', 'text' => 'Cannot exclude STEMI overlap — obtain 12-lead without delaying transport.', 'section' => 'A'],
            ['id' => 's8', 'text' => 'Keep heart rate and BP controlled per protocol, analgesia, surgical center transport.', 'section' => 'P'],
            ['id' => 's9', 'text' => '12-lead: sinus tachycardia, no ST elevation.', 'section' => 'O'],
            ['id' => 's10', 'text' => 'Large-bore IV access bilateral antecubital.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Patient retired military.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Wife packing hospital bag.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Pain started during yard work.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Neighbor is a nurse — assisted.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Living room has tall ceiling.', 'section' => 'X'],
            ['id' => 'x6', 'text' => 'Medication pill box labeled M-F.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Organophosphate exposure',
        'scenario' => 'Farmworker with SLUDGE symptoms after pesticide spray in enclosed barn.',
        'detail' => 'Colleague reports patient collapsed while mixing chemicals. Multiple workers exposed, yours most severe.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Colleague reports acute illness after pesticide exposure in barn.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Patient complains of blurred vision, nausea, and weakness.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Profuse salivation, lacrimation, bronchorrhea, miotic pupils.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Fasciculations observed, RR 24, SpO₂ 91%.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'BP 98/62, pulse 52 — bradycardia present.', 'section' => 'O'],
            ['id' => 's6', 'text' => 'Organophosphate poisoning — cholinergic crisis.', 'section' => 'A'],
            ['id' => 's7', 'text' => 'Risk of respiratory failure from secretions.', 'section' => 'A'],
            ['id' => 's8', 'text' => 'Decontaminate, atropine and pralidoxime per ALS protocol, airway management, hazmat notify.', 'section' => 'P'],
            ['id' => 's9', 'text' => 'Chemical container labeled organophosphate — photo taken.', 'section' => 'O'],
            ['id' => 's10', 'text' => 'Patient\'s clothing removed and bagged.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Farm owned by family three generations.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Barn cat ran outside.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Tractor idling in field.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Harvest festival next month.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Patient speaks limited English — interpreter phone used.', 'section' => 'X'],
            ['id' => 'x6', 'text' => 'Work boots muddy.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Termination of resuscitation — family present',
        'scenario' => '78-year-old found in asystole, 35 minutes of ACLS without ROSC, family requesting cessation.',
        'detail' => 'Witnessed collapse at family dinner. PEA throughout. Reversible causes addressed. Physician on radio orders termination.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Family reports sudden collapse during dinner.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Patient has DNR discussion pending — no form on scene.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Asystole on monitor after 35 min ACLS.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'No ROSC after epinephrine x4, defibrillation not indicated.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Reversible causes: no hypothermia, no tamponade signs, glucose 118.', 'section' => 'O'],
            ['id' => 's6', 'text' => 'Medical control authorizes termination of resuscitation.', 'section' => 'O'],
            ['id' => 's7', 'text' => 'Cardiac arrest unresponsive to ACLS — pronouncement.', 'section' => 'A'],
            ['id' => 's8', 'text' => 'Time of death documented 2051.', 'section' => 'A'],
            ['id' => 's9', 'text' => 'Family notified with compassion, chaplain requested.', 'section' => 'P'],
            ['id' => 's10', 'text' => 'Leave IV and airway in place per local protocol; law enforcement notified.', 'section' => 'P'],
            ['id' => 'x1', 'text' => 'Dinner was pot roast.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Grandchildren in upstairs bedroom.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Ambulance mileage 12 miles.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Patient collected stamps.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Living room carpet antique.', 'section' => 'X'],
            ['id' => 'x6', 'text' => 'Weather cold outside.', 'section' => 'X'],
        ],
    ],
];
