<?php

return [
    [
        'title' => 'MVC with neck pain',
        'scenario' => '32-year-old restrained driver in rear-end collision, ambulatory, complaining of neck stiffness.',
        'detail' => 'Airbags deployed. Patient denies LOC. C-spine precautions maintained. Mechanism: moderate-speed impact.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Patient states neck pain began immediately after impact.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Denies numbness or tingling in extremities.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Midline cervical tenderness without step-off.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Alert, GCS 15, BP 126/78, pulse 88.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Possible cervical spine injury — mechanism and symptoms.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'C-collar, spinal motion restriction, transport.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'Steering wheel deformed on inspection.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Traffic was heavy due to rush hour.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Patient listens to podcasts on commutes.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Tow truck estimated 20-minute wait.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Unresponsive hypoglycemia',
        'scenario' => '58-year-old diabetic found minimally responsive at home by spouse.',
        'detail' => 'Spouse reports patient skipped dinner. Home glucose monitor reads "LO".',
        'sentences' => [
            ['id' => 's1', 'text' => 'Spouse reports patient was confused then became unresponsive.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Last oral intake was breakfast.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Minimal response to painful stimulus, unable to swallow.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Glucose 34 mg/dL, skin cool and diaphoretic.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Severe hypoglycemia with altered mental status.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Airway management, IV glucose per protocol, transport.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'No insulin pen found at bedside.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Bedroom clock showed 2145.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Couple watched a movie earlier.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Cat was sleeping on the couch.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'COPD exacerbation',
        'scenario' => '67-year-old with progressive dyspnea and productive cough over 3 days, worse today.',
        'detail' => 'Home O₂ at 2 L/min normally. Increased sputum purulence reported.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Patient reports worsening shortness of breath and thick yellow sputum.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'States home oxygen not relieving symptoms today.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Prolonged expiratory phase, diffuse wheezes, speaking in phrases.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'SpO₂ 86% on 2 L O₂, RR 30, BP 148/92.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Acute COPD exacerbation with hypoxemia.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'High-flow oxygen per protocol, bronchodilator, transport.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'Barrel chest noted on inspection.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Patient retired from teaching last year.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Weather forecast predicted rain.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Living room carpet recently vacuumed.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Adult postictal seizure',
        'scenario' => '41-year-old found confused after witnessed tonic-clonic activity at grocery store.',
        'detail' => 'Bystander reports ~90 seconds of convulsions. No known epilepsy history.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Bystander describes generalized shaking lasting under 2 minutes.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Patient does not recall the event.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Postictal confusion, tongue laceration, incontinence noted.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'GCS 13 (E3 V4 M6), glucose 98, BP 142/88.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'New-onset seizure, postictal — rule out secondary cause.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Protect airway, supplemental O₂, IV access, transport.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'No medic alert jewelry identified.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Store manager offered a free coupon.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Shopping cart contained milk and bread.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Parking lot was partially shaded.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Upper GI bleed',
        'scenario' => '55-year-old with hematemesis and lightheadedness, history of alcohol use.',
        'detail' => 'Two episodes of coffee-ground emesis. Skin pale. Last drink was yesterday.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Patient reports vomiting blood twice over one hour.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Complains of dizziness when standing.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Pale, diaphoretic, dry mucous membranes.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'BP 94/58, pulse 118, RR 22, SpO₂ 96%.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Suspected upper GI hemorrhage with hypovolemia.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'NPO, IV access, rapid transport, monitor for shock.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'Melena noted on patient\'s clothing.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Patient prefers decaf coffee.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Ambulance bay was being repaved.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Family requested a specific hospital.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'First-trimester bleeding',
        'scenario' => '26-year-old female, 10 weeks pregnant, vaginal bleeding and cramping.',
        'detail' => 'LMP confirms gestational age. No prior pregnancy complications. Hx: one prior term delivery.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Patient reports bright red vaginal bleeding and lower abdominal cramping.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Denies dizziness or shoulder pain.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Mild suprapubic tenderness, no guarding, vitals stable.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'BP 118/74, pulse 92, SpO₂ 99%, approx. 50 mL blood loss noted.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Threatened miscarriage — cannot rule out ectopic.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Left lateral position, IV access, monitor, transport to OB-capable facility.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'Fundal height not assessed — early gestation.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Patient read a pregnancy book last week.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Partner drove a blue sedan.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Ultrasound scheduled for next month.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Stroke — FAST positive',
        'scenario' => '73-year-old with sudden right-sided weakness and slurred speech, last known well 45 minutes ago.',
        'detail' => 'Wife witnessed onset during dinner. No head trauma. On aspirin daily.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Wife reports sudden onset facial droop and arm weakness.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Patient states speech became slurred at dinner.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Right facial droop, arm drift, dysarthria present.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'BP 168/94, pulse 88 irregular, glucose 142, SpO₂ 97%.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Suspected acute stroke — LKW within treatment window.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Stroke alert notification, rapid transport to stroke center.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'Last known well time documented as 1845.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Dinner included grilled chicken.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Couple plans vacation in spring.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'TV was on in the background.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Hyperglycemia with ketosis',
        'scenario' => '22-year-old type 1 diabetic with polyuria, abdominal pain, and Kussmaul respirations.',
        'detail' => 'Ran out of insulin 2 days ago. Roommate called 911 for increasing confusion.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Patient reports nausea, abdominal pain, and excessive thirst.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'States insulin supply ran out 48 hours ago.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Deep rapid respirations, fruity breath, dry mucous membranes.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Glucose 486 mg/dL, BP 102/64, pulse 118, RR 28.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Diabetic ketoacidosis suspected.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'IV access, fluid resuscitation per protocol, rapid transport.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'Skin turgor decreased.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Patient is a college sophomore.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Pharmacy closed early yesterday.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Roommate studies engineering.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Moderate allergic reaction',
        'scenario' => '31-year-old with diffuse hives after new antibiotic, no airway compromise.',
        'detail' => 'Took first dose 2 hours ago. No lip or tongue swelling. Breathing comfortable.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Patient reports generalized itching after starting amoxicillin.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Denies throat tightness, wheezing, or dizziness.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Generalized urticaria, lungs clear, no facial edema.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'BP 122/76, pulse 84, RR 16, SpO₂ 99%.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Allergic reaction without anaphylaxis.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Diphenhydramine per protocol, monitor, transport if protocol requires.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'No prior penicillin allergy documented.', 'section' => 'S'],
            ['id' => 'x1', 'text' => 'Prescription bottle label is legible.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Patient works from home.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Pharmacy bag was on the counter.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Partial finger amputation',
        'scenario' => '44-year-old industrial worker with traumatic partial amputation of left index finger.',
        'detail' => 'Injury from table saw 15 minutes ago. Digit partially attached. Bleeding controlled with pressure.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Patient reports saw injury while cutting lumber.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Pain rated 8/10 at injury site.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Partial amputation left index finger, bleeding controlled.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'BP 134/82, pulse 102, skin pale at injury site.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Traumatic partial amputation, hemorrhage controlled.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Dressing, elevate, analgesia per protocol, transport with amputated part if separated.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'Neurovascular status distal to injury diminished.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Work shift started at 0700.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Safety goggles were worn.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Foreman called the company nurse.', 'section' => 'X'],
        ],
    ],
];
