<?php

return [
    [
        'title' => 'Multi-system trauma — fall from height',
        'scenario' => '27-year-old construction worker fell 15 feet from scaffolding, alert with multi-site pain.',
        'detail' => 'Fell onto concrete. Hard hat worn. C-spine immobilized by coworkers. ETA to trauma center 18 min.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Patient states he lost balance on scaffolding.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Reports pain in back, ribs, and left wrist.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'C-collar in place, midline C-spine tenderness.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Left wrist deformity, rib tenderness right lower chest.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'BP 104/68, pulse 112, RR 22, SpO₂ 96%.', 'section' => 'O'],
            ['id' => 's6', 'text' => 'Fall from height — multi-system trauma, spinal precautions.', 'section' => 'A'],
            ['id' => 's7', 'text' => 'Possible rib fractures and extremity fracture.', 'section' => 'A'],
            ['id' => 's8', 'text' => 'Spinal immobilization, IV access, analgesia, trauma center transport.', 'section' => 'P'],
            ['id' => 's9', 'text' => 'GCS 15 throughout encounter.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'OSHA investigator may follow up.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Lunch break was at 1130.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Scaffolding passed inspection last month.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Foreman name is on clipboard.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Crane visible in background.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Neonatal distress — home birth',
        'scenario' => 'Newborn 20 minutes old with cyanosis and poor respiratory effort, midwife on scene.',
        'detail' => 'Term pregnancy, spontaneous vaginal delivery. Apgar concern. Mother stable.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Midwife reports baby "not pinking up" after birth.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Mother denies complications during labor.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Newborn cyanotic, irregular respiratory effort, heart rate 90.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Muscle tone poor, grimace weak on stimulation.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Neonatal respiratory distress / possible perinatal compromise.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Warm, dry, stimulate, blow-by O₂, neonatal resuscitation per protocol, transport.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'Cord clamped and dry.', 'section' => 'O'],
            ['id' => 's8', 'text' => 'Gestational age estimated term by midwife.', 'section' => 'S'],
            ['id' => 's9', 'text' => 'Mother BP 118/74, no active bleeding.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Birth pool was in living room.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Playlist was playing softly.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Grandmother en route.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Baby blanket was handmade.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'House number is even.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Toxic ingestion — polypharmacy',
        'scenario' => '70-year-old found somnolent with empty bottles of opioids and benzodiazepines nearby.',
        'detail' => 'Daughter discovered patient. Unknown quantity ingested. Last seen normal 6 hours ago.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Daughter reports finding multiple empty prescription bottles.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Unclear if intentional; patient has chronic pain history.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Somnolent, responds to painful stimulus, pinpoint pupils.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'RR 8/min, SpO₂ 84% RA, BP 96/58, pulse 54.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Mixed overdose with respiratory depression.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Airway support, naloxone per protocol, glucose check, transport.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'No trauma noted.', 'section' => 'O'],
            ['id' => 's8', 'text' => 'Suicide note not found.', 'section' => 'O'],
            ['id' => 's9', 'text' => 'Medication list includes oxycodone and alprazolam.', 'section' => 'S'],
            ['id' => 'x1', 'text' => 'Daughter works night shift.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'TV was on static channel.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Cat food bowl was full.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Mailbox had three letters.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Patient enjoys gardening.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Eclampsia',
        'scenario' => '34-year-old pregnant female, 36 weeks, postictal after generalized seizure at home.',
        'detail' => 'Husband reports hypertension at OB visit yesterday. Headache and visual changes today.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Husband witnessed tonic-clonic seizure ~3 minutes.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Patient complained of severe headache and seeing spots earlier.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Postictal, pregnant abdomen gravid, 3+ pitting edema bilateral legs.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'BP 186/118, pulse 108, RR 20, SpO₂ 97%.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Eclampsia until proven otherwise.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Left lateral tilt, high-flow O₂, magnesium per ALS protocol, OB emergency transport.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'Reflexes hyperactive on assessment.', 'section' => 'O'],
            ['id' => 's8', 'text' => 'Fetal heart tones not assessed in field.', 'section' => 'O'],
            ['id' => 's9', 'text' => 'No vaginal bleeding noted.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Baby shower was last month.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Nursery painted green.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Husband called mother-in-law.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Due date is in three weeks.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Weather was humid.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Lightning strike — cardiac arrest',
        'scenario' => '42-year-old golfer found apneic after lightning strike, bystander CPR in progress.',
        'detail' => 'Strike 4 minutes ago. AED unavailable on course. ROSC achieved after 1 shock en route.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Bystander reports lightning hit tree near patient.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Patient collapsed immediately; CPR started within 1 minute.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Initial rhythm VF, defibrillated x1, ROSC at 2047.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Linear burn entry right shoulder, exit foot, pupils sluggish.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Pulse 88 post-ROSC, BP 92/60, GCS 6.', 'section' => 'O'],
            ['id' => 's6', 'text' => 'Lightning strike with cardiac arrest, post-ROSC.', 'section' => 'A'],
            ['id' => 's7', 'text' => 'Risk of recurrent arrhythmia and multisystem injury.', 'section' => 'A'],
            ['id' => 's8', 'text' => 'Continue monitoring, IV access, rapid transport, avoid c-spine immobilization unless indicated.', 'section' => 'P'],
            ['id' => 's9', 'text' => 'Oxygen via BVM transitioned to NRB at 15 L.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Golf cart parked at hole 7.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Tournament was friendly match.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Storm siren sounded earlier.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Patient\'s clubs are TaylorMade.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Pro shop sold umbrellas.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Spinal cord injury — diving',
        'scenario' => '18-year-old hit head on pool bottom, floating face-down, now immobilized with neck pain.',
        'detail' => 'Diving into shallow end. Immediate paralysis reported by friends. GCS 14.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Friends report dive into shallow end of pool.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Patient states he cannot move legs.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'C-collar applied, midline cervical tenderness, no rectal tone assessed.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Motor: upper extremities weak bilaterally, lower extremities 0/5.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Sensory level approximately T4 per patient report.', 'section' => 'S'],
            ['id' => 's6', 'text' => 'Suspected cervical spinal cord injury.', 'section' => 'A'],
            ['id' => 's7', 'text' => 'Maintain spinal motion restriction, IV access, transport to trauma center.', 'section' => 'P'],
            ['id' => 's8', 'text' => 'BP 98/62, pulse 58 — concern for neurogenic shock.', 'section' => 'O'],
            ['id' => 's9', 'text' => 'SpO₂ 97% on high-flow O₂.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Pool party had 12 attendees.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'DJ played pop music.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Graduation was last week.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Depth markers visible at 4 ft.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Lifeguard off duty — private pool.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Status asthmaticus',
        'scenario' => '16-year-old severe asthma unresponsive to home nebulizer, speaking single words.',
        'detail' => 'Peak flow 30% predicted. Prior ICU admission last year. Parents administered epinephrine auto-injector without improvement.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Parents report worsening wheeze despite 3 nebulizer treatments.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Patient can speak only single words.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Silent chest alternating with diffuse wheezes, severe retractions.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'SpO₂ 88% on O₂, RR 36, pulse 140, BP 130/84.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Status asthmaticus — impending respiratory failure.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Continuous bronchodilator per protocol, consider CPAP/BVM, rapid ALS transport.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'Accessory muscle use with nasal flaring.', 'section' => 'O'],
            ['id' => 's8', 'text' => 'Epinephrine auto-injector given 15 min ago per parent.', 'section' => 'S'],
            ['id' => 's9', 'text' => 'Skin pale and diaphoretic.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'School nurse phone number on file.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Allergy to cats documented.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Bedroom has asthma action plan poster.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Family cat kept outdoors.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Homework on desk.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Compartment syndrome risk',
        'scenario' => '25-year-old with crush injury to left lower leg, pain out of proportion after MVC.',
        'detail' => 'Dashboard intrusion. Leg entrapped 35 minutes. Pulses present initially, now diminished.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Patient reports crushing pain in left lower leg since extrication.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Pain worsens with passive toe extension.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Left calf firm and tense, pain disproportionate to exam.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'DP pulse diminished left foot, cap refill 4 sec.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'BP 118/76, pulse 104, SpO₂ 98%.', 'section' => 'O'],
            ['id' => 's6', 'text' => 'Crush injury with concern for compartment syndrome.', 'section' => 'A'],
            ['id' => 's7', 'text' => 'Do not elevate leg; splint in position found, rapid transport.', 'section' => 'P'],
            ['id' => 's8', 'text' => 'Open fracture not present.', 'section' => 'O'],
            ['id' => 's9', 'text' => 'Motor function toes decreased left side.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Vehicle is a sedan.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Airbag deployed driver side only.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Patient was driving to gym.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Intersection has traffic camera.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Tow truck ETA 30 minutes.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Distributive shock — anaphylaxis refractory',
        'scenario' => '38-year-old with peanut exposure, hypotensive after two epinephrine doses.',
        'detail' => 'Restaurant exposure 20 min ago. Stridor present. Second epi given 5 min ago by bystander MD.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Patient ate dish with undisclosed peanut oil.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Reports throat closing and dizziness.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Stridor, diffuse urticaria, angioedema lips and tongue.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'BP 78/42, pulse 132, SpO₂ 90%, RR 28.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Refractory anaphylaxis with distributive shock.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Repeat epinephrine per protocol, aggressive airway prep, IV fluids, rapid transport.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'Two prior epinephrine auto-injector doses documented.', 'section' => 'S'],
            ['id' => 's8', 'text' => 'Bronchospasm with bilateral wheezes.', 'section' => 'O'],
            ['id' => 's9', 'text' => 'Patient carries epinephrine — used both pens.', 'section' => 'S'],
            ['id' => 'x1', 'text' => 'Restaurant name on receipt.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Dinner reservation was 1900.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Waiter apologized repeatedly.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Patient is a food blogger.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Valet parking used.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'STEMI — active chest pain',
        'scenario' => '59-year-old male with ongoing crushing chest pain, diaphoresis, and ST elevation on monitor.',
        'detail' => 'Pain began 40 min ago at rest. Nitroglycerin x1 without relief. ASA allergy: none.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Crushing substernal pain radiating to left arm, 8/10.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Denies relief after sublingual nitroglycerin.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Diaphoretic, anxious, lungs clear.', 'section' => 'O'],
            ['id' => 's4', 'text' => '12-lead: ST elevation II, III, aVF.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'BP 148/92, pulse 98, SpO₂ 94%, RR 20.', 'section' => 'O'],
            ['id' => 's6', 'text' => 'STEMI — inferior wall pattern.', 'section' => 'A'],
            ['id' => 's7', 'text' => 'Time-sensitive coronary occlusion suspected.', 'section' => 'A'],
            ['id' => 's8', 'text' => 'Aspirin, nitroglycerin per protocol, STEMI alert, cath lab activation, rapid transport.', 'section' => 'P'],
            ['id' => 's9', 'text' => 'No JVD or rales on exam.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Patient retired from accounting.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Wife drove to meet at hospital.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Pain started while watching TV.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Garage has two cars.', 'section' => 'X'],
            ['id' => 'x5', 'text' => 'Neighbor waved at ambulance.', 'section' => 'X'],
        ],
    ],
];
