<?php

return [
    [
        'title' => 'Pediatric asthma — moderate',
        'scenario' => '7-year-old with audible wheezing, retractions, and SpO₂ 90% after playing outside.',
        'detail' => 'Mother reports increased albuterol use this week. No fever. PMH: asthma since age 3. Allergies: none known.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Mother states wheezing worsened over 2 hours after soccer.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Child reports chest feels "tight."', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Intercostal retractions, diffuse wheezes, speaking in short phrases.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'SpO₂ 90% RA, RR 32, pulse 128, temp 37.1°C.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Moderate pediatric asthma exacerbation.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Oxygen, bronchodilator per protocol, parent ride-along, transport.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'Peak flow 45% of personal best per mother.', 'section' => 'S'],
            ['id' => 's8', 'text' => 'No cyanosis noted.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Soccer coach is Mr. Daniels.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Snack after game was oranges.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Field number 3 was in use.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Mother parked a minivan.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Elder fall — hip pain',
        'scenario' => '81-year-old female found on bathroom floor after slip, unable to bear weight on right leg.',
        'detail' => 'On warfarin for AFib. No LOC. Assisted living staff on scene. Time on floor ~30 minutes.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Patient reports slipping on wet tile.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Right hip pain 9/10, denies hitting head.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Right leg shortened and externally rotated.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Alert, GCS 15, BP 108/64, pulse 98.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Suspected hip fracture, fall without head strike.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Pain management, gentle movement avoidance, transport.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'Anticoagulant use increases bleeding risk.', 'section' => 'A'],
            ['id' => 's8', 'text' => 'No anticoagulant bruising elsewhere on exam.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Bathroom rug was blue.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Facility serves lunch at noon.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Patient enjoys crossword puzzles.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Weather was overcast.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Carbon monoxide exposure',
        'scenario' => 'Family of three with headaches and nausea after gas furnace malfunction overnight.',
        'detail' => 'CO detector reading 180 ppm on arrival. All ambulatory. Children ages 6 and 9.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Parents report waking with headache and nausea.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Children complain of dizziness and "feeling weird."', 'section' => 'S'],
            ['id' => 's3', 'text' => 'All patients alert, mild confusion in father only.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'SpO₂ 94–97% on room air; CO level pending.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Suspected CO poisoning — multiple victims.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Remove from environment, high-flow O₂, transport all, fire department notified.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'Cherry-red skin not observed.', 'section' => 'O'],
            ['id' => 's8', 'text' => 'Furnace service overdue per homeowner.', 'section' => 'S'],
            ['id' => 'x1', 'text' => 'House built in 1985.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Family dog also in home, asymptomatic.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Mail was delivered at 0900.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Neighbor owns a pickup truck.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Drowning — rescued child',
        'scenario' => '5-year-old pulled from community pool, coughing with return of spontaneous breathing.',
        'detail' => 'Submersion time estimated under 2 minutes. CPR not required. Pool depth 4 feet.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Lifeguard reports child was underwater briefly.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Child crying, says "I swallowed water."', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Coughing with coarse lung sounds, SpO₂ 93%.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Pulse 120, RR 28, temp 36.8°C, alert.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Near-drowning with respiratory compromise.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Oxygen, spinal precautions not indicated, transport for monitoring.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'No vomiting noted.', 'section' => 'O'],
            ['id' => 's8', 'text' => 'Parent consents to transport.', 'section' => 'S'],
            ['id' => 'x1', 'text' => 'Pool water temperature was comfortable.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Swim class scheduled next week.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Child wore blue swim trunks.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Concession stand sold pretzels.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Psychiatric crisis',
        'scenario' => '29-year-old with agitation, auditory hallucinations, and suicidal ideation per family.',
        'detail' => 'No weapons visible. History of bipolar disorder, missed medications 3 days. Cooperative with crew.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Patient reports hearing voices telling him to harm himself.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Family states he stopped lithium 3 days ago.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Agitated but cooperative, speech pressured, no focal neuro deficits.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'BP 138/86, pulse 104, RR 18, SpO₂ 99%.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Acute psychiatric emergency with suicidal ideation.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Calm approach, transport per mental health protocol, law enforcement if needed.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'No homicidal ideation expressed.', 'section' => 'S'],
            ['id' => 's8', 'text' => 'Empty pill bottles found in bedroom.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Patient enjoys playing guitar.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'TV was on a music channel.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Apartment lease renews in fall.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Sister brought iced tea.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Traumatic pneumothorax',
        'scenario' => '24-year-old stabbed to right chest, decreasing breath sounds on affected side.',
        'detail' => 'Penetrating trauma 8 minutes ago. Initial SpO₂ 88%. No known allergies.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Patient reports sudden knife injury during altercation.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Increasing difficulty breathing since injury.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Decreased breath sounds right hemithorax, JVD absent.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'SpO₂ 88%, RR 30, BP 102/70, pulse 118.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Open pneumothorax / penetrating chest trauma.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Occlusive dressing, high-flow O₂, rapid transport, ALS intercept.', 'section' => 'P'],
            ['id' => 's7', 'text' => '1.5 cm stab wound right 4th ICS.', 'section' => 'O'],
            ['id' => 's8', 'text' => 'Trachea midline on assessment.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Altercation occurred near a bus stop.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Witness left before police arrived.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Patient\'s phone screen was cracked.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Weather was clear.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Sickle cell crisis',
        'scenario' => '19-year-old known sickle cell patient with severe generalized pain and fever.',
        'detail' => 'Pain 10/10 in back and legs. Treated at home with inadequate oral analgesia.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Patient describes severe bone pain worse than prior crises.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Reports fever and chills since yesterday.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Diffuse tenderness, jaundiced sclera, splenomegaly not assessed.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Temp 38.8°C, pulse 124, BP 118/72, SpO₂ 95%.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Sickle cell vaso-occlusive crisis with fever — rule out sepsis.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'IV access, fluid resuscitation, analgesia per protocol, transport.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'Hydration inadequate per patient.', 'section' => 'S'],
            ['id' => 's8', 'text' => 'Capillary refill 3 seconds.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Patient is a college athlete.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Roommate was studying nearby.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Campus health closed for holiday.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Pain scale poster on wall.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Hypertensive emergency symptoms',
        'scenario' => '62-year-old with severe headache, blurred vision, and BP 218/124.',
        'detail' => 'Ran out of antihypertensives 5 days ago. No chest pain. PMH: hypertension, CKD stage 2.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Sudden pounding headache and visual changes over 3 hours.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Missed blood pressure medications for several days.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Papilledema not assessed; patient reports blurred vision.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'BP 218/124, pulse 96, RR 18, SpO₂ 98%.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Hypertensive emergency until proven otherwise.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Keep patient calm, transport, avoid lowering BP rapidly in field.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'No focal neurologic deficits on screening exam.', 'section' => 'O'],
            ['id' => 's8', 'text' => 'Denies chest pain or dyspnea.', 'section' => 'S'],
            ['id' => 'x1', 'text' => 'Pharmacy auto-refill was disabled.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Patient watched news before headache.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Garage door was open.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Grandchildren visited last weekend.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Burns — scald',
        'scenario' => '3-year-old with partial-thickness burns to anterior chest and arm from hot soup spill.',
        'detail' => 'Injury 25 minutes ago. Cooled with running water at home. Parents very anxious.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Mother reports soup spilled on child at dinner.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Child crying, consolable in mother\'s arms.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Partial-thickness burns with blisters anterior chest and R arm.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'Pulse 130, RR 24, SpO₂ 99%, temp 37.0°C.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Pediatric scald burns — estimate TBSA at hospital.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Sterile dressing, keep warm, pain control, transport to burn center per protocol.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'No airway or inhalation injury signs.', 'section' => 'O'],
            ['id' => 's8', 'text' => 'Cooling applied ~10 minutes per parent.', 'section' => 'S'],
            ['id' => 'x1', 'text' => 'Soup was tomato basil flavor.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'High chair was wiped down.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Family dog barked at crew.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Dinner table seats four.', 'section' => 'X'],
        ],
    ],
    [
        'title' => 'Pelvic fracture — MVC',
        'scenario' => '38-year-old unrestrained passenger with pelvic pain after high-speed lateral impact.',
        'detail' => 'Vehicle intrusion on passenger side. Patient trapped 20 minutes. Vitals unstable on extrication.',
        'sentences' => [
            ['id' => 's1', 'text' => 'Patient reports severe pelvic pain since impact.', 'section' => 'S'],
            ['id' => 's2', 'text' => 'Denies loss of consciousness.', 'section' => 'S'],
            ['id' => 's3', 'text' => 'Pelvic instability on gentle palpation, seatbelt sign present.', 'section' => 'O'],
            ['id' => 's4', 'text' => 'BP 88/54, pulse 126, RR 24, SpO₂ 94%.', 'section' => 'O'],
            ['id' => 's5', 'text' => 'Suspected pelvic fracture with hemorrhagic shock.', 'section' => 'A'],
            ['id' => 's6', 'text' => 'Pelvic binder, IV access, rapid transport, minimize movement.', 'section' => 'P'],
            ['id' => 's7', 'text' => 'Distended abdomen noted.', 'section' => 'O'],
            ['id' => 's8', 'text' => 'Extrication completed at 2012.', 'section' => 'O'],
            ['id' => 'x1', 'text' => 'Traffic camera may have recorded crash.', 'section' => 'X'],
            ['id' => 'x2', 'text' => 'Driver transported separately.', 'section' => 'X'],
            ['id' => 'x3', 'text' => 'Tow company notified.', 'section' => 'X'],
            ['id' => 'x4', 'text' => 'Patient was commuting home from work.', 'section' => 'X'],
        ],
    ],
];
