<?php

return [
    'emt_basic' => [
        'pharma-contraindications' => require __DIR__.'/exercise_content/emt_basic/pharma_contraindications.php',
        'pharma-assist' => require __DIR__.'/exercise_content/emt_basic/pharma_assist.php',
        'pharma-matching' => require __DIR__.'/exercise_content/emt_basic/pharma_matching.php',
        'pharma-outcomes' => require __DIR__.'/exercise_content/emt_basic/pharma_outcomes.php',
        'pharma-dosage' => require __DIR__.'/exercise_content/emt_basic/pharma_dosage.php',
        'soap-charting' => require __DIR__.'/exercise_content/emt_basic/soap_charting.php',
        'soap_charting_levels' => require __DIR__.'/exercise_content/emt_basic/soap_charting_levels.php',
        'triage-start' => require __DIR__.'/exercise_content/emt_basic/triage_start.php',
        'triage-jumpstart' => require __DIR__.'/exercise_content/emt_basic/triage_jumpstart.php',
        'triage-salt' => require __DIR__.'/exercise_content/emt_basic/triage_salt.php',
        'triage-mci' => require __DIR__.'/exercise_content/emt_basic/triage_mci.php',
        'gcs-scenarios' => require __DIR__.'/exercise_content/emt_basic/gcs_scenarios.php',
        'burn-scoring' => require __DIR__.'/exercise_content/emt_basic/burn_scoring.php',
        'stroke-scale' => require __DIR__.'/exercise_content/emt_basic/stroke_scale.php',
        'vital-signs' => require __DIR__.'/exercise_content/emt_basic/vital_signs.php',
    ],

    'nclex_pn' => [
        'abc-prioritization' => require __DIR__.'/exercise_content/nclex_pn/abc_prioritization.php',
        'adpie-nursing-process' => require __DIR__.'/exercise_content/nclex_pn/adpie_nursing_process.php',
        'maslow-prioritization' => require __DIR__.'/exercise_content/nclex_pn/maslow_prioritization.php',
        'delegation' => require __DIR__.'/exercise_content/nclex_pn/delegation.php',
        'isolation-precautions' => require __DIR__.'/exercise_content/nclex_pn/isolation_precautions.php',
        'medication-rights' => require __DIR__.'/exercise_content/nclex_pn/medication_rights.php',
        'therapeutic-communication' => require __DIR__.'/exercise_content/nclex_pn/therapeutic_communication.php',
        'gcs-scoring' => require __DIR__.'/exercise_content/nclex_pn/gcs_scoring.php',
        'braden-scale' => require __DIR__.'/exercise_content/nclex_pn/braden_scale.php',
        'morse-fall-scale' => require __DIR__.'/exercise_content/nclex_pn/morse_fall_scale.php',
    ],

    'paramedic' => [
        'patient-assessment' => require __DIR__.'/exercise_content/paramedic/patient_assessment.php',
        'rhythm-12lead' => require __DIR__.'/exercise_content/paramedic/rhythm_12lead.php',
        'cardiology-treatment' => require __DIR__.'/exercise_content/paramedic/cardiology_treatment.php',
        'airway-respiratory' => require __DIR__.'/exercise_content/paramedic/airway_respiratory.php',
        'pharmacology-mastery' => require __DIR__.'/exercise_content/paramedic/pharmacology_mastery.php',
        'shock-hemodynamics' => require __DIR__.'/exercise_content/paramedic/shock_hemodynamics.php',
        'trauma-management' => require __DIR__.'/exercise_content/paramedic/trauma_management.php',
        'stroke-neurology' => require __DIR__.'/exercise_content/paramedic/stroke_neurology.php',
        'medical-emergencies' => require __DIR__.'/exercise_content/paramedic/medical_emergencies.php',
        'pediatrics-emergency' => require __DIR__.'/exercise_content/paramedic/pediatrics_emergency.php',
        'obstetrics-neonatal' => require __DIR__.'/exercise_content/paramedic/obstetrics_neonatal.php',
        'ems-operations-mci' => require __DIR__.'/exercise_content/paramedic/ems_operations_mci.php',
        'soap-charting' => require __DIR__.'/exercise_content/paramedic/soap_charting.php',
        'full-als-scenario' => require __DIR__.'/exercise_content/paramedic/full_als_scenario.php',
        'adaptive-nrp-readiness' => require __DIR__.'/exercise_content/paramedic/adaptive_nrp_readiness.php',
    ],
];
