<?php

require_once __DIR__.'/helpers.php';

return nclex_levels([
    [
        'title' => 'Clostridioides difficile',
        'scenario' => 'A client has watery diarrhea, positive stool PCR for C. difficile, and is on contact precautions. The room has a private toilet.',
        'question' => 'Which transmission-based precautions are required?',
        'options' => [
            'contact' => 'Contact precautions — gown and gloves; soap-and-water hand hygiene',
            'droplet' => 'Droplet precautions — surgical mask within 3 feet',
            'airborne' => 'Airborne precautions — N95 respirator and negative-pressure room',
            'standard' => 'Standard precautions only — no transmission-based precautions',
            'protective' => 'Protective (reverse) isolation — protect client from pathogens',
        ],
        'correct' => 'contact',
        'explanation' => 'C. difficile spreads by contact with spores. Use contact precautions with gown and gloves; perform hand hygiene with soap and water because alcohol-based rubs do not reliably remove spores.',
    ],
    [
        'title' => 'MRSA Wound Colonization',
        'scenario' => 'A client admitted from a long-term care facility has a chronic wound culture positive for MRSA. The client is alert, afebrile, with no respiratory symptoms.',
        'question' => 'Which precaution category applies?',
        'options' => [
            'contact' => 'Contact precautions for MRSA in wound',
            'droplet' => 'Droplet precautions for all MRSA regardless of site',
            'airborne' => 'Airborne precautions until two negative cultures',
            'standard' => 'Standard precautions only because client is afebrile',
            'protective' => 'Protective isolation to prevent MRSA acquisition',
        ],
        'correct' => 'contact',
        'explanation' => 'MRSA colonization or infection spread by direct contact requires contact precautions (gown and gloves) in addition to standard precautions, regardless of fever status.',
    ],
    [
        'title' => 'Active Pulmonary Tuberculosis',
        'scenario' => 'A client has productive cough, night sweats, weight loss, and sputum AFB smear positive. Chest X-ray shows cavitary upper-lobe infiltrates.',
        'question' => 'Which precautions should the PN implement?',
        'options' => [
            'contact' => 'Contact precautions with gown and gloves only',
            'droplet' => 'Droplet precautions with surgical mask',
            'airborne' => 'Airborne precautions — fit-tested N95 or PAPR and negative-pressure room',
            'standard' => 'Standard precautions until culture confirms TB',
            'protective' => 'Protective isolation for immunocompromised roommate protection',
        ],
        'correct' => 'airborne',
        'explanation' => 'Suspected or confirmed pulmonary TB requires airborne precautions: private negative-pressure room, door closed, and N95 respirator or equivalent for staff entering the room.',
    ],
    [
        'title' => 'Measles Exposure Risk',
        'scenario' => 'A child presents with high fever, cough, coryza, conjunctivitis, and Koplik spots. The provider suspects measles pending serology.',
        'question' => 'Which isolation precautions are indicated?',
        'options' => [
            'contact' => 'Contact precautions only',
            'droplet' => 'Droplet precautions with surgical mask',
            'airborne' => 'Airborne precautions until 4 days after rash onset (immune) or duration of illness',
            'standard' => 'Standard precautions because rash is not yet generalized',
            'protective' => 'Protective isolation for neutropenic clients sharing unit',
        ],
        'correct' => 'airborne',
        'explanation' => 'Measles is airborne-transmitted via respiratory droplet nuclei. Airborne precautions with N95 respirator and isolation per CDC guidelines apply for suspected and confirmed cases.',
    ],
    [
        'title' => 'Hospitalized COVID-19',
        'scenario' => 'A client is hospitalized with confirmed COVID-19 pneumonia, requiring supplemental oxygen but not intubation. Facility policy follows current CDC healthcare guidance.',
        'question' => 'Which precaution set is most appropriate for routine bedside care?',
        'options' => [
            'contact' => 'Contact precautions only — gown and gloves',
            'droplet' => 'Droplet precautions — gown, gloves, eye protection, and facemask',
            'airborne' => 'Airborne precautions for all COVID-19 clients regardless of procedure',
            'standard' => 'Standard precautions without mask because client is on nasal cannula',
            'protective' => 'Protective isolation — client is immunocompromised',
        ],
        'correct' => 'droplet',
        'explanation' => 'For routine care of hospitalized COVID-19 clients, combine standard precautions with transmission-based precautions (typically droplet and contact with eye protection and facemask). Airborne precautions are added for aerosol-generating procedures.',
        'level_options' => [
            4 => [
                'contact' => 'Contact precautions only in private room',
                'droplet' => 'Droplet precautions — gown, gloves, eye protection, and facemask',
                'airborne' => 'Airborne precautions for all care including routine vitals',
                'standard' => 'Standard precautions — COVID-19 is endemic, no PPE needed',
                'protective' => 'Reverse isolation to protect client from hospital flora',
            ],
            5 => [
                'contact' => 'Contact precautions without mask because client wears one',
                'droplet' => 'Droplet precautions — gown, gloves, eye protection, and facemask',
                'airborne' => 'Airborne only when performing nebulizer treatment or intubation',
                'standard' => 'Standard precautions until PCR confirms COVID-19',
                'protective' => 'Protective isolation because client receives steroids',
            ],
        ],
        'level_correct' => [
            5 => 'droplet',
        ],
    ],
    [
        'title' => 'Neutropenic Chemotherapy Client',
        'scenario' => 'A client receiving induction chemotherapy has absolute neutrophil count 200/mm³ and is admitted for monitoring. No active infection is present.',
        'question' => 'Which precaution approach protects this client?',
        'options' => [
            'contact' => 'Contact precautions to prevent MRSA spread from client',
            'droplet' => 'Droplet precautions for all visitors',
            'airborne' => 'Airborne precautions with N95 for all staff',
            'standard' => 'Standard precautions without special room requirements',
            'protective' => 'Protective (reverse) isolation — protect immunocompromised client from pathogens',
        ],
        'correct' => 'protective',
        'explanation' => 'Neutropenic clients need protective environment measures (reverse isolation): private room, HEPA filtration when available, restrict fresh flowers and raw foods per policy, and limit visitors with infections.',
    ],
    [
        'title' => 'Influenza — Confirmed Case',
        'scenario' => 'An adult client has sudden onset fever, myalgia, and influenza PCR positive during flu season. No lower respiratory complications.',
        'question' => 'Which transmission-based precautions apply?',
        'options' => [
            'contact' => 'Contact precautions only',
            'droplet' => 'Droplet precautions — surgical mask within 6 feet; private room preferred',
            'airborne' => 'Airborne precautions with N95 for all care',
            'standard' => 'Standard precautions because influenza is seasonal',
            'protective' => 'Protective isolation for the client\'s benefit',
        ],
        'correct' => 'droplet',
        'explanation' => 'Influenza spreads by droplets. Implement droplet precautions with surgical mask when within 6 feet, place in private room when possible, and continue for duration per facility policy (typically until 24 hours after fever resolves without antipyretics).',
    ],
    [
        'title' => 'Meningococcal Meningitis',
        'scenario' => 'A college student is admitted with sudden fever, severe headache, nuchal rigidity, and petechial rash. Lumbar puncture confirms Neisseria meningitidis.',
        'question' => 'Which precautions should the PN initiate immediately?',
        'options' => [
            'contact' => 'Contact precautions for stool and wound drainage',
            'droplet' => 'Droplet precautions — mask within 3–6 feet until 24 hours of effective antibiotics',
            'airborne' => 'Airborne precautions with negative-pressure room',
            'standard' => 'Standard precautions until culture returns',
            'protective' => 'Protective isolation because client is young and healthy',
        ],
        'correct' => 'droplet',
        'explanation' => 'Neisseria meningitidis requires droplet precautions until 24 hours after initiation of effective antibiotic therapy. Prophylaxis may be indicated for close contacts per public health guidance.',
    ],
    [
        'title' => 'Herpes Zoster — Immunocompetent',
        'scenario' => 'A healthy adult has localized vesicular rash in a single thoracic dermatome, diagnosed as herpes zoster (shingles). Rash is covered.',
        'question' => 'Which precautions are appropriate?',
        'options' => [
            'contact' => 'Contact precautions — gown and gloves for all care',
            'droplet' => 'Droplet precautions until vesicles crust',
            'airborne' => 'Airborne precautions for localized zoster in all clients',
            'standard' => 'Standard precautions with rash covered; airborne if disseminated or immunocompromised',
            'protective' => 'Protective isolation for the client',
        ],
        'correct' => 'standard',
        'explanation' => 'Localized herpes zoster in immunocompetent clients requires standard precautions with lesions covered. Airborne and contact precautions apply for disseminated zoster or immunocompromised clients because varicella-zoster virus can spread via airborne route.',
        'level_options' => [
            4 => [
                'contact' => 'Contact precautions until all vesicles crust',
                'droplet' => 'Droplet precautions for shingles always',
                'airborne' => 'Airborne precautions for localized zoster in immunocompetent host',
                'standard' => 'Standard precautions with rash covered; airborne if disseminated or immunocompromised',
                'protective' => 'Protective isolation because client takes antivirals',
            ],
            5 => [
                'contact' => 'Contact precautions — shingles is contact-only like MRSA',
                'droplet' => 'Droplet precautions with mask for all visitors',
                'airborne' => 'Airborne precautions for localized zoster in immunocompetent host',
                'standard' => 'Standard precautions with rash covered; airborne if disseminated or immunocompromised',
                'protective' => 'Reverse isolation to prevent bacterial superinfection',
            ],
        ],
    ],
    [
        'title' => 'Vancomycin-Resistant Enterococcus (VRE)',
        'scenario' => 'A client has a urine culture positive for VRE without systemic symptoms. The client shares a bathroom on the unit.',
        'question' => 'Which precautions are indicated?',
        'options' => [
            'contact' => 'Contact precautions — gown and gloves for room entry',
            'droplet' => 'Droplet precautions for urinary pathogens',
            'airborne' => 'Airborne precautions until culture clears',
            'standard' => 'Standard precautions because client is asymptomatic',
            'protective' => 'Protective isolation to protect client from VRE',
        ],
        'correct' => 'contact',
        'explanation' => 'VRE colonization or infection requires contact precautions to prevent spread via contaminated hands and surfaces, regardless of whether the client is symptomatic.',
    ],
]);
